### ISSUE TITLE
Image alignment breaks when using Gutenberg and Cubic theme on width > 768

### ISSUE THREAD

**Issue by sshevlyagin** [WordPress/gutenberg#10833]
**Describe the bug**
Image alignment breaks when using Gutenberg editor and Cubic theme

**To Reproduce**
1. Create a gallery on a post using the Gutenberg editor and the Cubic theme
2. Go to the page in a width greater than 768
3. Observe problem with images

**Workaround**
1. Comment out the large screen media section of the Boardwalk theme, lines 3224 – 3291 the problem went away.

**Expected behavior**
No image issues

**Screenshots**
No problem 767 – https://snag.gy/1mwznp.jpg

![1mwznp](https://user-images.githubusercontent.com/1119271/47328901-fd85a000-d62f-11e8-8b1c-500ec4897a28.jpg)

Problem 768 – https://snag.gy/efmb1g.jpg

![efmb1g](https://user-images.githubusercontent.com/1119271/47328909-02e2ea80-d630-11e8-9c16-c6adf8481c2e.jpg)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Brave (effectively Chrome)
 - Brave | 0.25.2
-- | --
- V8 | 6.9.427.23

**Additional context**
- Gutenberg 4.0.0
- Original forum post https://wordpress.org/support/topic/images-not-aligning-at-768-px

**Comment by youknowriad** [comment]
Looks like the original issue is fixed.

**Comment by portgordon** [comment]
This is still an issue for me, and commenting out the code described above does not appear to resolve the issue in my case. Any one else experiencing it?
