### ISSUE TITLE
Help text for PluginPostStatusInfo entry overlaps with content

### ISSUE THREAD

**Issue by SeanDS** [WordPress/gutenberg#10834]
**Describe the bug**
I upgraded to 4.0 and the help text for a `TextControl` I defined in the `PluginPostStatusInfo` slot started to overlap the text input component by a few pixels.

Disabling the CSS rule `margin-top: -8px` in the `.components-base-control .components-base-control__help` class fixes this.

**To Reproduce**
Here is a barebone JavaScript file that reproduces the error:

```javascript
var el = wp.element.createElement;
var __ = wp.i18n.__;
var registerPlugin = wp.plugins.registerPlugin;
var PluginPostStatusInfo = wp.editPost.PluginPostStatusInfo;
var TextControl = wp.components.TextControl;

function MyPostStatusInfoPlugin({}) {
    return el(
        PluginPostStatusInfo,
        {
            className: 'my-post-status-info'
        },
        el(
            TextControl,
            {
                name: 'my_edit_summary',
                label: __( 'Edit summary' ),
                help: __( 'Briefly summarise your changes' )
            }
        )
    );
}

registerPlugin( 'my-post-status-info-plugin', {
	render: MyPostStatusInfoPlugin
} );
```

Then in a WordPress plugin, enqueue the script to make it load:

```php
wp_enqueue_script(
	'some-slug',
	'/path/to/script.js',
	array( 'wp-edit-post', 'wp-plugins', 'wp-i18n', 'wp-element' ),
	'0.1'
);
```

**Expected behavior**
The help text should not overlap the text field.

**Screenshots**
With overlapping text:

![image](https://user-images.githubusercontent.com/5225190/47258112-16eae880-d486-11e8-81b3-5db19c081845.png)

Without overlapping text, after disabling the CSS rule `margin-top: -8px` in the `.components-base-control .components-base-control__help`:

![image](https://user-images.githubusercontent.com/5225190/47258217-962cec00-d487-11e8-8e44-ac9941375160.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox Nightly
 - Version: 64.0a1

**Comment by gziolo** [comment]
I'm still able to reproduce:

![Screen Shot 2019-10-21 at 11 20 15](https://user-images.githubusercontent.com/699132/67192958-cdb0da00-f3f4-11e9-83c7-7579d8640030.png)

**Comment by gziolo** [comment]
@jasmussen - is it something that should be fixed inside `TextControl`?

**Comment by tellthemachines** [comment]
Related: #9305

**Comment by SeanDS** [comment]
This is still broken. I'm also getting an issue with spacing between multiple `PluginPostStatusInfo` elements. Without any special fixes to the default CSS, this is what multiple boxes with help text look like:

![image](https://user-images.githubusercontent.com/5225190/83002923-24226e80-9ffd-11ea-9980-f090dd08f6ba.png)

I can fix it all with, in my case:

```css
/* Fix Gutenberg help text bug: https://github.com/WordPress/gutenberg/issues/10834 */
.components-base-control .components-base-control__help {
    margin-top: 0 !important;
}
.components-panel__row.ssl-alp-hide-revisions-panel,
.components-panel__row.ssl-alp-hide-crossreferences-panel {
    margin-top: 10px !important;
}
```

where `ssl-alp-hide-revisions-panel` and `ssl-alp-hide-crossreferences-panel` are the class names of the containing `<div>`s of the "Hide revisions" and "Hide cross-references" controls, respectively. Fixed, it looks like this:

![image](https://user-images.githubusercontent.com/5225190/83003356-b9256780-9ffd-11ea-8ad3-a034c1293007.png)

**Comment by paaljoachim** [comment]
Hey @SeanDS 
Could you retest and see if this is still valid?
How can we move it forward?

**Comment by SeanDS** [comment]
Now it looks like this:

![image](https://user-images.githubusercontent.com/5225190/108620788-5941dd00-7426-11eb-9e22-865303704dd2.png)

The CSS I mentioned above no longer has any effect, presumably because class names have changed since then.
I think the original problem is therefore technically fixed, though the spacing between those checkbox rows is still suspect. Is there an issue for that?

**Comment by paaljoachim** [comment]
Hey @SeanDS Sean

I searched and I was not able to find any issue that mentions it.
I am thinking you can close this issue and open a new issue (bug) and mention the CSS that needs to be fixed.
Have a continued great weekend!

**Comment by SeanDS** [comment]
Ok, will do, thanks.
