### ISSUE TITLE
Columns UI is still buggy and confusing

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11159]
**Describe the bug**
Following up on #10560, the columns block is still incredibly hard to use and confusing. There are so many issues that I can't really isolate much beyond to provide some screenshots and a GIF of TABing around and trying to figure out where the columns are.

**To Reproduce**
1. Insert a columns block

**Expected behavior**
1. Columns should be aligned and not overlap
1. It should be clear where each column is
1. It should be easy to insert a new block into either column in any order
1. It should be easy to use columns with a keyboard or mouse

**Screenshots**
![unclear initial state of columns block](https://user-images.githubusercontent.com/1238696/47608398-c02f6280-d9e1-11e8-85ab-88cfc847c96b.png)

![stranger overlapping and unclear icon placement of empty columns](https://user-images.githubusercontent.com/1238696/47608400-ca516100-d9e1-11e8-92be-a8cc25527354.png)

![animated gif showing confusing visual appearance of columns causing challenges to using it](https://user-images.githubusercontent.com/1238696/47608407-d4735f80-d9e1-11e8-93ab-401bbcb84059.gif)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Firefox 63
- WordPress 5.0-beta1-43823, Twenty Nineteen, no plugins

_Note: Updated the title which came off a little antagonistic. My apologies. That was not my best moment, and I'm being more thoughtful with subsequent bug report titles._

**Comment by pagelab** [comment]
Agreed. The lack of immediate visual cues makes quite difficult to understand how to fill the columns.

**Comment by StaggerLeee** [comment]
I suggest to fill each column with subtle background color. Something like #f5f5f5.

**Comment by pagelab** [comment]
Another option is to do just like Adobe Indesign and other desktop publishing apps: just add a blue border to show that this is a text frame.

![magnify1](https://user-images.githubusercontent.com/1451087/47616857-d819eb80-daa0-11e8-8cd4-35d69ac7bd76.png)

**Comment by StaggerLeee** [comment]
With some paddings, please. Looks amateurish this way.

**Comment by mrleemon** [comment]
Figuring out where to click in Gutenberg is like playing hide and seek with the editing system. The columns block is a clear example.

**Comment by slimmilkduds** [comment]
I have added a very subtle dashed border to the columns in the editor, it got great feedback from my users

**Comment by jasmussen** [comment]
I made a number of improvements in #11904. There are still many enhancements and refinements possible, but please test version 4.4 and see if it addresses any of the issues brought up here, and let's continue to think of ways to improve it.

**Comment by jasmussen** [comment]
@mrwweb The changes at this time are mostly stabilizing the implementation that's there. In that vein you can see the fixes included in https://github.com/WordPress/gutenberg/pull/11904 — mostly around the ability to select the contents of each column, as well as selecting the block itself, with the mouse. There are also improvements to the rendering on the front-end when you're using more than 2 columns, as well as the mobile view. I expect more radical changes to happen in the future, as the interface for nested blocks are improved further.

**Comment by mrwweb** [comment]
@jasmussen Sorry I couldn't get feedback in sooner. Life and work, y'know?

Anyway, there needs to be way more eyes on this than just mine. I am still _incredibly_ confused by the bugs I'm seeing when first inserting a block. These screenshots are all with Win 10, Firefox 63, WP 5.0-beta5, no plugins, and Twenty Nineteen:

The way default flexbox children work, columns don't fill the initial block width:
![image](https://user-images.githubusercontent.com/1238696/48754363-45571180-ec46-11e8-9974-2a9fe2645543.png)

Looking at the source is terrifying, so I can see how it might be hard to pull this off, but the current state is really confusing and hard to use.

The use of disappearing placeholder text (which is a [research-backed bad way to identify input areas](https://www.nngroup.com/articles/form-design-placeholders/)!) as the only sign of where the columns are makes it very confusing:
![image](https://user-images.githubusercontent.com/1238696/48754401-6d467500-ec46-11e8-9934-dbd4ae41cd78.png)

Even the neutral state (when cursor isn't in either column) doesn't scream "columns" to me:
![image](https://user-images.githubusercontent.com/1238696/48754427-82bb9f00-ec46-11e8-9fc8-2efef3f971d3.png)

And that neutral state doesn't come back if you add content and remove it:
![image](https://user-images.githubusercontent.com/1238696/48754697-708e3080-ec47-11e8-84d9-1cd6d998e45a.png)

Again, because of flexbox, short column content means the columns don't fill the width of the screen:
![image](https://user-images.githubusercontent.com/1238696/48754454-91a25180-ec46-11e8-87dc-a9e9d4852761.png)

...and adding blocks can end up with really weird looking results:

![image](https://user-images.githubusercontent.com/1238696/48754481-9ff06d80-ec46-11e8-9f1f-56a44faaea6d.png)

Strangely, once an image is inserted, the boxes seem to _stop_ flexing and become equal width. They don't contain an image that's been expanded:

![image](https://user-images.githubusercontent.com/1238696/48754508-b8608800-ec46-11e8-8659-d6face8e2173.png)

Here's a GIF showing a lot of those initial states and how incredibly unclear the column boundaries are and how confusing the block inserter position is (the weird gray stuff during image insertion and toward the end is a glitch in the recording and not visible when actually using the editor):
![confusing-columns](https://user-images.githubusercontent.com/1238696/48754547-e219af00-ec46-11e8-8a2c-274c93552790.gif)

Notably, at the end, I flip on the unified toolbar which means the column borders are now completely gone and what was very frustrating becomes nearly impossible.

The whole experience feels like it needs a rethink to me, but here are some immediate changes I would recommend:

- Columns should always fill the width of the parent block (as UI allows)
- Columns should always be equal width (at least until column resizing become available, and even then, I'd be very much in favor of only supporting a certain number of snappable resizing widths).
- The placeholder for columns should not be an empty paragraph but rather something that suggests both a boundary and emptiness. The image block provides useful guidance on this point.
- The inserter button should be centered in each column and persistently visible until a block is added to that column in a way so that the block is visible itself and can define the column.

This is so crude I considered not posting it, but here's the best I could get in a few minutes:

![image](https://user-images.githubusercontent.com/1238696/48754932-66206680-ec48-11e8-9702-a7a981d0493b.png)

I hope this is useful. I'm excited to have a good implementation for columns in the editor some day, but if 5.0 launches next week, I'd prefer columns get dropped from the release.

**Comment by jasmussen** [comment]
Good thoughts there, thanks for the feedback.

I don't know why you're seeing these issues, many of them should be fixed in Beta 5, notably the arbitrary width issues, and the content overflow issue. It's possible that the version of TwentyNineteen that shipped with Beta 5 did not include some of the necessary fixes we've pushed. Those might not go out until RC1 of TwentyNineteen goes out. In any case, here are a few GIFs of what I'm seeing.

Vanilla editor styles:

![columns vanilla](https://user-images.githubusercontent.com/1204802/48759896-e4aaf180-eca4-11e8-80ac-e3cf201b9577.gif)

![columns vanilla images](https://user-images.githubusercontent.com/1204802/48759907-ebd1ff80-eca4-11e8-81cd-7e60f8a729c4.gif)

TwentyNineteen:

![columns 2019](https://user-images.githubusercontent.com/1204802/48759915-effe1d00-eca4-11e8-8fe2-4d3ceff57451.gif)

Here's some Windows testing. Edge:

![edge](https://user-images.githubusercontent.com/1204802/48760612-c5ad5f00-eca6-11e8-8b32-eb07d0aaa91a.gif)

Firefox:

![firefox](https://user-images.githubusercontent.com/1204802/48760625-c940e600-eca6-11e8-86ab-1cb146fb8fe7.gif)

As noted, I agree there are many improvement that can be made. I like the suggestions on this thread, of showing some dashed outlines on the columns to make it more visually clear that you are editing columns. 

Your suggestion of improved appenders also makes sense, in fact we have the "non-paragraph based appender" that might work well here:

![generic-appender](https://user-images.githubusercontent.com/1204802/48760702-02795600-eca7-11e8-8474-84333b5621ed.png)

An additional improvement, which @alexislloyd mocked up would be to include the columns count in the block toolbar itself:

![block-toolbar](https://user-images.githubusercontent.com/1204802/48760732-145af900-eca7-11e8-8638-b5ecf92dfd3b.gif)

**Comment by mrwweb** [comment]
@jasmussen I'm seeing the same arbitrary width issues with [McCluhan](https://wordpress.org/themes/mcluhan/) enabled which makes me think it's not a theme issue (nor should it be, right?).

Yes to all the suggestions. Hopefully before 5.0 drops!

Win 10, Firefox 63.0.3, WP 5.0-beta5-43909, McCluhan 1.13

**Comment by mrwweb** [comment]
Update: Still seeing the "collapsed" initial display of columns with WordPress 5.0-RC1-43944 and Twenty Nineteen ("Version 1.0" whatever comes with the RC).

![image](https://user-images.githubusercontent.com/1238696/49027920-1402a800-f156-11e8-8c2a-223223f4a375.png)

**Comment by jasmussen** [comment]
@kjellr Any idea why he might be seeing this?

**Comment by kjellr** [comment]
> I'm seeing the same arbitrary width issues with McCluhan enabled which makes me think it's not a theme issue (nor should it be, right?).

Actually yes — I can confirm this. Using `5.0-RC1-43944`, I'm seeing this with all themes. So I don't think this is Twenty Nineteen-specific.  

**Gutenberg Starter Theme:**
<img width="640" alt="screen shot 2018-11-27 at 8 27 32 am" src="https://user-images.githubusercontent.com/1202812/49084786-7626e000-f21e-11e8-8866-e268dfe658b1.png">

**Twenty Seventeen**
<img width="755" alt="screen shot 2018-11-27 at 8 25 33 am" src="https://user-images.githubusercontent.com/1202812/49084798-80e17500-f21e-11e8-9970-350d444fc367.png">

**Comment by jasmussen** [comment]
Interesting. I can't reproduce but I'll give this another stab. I might ping you. Thanks Kjell.

**Comment by kjellr** [comment]
FWIW, setting the width of `editor-inner-blocks` to `100%` appears to solve the issue. Though I'm not sure why that's necessary in RC1, but not in the previous Gutenberg version. 

![columns-broken](https://user-images.githubusercontent.com/1202812/49085362-dff3b980-f21f-11e8-9d38-107d212bdcf9.gif)

**Comment by mrwweb** [comment]
Can we get this into the 5.0.0 milestone please? :)

**Comment by youknowriad** [comment]
I think I reproduce with the RC but not with the plugin.

**Comment by jasmussen** [comment]
I will have a fix for this no later than tomorrow, so we can be sure to get that fix into the 5.0 release.

**Comment by mrwweb** [comment]
@jasmussen @mtias @kjellr This is still the initial empty state of columns in RC3! Win 10, Firefox, no plugins, Twenty Nineteen.

![initial state of empty columns](https://user-images.githubusercontent.com/1238696/49483583-a22afe00-f7e8-11e8-8da0-d1ae49209353.png)

Why was this punted to 5.0.1? This looks and feels like a bug that people will notice immediately.

**Comment by afercia** [comment]
The reason for the wrong width when clicking in a column is in the different order of the stylesheets in the markup. This is something that emerged also in other issues: either Gutenberg guarantees its stylesheets are in the expected order or some selectors should have a higher specificity.

Specifically, here's the current order in the plugin (latest master) and in 5.0:
```
plugin:
block-library/theme.css
block-library/style.css   > .wp-block-columns = display: flex;  = width based on content
block-library/editor.css  > .wp-block-columns = display: block; = width 100%

Result: display block prevails and the columns take all the available width.

5.0
block-library/theme.css
block-library/editor.css  > .wp-block-columns = display: block; = width 100%
block-library/style.css   > .wp-block-columns = display: flex;  = width based on content

Result: display flex prevails and the columns width is based on their content: when the placeholder gets removed, the column is narrower. To reproduce, you can also edit in the browser's inspector the placeholder text to make it shorter and you will see the column shrinks.
```

**Comment by mrwweb** [comment]
Thanks for the very clear explanation, @afercia. That makes a lot of sense. It also makes me wonder what else has broken for the same reason.

Here's an example of the content-driven widths you mentioned:

![image](https://user-images.githubusercontent.com/1238696/49526321-7188aa00-f864-11e8-98d5-7970b7a6ffb5.png)

That almost certainly is not what a user will expect for a "two column layout".

**Comment by youknowriad** [comment]
AFAIK this is not an issue in the plugin, so I'm closing this issue in favor of this trac ticket https://core.trac.wordpress.org/ticket/45442

Let me know if I missed anything here.
