### ISSUE TITLE
Meta is not saved to preview

### ISSUE THREAD

**Issue by elliotcondon** [WordPress/gutenberg#11280]
**Describe the bug**
When previewing a post in Gutenberg, meta is not saved from metaboxes.

When previewing a post in the "classic editor", the form would submit and trigger the "save_post" action for the "revision" allowing plugins such as ACF to save postmeta from the $_POST data.

I assume that the "save_post" action is being fired correctly, but the metabox data is not available in $_POST. This results in no metadata saved for the preview.

Metadata should not be ignored from the "preview". Many agencies use custom fields to allow clients to edit bespoke websites who use preview in their workflow.

**To Reproduce**
1. Install ACF or any similar plugin.
2. Create a basic text field "test" for the page or post edit screen.
3. Fill in a value for this field and publish the post.
4. Edit the "single.php" template file to output this "test" meta (for visual reference)
5. Note that when viewing the post, you can see this meta data output into the HTML
6. Edit the post again and modify the field value
7. Click preview
8. Note that the "test" meta has not changed on the front-end. Also, the revision created in the DB does not contain any postmeta data.

**Expected behavior**
When viewing a preview (step 8), the "test" meta should reflect its updated value.

**Additional context**
- WordPress version 4.9.8
- Gutenberg plugin version 4.1.1

**Comment by earnjam** [comment]
Related to #9151

**Comment by danielbachhuber** [comment]
I was able to verify this issue:

![metavalue](https://user-images.githubusercontent.com/36432/47786481-24e00b00-dcc9-11e8-8bf4-4c06655f59b4.gif)

Notably:
1. If you change the value of your test meta box and hit "Preview", the change is not saved to the database and the Preview includes the old value.
2. If you change the value of your test meta box and hit "Save Draft", then the change _is_ saved to the database and the Preview includes the new value.

For published post, there's similar behavior: the change isn't included in the Preview until the "Update" button is clicked.

**Comment by danielbachhuber** [comment]
Also, for the next person, here's my test code for the meta box:

```
add_action( 'add_meta_boxes', function(){
	add_meta_box( 'test', 'Test', function(){
		echo '<input name="daniel_test" value="' . get_post_meta( get_the_ID(), 'daniel_test', true ) . '" />';
	});
});

add_action( 'save_post', function( $post_id ){
	if ( ! isset( $_POST['daniel_test'] ) ) {
		return;
	}
	update_post_meta( get_the_ID(), 'daniel_test', $_POST['daniel_test'] );
});

add_filter( 'the_content', function( $content ){
	$content .= 'Daniel test: ' . get_post_meta( get_the_ID(), 'daniel_test', true );
	return $content;
});
```

**Comment by adamsilverstein** [comment]
Worth noting that fixing this by saving meta will introduce a longstanding core bug: https://core.trac.wordpress.org/ticket/20299 - that is: because meta is not revisioned, we may need to update the actual post meta for previewing.

**Comment by danielbachhuber** [comment]
> Worth noting that fixing this by saving meta will introduce a longstanding core bug:

Correct. Because this is a known existing issue, it's safe to reintroduce.

**Comment by danielbachhuber** [comment]
Per `#core-restapi` [conversation today](https://wordpress.slack.com/archives/C02RQC26G/p1541092408046400), @adamsilverstein will work on this later this afternoon.

**Comment by gziolo** [comment]
It should be fixed with #11409.

**Comment by OksanaRomaniv** [comment]
Still experiencing the issue with WP Version 5.2.2 and ACF Pro 5.8.3

**Comment by thomasansems** [comment]
I can confirm that the issue is still here in WP 5.4.2

**Comment by ClareBryden** [comment]
As can I in WP 5.5.3

**Comment by Alimba86** [comment]
Same issues in WP 5.6.1

**Comment by PascalMarechal** [comment]
Same issues on WP 5.7.2

**Comment by roryashfordbentley** [comment]
Can we re-open this ticket to track the current status of this issue as the issue isnt resolved?

**Comment by ofhouse** [comment]
In case someone landed here, the current tracking issue is this: https://github.com/WordPress/gutenberg/issues/16006
