### ISSUE TITLE
Copied Editor Content Pastes HTML when using Paste as Plain Text

### ISSUE THREAD

**Issue by mrwweb** [WordPress/gutenberg#11742]
**Describe the bug**
When copying visual content out of Gutenberg and pasting it into other contexts with Paste as Plain Text (`CTRL` + `SHIFT` + `V`), it pastes HTML code, not plain text. The Classic Editor meets normal user expectations of this default browser feature.

**To Reproduce**
1. Copy formatted editor content
1. Open a non-WP content editor like Google Docs, Gmail, etc.
1. Paste with `CTRL` + `SHIFT` + V
1. **Result:** HTML code is pasted

**Screenshots**
The bug:
![paste-plain-text-html](https://user-images.githubusercontent.com/1238696/48317913-94010d80-e5ad-11e8-97ce-1962ed3210a9.gif)

Expected behavior:
![paste-plain-text-html-expected](https://user-images.githubusercontent.com/1238696/48317930-bb57da80-e5ad-11e8-8eca-cb4ca7cc8a5f.gif)

**Desktop (please complete the following information):**
Win 10, Firefox 63, WP 5.0-beta3, no plugins, Twenty Nineteen

**Comment by designsimply** [comment]
Tested and confirmed that using `Cmd+Shift+V` (paste without formatting) results in pasting HTML when copying and pasting multi-selected blocks. I found that it works as expected when copying the content from a single block. 

<sup>Tested with WordPress 4.9.8 and Gutenberg 4.3.0-rc.1 using Firefox 63.0.1 and Chrome 70.0.3538.77 on macOS 10.13.6.</sup>

**Comment by gziolo** [comment]
This works the same when using `Copy All Content` button in the More Menu:

![screen shot 2018-11-26 at 15 42 34](https://user-images.githubusercontent.com/699132/49020978-f0f5e980-f191-11e8-9ea6-2817e64f7548.png)

We should either align this behavior or change the name of the button to make it clear that HTML source is being copied.

**Comment by earnjam** [comment]
This looks like it was resolved at some point. It no longer copies the HTML markup. 

@mrwweb can you confirm so I can close this?

**Comment by earnjam** [comment]
Nevermind. It just didn't show the markup in Google Docs where I pasted. It still copied the HTML comments to the clipboard. When I paste in a text editor, I can see all the markup.

**Comment by mrwweb** [comment]
I can confirm that the reported behavior is still happening.

**Comment by mrwweb** [comment]
@gziolo's report is correct, but I think of it as a separate issue. See #11739.

**Comment by pwkip** [comment]
I believe this might be related: https://github.com/WordPress/gutenberg/issues/27386

**Comment by paaljoachim** [comment]
Tested with WordPress 5.7 beta 3.
Twenty Twenty One.

> To Reproduce
> Steps to reproduce the behavior:
> 
> Copy formatted editor content
> Open a non-WP content editor like Google Docs, Gmail, etc.
> Paste with CTRL + SHIFT + V
> Result: HTML code is pasted


Copied formatted editor content from 2 paragraph blocks and a list block.
Opened Gmail and pasted with CTRL + SHIFT + V

The result:
![Screen Shot 2021-02-21 at 02 18 16](https://user-images.githubusercontent.com/5323259/108612666-14e51b80-73eb-11eb-8ab4-5f4591272621.png)

So this issue has not yet been fixed.

**Comment by Pinny911** [comment]
Hi all, 

I actually can't figure out the problem and need your support. I can't figure out how to fix it. When I copied 3 or more blocks of a page from WordPress to Google Chrome or Microsoft Word, the text was copied like the code editor like the ones below. I just wanted the text but it was reproduced with the codes too.

Thank you, 


<h3></h3>



<p><strong>

**Comment by Mamaduka** [comment]
Hi, @mrwweb

I think this issue got fixed in recent Gutenberg versions. I was testing https://github.com/WordPress/gutenberg/issues/9018#issuecomment-1235725075 and tried Paste as Plain text command as well. It worked without an issue.

**Comment by Mamaduka** [comment]
I'm going to close the issue. I can no longer reproduce it.

Feel free to re-open it if you're still experiencing the problem.
