### ISSUE TITLE
Classic block: Convert to Blocks removes data, rb, and rtc elements

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#11775]
## The issue
`<data>`, `<rb>`, and `<rtc>` elements are not preserved when converting a Classic block to other blocks using the <kbd><samp>Convert to Blocks</samp></kbd> option.

## Reproduction steps
1. Create a post using the Classic Editor and open in it Gutenberg, or insert a Classic block in Gutenberg.
2. Open the <kbd><samp>More Options</samp></kbd> (ellipsis) menu and choose <kbd><samp>Edit as HTML</samp></kbd>.
3. Insert the following markup:
```html
<data value="value">data</data> <ruby>ruby <rb>rb</rb> <rp>rp</rp> <rt>rt</rt> <rtc>rtc</rtc> <rp>rp</rp></ruby>
```
4. Open the <kbd><samp>More Options</samp></kbd> menu again and choose <kbd><samp>Edit visually</samp></kbd>.
5. Press <kbd><samp>More Options</samp></kbd> → <kbd><samp>Convert to Blocks</samp></kbd>. This will result in a Paragraph block being created.
6. Press <kbd><samp>More Options</samp></kbd> → <kbd><samp>Edit as HTML</samp></kbd>.
7. The markup should all be preserved from the Classic block, but this bug causes `<data>`, `<rb>`, and `<rtc>` elements to be removed.

## Related issues and PRs
- #6102

**Comment by designsimply** [comment]
Thanks for clearly written issue! 

Since I wasn't familiar with these HTML elements, I looked them up and found some have limited browser compatibility charts and wanted to make a note about that:

* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/data#Specifications
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rb#Specifications
* https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rtc#Browser_compatibility

**Comment by nosolosw** [comment]
This is now fixed. Probably by some of the changes that affected https://github.com/WordPress/gutenberg/issues/12029

**Comment by ZebulanStanphill** [comment]
@nosolosw I can still reproduce in latest `master`. Please re-open.

**Comment by nosolosw** [comment]
Hi @ZebulanStanphill this is a GIF I've just recorded with the latest `master`:

![peek 2018-11-20 22-29](https://user-images.githubusercontent.com/583546/48804031-d8aa4880-ed13-11e8-82b4-ef15b9d5e1ec.gif)

I understood that was what you were expecting to happen, is that correct?

**Comment by ZebulanStanphill** [comment]
@nosolosw No. If you look at the resulting markup, some of the tags have been stripped out. The `<ruby>` tag (and some others) were not stripped out, but that's not what this ticket is about. I just put the `<ruby>` tag there since you're supposed to nest the `<rb>` and `<rtc>` elements inside of one, assuming I understand the HTML specification correctly.

The title of this issue says `<data>`, `<rb>`, and `<rtc>` elements are removed, and that is precisely what happens in your GIF.

**Comment by nosolosw** [comment]
Oh, you are so right, I was confused by the actual text while looking at other issues at the same time.

**Comment by ellatrix** [comment]
This is how the classic editor works (TinyMCE). There's nothing I can do about that. You'll notice that it works in Gutenberg:

1. Create a paragraph block. You'll have to type something in it so the controls appear.
2. Go to more options, then edit as HTML.
3. Insert:

```html
<p><data value="value">data</data> <ruby>ruby <rb>rb</rb> <rp>rp</rp> <rt>rt</rt> <rtc>rtc</rtc> <rp>rp</rp></ruby></p>
```

4. Edit visually. All content is there.
