### ISSUE TITLE
When you paste text from Microsoft word, it messes up all of the formatting

### ISSUE THREAD

**Issue by rachelleilani** [WordPress/gutenberg#11834]
When you paste text from Microsoft word, it messes up all of the formatting, which would be fine, but some of the words do not space. so my sentence ends up looking like "and then shelooked at" because there is not spacing, and even when I go back and fix it, for some reason it appears again, so I am continuously fixing it. This occurred on a Windows computer on Google Chrome and version 4.3.0 of Gutenberg.

**Comment by designsimply** [comment]
Thank you for the extra information. Last question, for the deleted paragraph, that may be a separate issue—was the paragraph deleted without notice or wast it replaced with a block validation error of some kind?

A new issue was filed with some steps to reproduce and screenshot at https://github.com/WordPress/gutenberg/issues/11853 and I am going to close this issue in favor of that one so we can consolidate the report to one place. This is a very good thing to report and I very much appreciate that you've posted about it! I will also continue looking into the paragraph issue, if it turns out to be separate issue then I can either re-open this one or start a new, more specific issue for that case.

**Comment by rachelleilani** [comment]
It had an error about coding or something, I don’t remember because I
deleted and fixed very quickly since I really want my work to be a
reflection of how I am so the lack of spacing is and issue.

**Comment by designsimply** [comment]
Okay. I think that sounds like a block validation error and is a separate issue. To help test/debug that one, I will want to know more about it such as what contents the paragraph had from the start and as many specific details/steps to reproduce the problem as possible (e.g. versions of Word and OS, how the paragraph was first created in Word, what kind of formatting it had, basically whatever steps to reproduce the problem).

First, though, the spaces issue seems more pressing and I tried but couldn't replicate the problem in testing. If you can think of anything at all I'm missing in my testing steps, please let me know! https://github.com/WordPress/gutenberg/issues/11853#issuecomment-438799135

**Comment by rachelleilani** [comment]
If you create the entire thing you’re trying to type in a word doc and
paste it over as ctrl+v instead of pasting as plain text, that’s when the
issue occurs. And I am using the brand new word that was just updated (I’m
on a school account so we always get the new roll out). And I write short
stories so it’s just my last paragraph of my short story. I can send you
the link to the actual story if that’ll help.

**Comment by designsimply** [comment]
Noting that #11853 was closed as a duplicate of #11588.

**Comment by designsimply** [comment]
> I am using the brand new word that was just updated.

I would like to note the version number for reference. I searched Google for "[What is the current latest stable version of Microsoft Word?](https://www.google.com/search?q=What+is+the+current+latest+stable+version+of+Microsoft+Word%3F)" and that led me to a Wikipedia article with a release history section that says:

| Year  Released | Name | Version | Comments |
| :--- | :--- | :--- | :--- |
| 2019 | Word 2019 | 16.0 | Included in Office 2019 |

Source: https://en.wikipedia.org/wiki/Microsoft_Word#Release_history

So I think you are using Word 2019 Version 16.0.

> It’s just my last paragraph of my short story. I can send you the link to the actual story if that’ll help.

If you can send me the last few paragraphs in a reply here (or in a Word document saved on the web? maybe upload it to your blog's media library and get the link directly from there?) then I can try to copy and paste that content specifically from Word (or Libre Offic in my case) into Gutenberg to see if I can get the same problem to happen. If that's too much trouble, pasting the last two paragraphs in a comment reply here would be a good alternate step I can try testing with. The trick for this issue will be to try to figure out if there's something in that paragraph specifically that is causing trouble. 🤔 another thing you might try would be to try copy and pasting just the problematic paragraph into a new draft and then check to see if the same problem happens again if you save and re-open the post.

**Comment by rachelleilani** [comment]
I did the last thing you suggested and didn’t have the issue again because
I updated the post the other day and it was fine so I don’t believe it was
the specific text.

**Comment by rachelleilani** [comment]
The more pressing issue for my is the deleting of spaces because I fix it,
and then I have to go back again and redo it all.

**Comment by databell** [comment]
I'm experiencing the same problem with pasting from Word / Mac 2008. It's an older version, but that shouldn't really matter. But it's making me want to switch to the Classic Editor instead. And I have a lot of blogging clients that already want me to either not update to 5.0 or simply install the CE.

**Comment by designsimply** [comment]
This issue should have been fixed in WordPress version 5.0.2 released on December 19, 2018. If you are still having trouble after updating to WordPress 5.0.2 or later, please check https://github.com/WordPress/gutenberg/issues/11588 for updates and leave a comment there noting your WordPress version and any relevant details you think may be helpful (i.e. you are using a very old version of Word). Thank you!

**Comment by staceylcummings** [comment]
It's not fixed. I'm on Wordpress 5.2.2; I'm on version 1906 excel, outlook and word. I copy text from these applications to Gutenberg. Randomly Gutenberg adds a space between words. I'm continually fixing it, the same ones over and over. It is getting very annoying.

**Comment by designsimply** [comment]
> Randomly Gutenberg adds a space between words.

The original issue here reported spaces being removed, not added. I think your issue is separate. @staceylcummings would you mind creating a new issue with all of the details from your comment at https://github.com/WordPress/gutenberg/issues/new/choose ?
