### ISSUE TITLE
Unexpected `&nbsp;` in pasted content

### ISSUE THREAD

**Issue by moorscode** [WordPress/gutenberg#11912]
**Describe the bug**
When pasting a text string ending in a space, a non-breaking space is being added.
This only happens if the text is being written in a block and copied from there.

**A string copied from another program will not yield these results.**

**To Reproduce**

1. I type the following piece of text in a paragraph block in the visual mode: "This is a text. "
1. I copy the piece of text to my clipboard
1. I paste the piece multiple times after each other, so they will be sentences within the same paragraph
1. I save the post
1. I reload the post
1. I open the code editor and see a lot of `&nbsp;` entries.

More instant results:

1. I type the following piece of text in a paragraph block in the visual mode: "This is a text. "
1. I switch to the code editor
1. I copy the piece of text (including the space)
1. I paste the text several times
1. I press "update"
1. The spaces are instantly converted into `&nbsp;` entries
1. Reloading the page does gives the same results.

Bit differently in this order:

1. I type the following piece of text in a paragraph block in the visual mode: "This is a text. "
1. I copy the text (including the space)
1. I switch to the code editor
1. I paste the text after the existing text
1. I press "publish"
1. The space after the first piece of copy is converted to a `&nbsp;` the rest of the spaces are normal
1. Reloading the page does gives the same results.

**Expected behavior**
I expect a regular space to be added instead of a non-breaking space. This will glue my two sentences together.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 70.0

**Additional context**
- Gutenberg 4.3.0
- WordPress 4.9.8

**Comment by iseulde** [comment]
I think #12166 should fix this issue. Could you confirm? Also, this seems to a duplicate of #7474?

**Comment by iseulde** [comment]
Should be fixed by #12166. Please reopen if that's not the case.

**Comment by giles14** [comment]
I'm still seeing this, when I copy-paste content from another source (including Wordpress editor) after and before using `<strong>` `</strong>` tags.

**Comment by ellatrix** [comment]
@giles14 could you please create a new issue?
