### ISSUE TITLE
Extra P tags added to custom dynamic blocks

### ISSUE THREAD

**Issue by mattheu** [WordPress/gutenberg#12646]
I have a a custom block that is dynamic and rendered using the render callback.
The custom block renders the excerpt. 

The render callback returns something like this:

```
<div>
    <a href="http://example.com"><?php echo get_the_excerpt(); ?></a>
</div>
```

Prior to Gutenberg 4.6 this worked as expected. After updating, I now get paragraph tags added around the link.

Digging into this a bit - it seems the regression was caused by this change: https://github.com/WordPress/gutenberg/commit/2a66db0fc99a9fb1ba99f61e59e6a0b2a4a5f9ef#diff-6ff32417da0658502e7caa1a1abbeae6

The key difference is the new code restores the `wpautop` filter at a later priority, which is still getting run.

Digging into this some more - it is actually because `get_the_excerpt` internally calls `apply_filters( 'the_content' ` - which is a bit of a headache. 

**To Reproduce**
The small test case below will reproduce the issue on the Gutenberg master.

```

add_action( 'after_setup_theme', function() {
	register_block_type( 'test/autopbug', [
		'render_callback' => 'test_autop_bug_render_callback',
	] );
} );

function test_autop_bug_render_callback() {
	ob_start();
	?>
<div class="test-autop-bug">

	<a href="http://example.com"><?php echo get_the_excerpt(); ?></a>

</div>
	<?php return ob_get_clean();
}

```

Then add the following block to a posts content using the code editor: 

```
<!-- wp:test/autopbug /-->
```

Then on the front end inspect the markup. The link will be wrapped in a paragraph. If you remove the call to `get_the_excerpt` then the link is not wrapped in a paragraph.

**Comment by danielbachhuber** [comment]
Does this issue reproduce with 5.0-RC3 too, or simply the plugin?

**Comment by mattheu** [comment]
I’ll try and test with 5.0-RC3

**Comment by mattheu** [comment]
@danielbachhuber Confirmed this is an issue with 5.0-RC3

**Comment by danielbachhuber** [comment]
@mattheu Ok. Can you create a Core Trac ticket and we'll get this fixed in `5.0.x`? Most of the PHP code in Gutenberg is going away once 5.0 ships.

**Comment by montaniasystemab** [comment]
This is still reproducible with version 5.0.3, using `get_the_excerpt()` inside a server rendered block

**Comment by tyrann0us** [comment]
Maybe related to #12530? There's a workaraound mentioned in https://github.com/WordPress/gutenberg/issues/12530#issuecomment-443736873.

**Comment by websevendev** [comment]
Another potential workaround - if you present the HTML as a `core/html` block and run it through `do_blocks()` then wpautop doesn't seem to be applied:

```php
function test_autop_bug_render_callback() {
	ob_start();
	?>
<div class="test-autop-bug">

	<a href="http://example.com"><?php echo get_the_excerpt(); ?></a>

</div>
	<?php return do_blocks('<!-- wp:html -->' . ob_get_clean() . '<!-- /wp:html -->');
}
```

Not sure if that has any side effects.

**Comment by jg314** [comment]
I'm also seeing this issue in WordPress 5.1.1, but it does look like there's a ticket open on Trac at https://core.trac.wordpress.org/ticket/45495 to deal with this bug.

**Comment by pwkip** [comment]
This might be related to another bug that I dicovered.

Generating a block like this:
```
<a href="#"><div>content</div></a>
``` 
will generate this HTML:
```
<a href="#"><div>content</div>
<p></a>
``` 
This is invalid HTML, so when I inspect DEV tools, chrome turns this into:
```
<a href="#">
  <div class="title">content</div>
</a>
<p><a href="#"></a></p>
```

The fix here is to use a span element:
```
<a href="#"><span>content</span></a>
```
This simply renders the correct HTML.

So I guess that the underlying problem has something to do with the fact that HTML does not allow block level elements (like DIV) inside inline elements (like SPAN, A). Although, there should be an exception for A-tags. https://stackoverflow.com/questions/1827965/is-putting-a-div-inside-an-anchor-ever-correct

**Comment by paaljoachim** [comment]
Is this issue still relevant?

**Comment by kathrynwp** [comment]
> I'm also seeing this issue in WordPress 5.1.1, but it does look like there's a ticket open on Trac at https://core.trac.wordpress.org/ticket/45495 to deal with this bug.

Looks like this issue was fixed in April 2019 in this changeset:

https://core.trac.wordpress.org/ticket/45495#comment:8

I'm going to go ahead and close this out, but if you are still experiencing the original issue, feel free to reopen with additional details, if needed.

**Comment by robertableson** [comment]
> > I'm also seeing this issue in WordPress 5.1.1, but it does look like there's a ticket open on Trac at https://core.trac.wordpress.org/ticket/45495 to deal with this bug.
> 
> Looks like this issue was fixed in April 2019 in this changeset:
> 
> https://core.trac.wordpress.org/ticket/45495#comment:8
> 
> I'm going to go ahead and close this out, but if you are still experiencing the original issue, feel free to reopen with additional details, if needed.

It still seems to happen when you output a div tag containing everything. A span does not. Perhaps it's still an issue?

**Comment by kathrynwp** [comment]
@robertableson Thanks for the comment. I haven't been able to replicate this with the test case provided by @mattheu above. 

> The link will be wrapped in a paragraph. 

Here's what I see, not spotting any extra `<p>` tags:

![Autop_Bug_Test_–_Self-hosted_Test](https://user-images.githubusercontent.com/7662449/180078603-1406a376-4fc6-43bc-8a9f-27950ec8414f.jpg)

WordPress 6.0.1
No plugins active OR just Gutenberg 13.6.0 or 13.7.0 active
Theme: Twenty Twenty-One 1.6

Could you provide me with your steps to replicate and I'll be glad to have another look. Thanks!

**Comment by Sajgoniarz** [comment]
Same here, in 6.2.0 with only Gutenberg 15.8.1 installed. I'm following tutorial and random p and br started to appearing in part-template that i wasn't editing.
Editor:
![Untitled](https://github.com/WordPress/gutenberg/assets/2995236/54dd7720-362a-42c1-875d-19b14e43e5c7)
header.html:
code responsible for that part:
`
<div class="wp-block-group container !mx-auto w-full" style="margin-top:0rem;margin-bottom:0rem;padding-top:1.25rem;padding-right:0rem;padding-bottom:1.25rem;padding-left:0rem">
    
    
    
    <div class="wp-block-udemy-plus-header-tools">
        
        <a class="signin-link open-modal" href="#signin-modal">
            <div class="signin-icon">
                <i class="bi bi-person-circle"></i>
            </div>
            <div class="signin-text">
                <small>Hello, Sign in</small>
                My Account 2
            </div>
        </a>
    </div>
    
</div>
`
This 2 to My Account i have added to check if file is loading from template after reloading site.

**Comment by mnaharnowicz-fp** [comment]
Same issue in WP 6.2 with only Gutenberg 15.8.1 installed.
Editor started to insert br and p into part template that i have not edited:
![Untitled](https://github.com/WordPress/gutenberg/assets/2995236/0fb1322a-6e00-4c57-a2a9-64b2abf3a698)
Source of that Custom HTML block:


    <div class="wp-block-udemy-plus-header-tools">
        
        <a class="signin-link open-modal" href="#signin-modal">
            <div class="signin-icon">
                <i class="bi bi-person-circle"></i>
            </div>
            <div class="signin-text">
                <small>Hello, Sign in</small>
                My Account 2
            </div>
        </a>
    </div>
    

I especially added 2 to verify if it loads data straight away from template file. not from db.

**Comment by kathrynwp** [comment]
@Sajgoniarz What you're experiencing sounds more related to this recent core change:

https://core.trac.wordpress.org/ticket/58366
