### ISSUE TITLE
Can't select all list items with Shift + up arrow without selecting previous block

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#12656]
**Describe the bug**

In WordPress 5.0, given a list of at least 4 items in a list block, if I try to select all of those items with CMD + Shift + Left arrow and then Shift + Up arrow, all of the items except for the first can be selected as expected. As soon as I type Shift + Up arrow for the last item, the selection skips and becomes a multi-block selection.

**To Reproduce**
1. Add a paragraph block
2. Add a list block
3. Type 4 or more list items
4. Place cursor at the end of the last list item
5. Type CMD + Shift + Left arrow (OSX) to select all text in the last item
6. Type Shift + Up arrow to add the above list item to the selection
7. Repeat

**Expected behavior**

I expect to be able to select each list item in the block so that I can copy/cut or otherwise manipulate the text.

**Screenshots**

![list-item-select](https://user-images.githubusercontent.com/286171/49611464-3a4ef180-f967-11e8-9b77-6cfbc48dc896.gif)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.12.6
 - Browser: Chrome
 - Version:  70.0.3538.110

**Comment by jeremyfelt** [comment]
I've updated the original ticket description—this appears to only happen with 4 or more list items. In a list of 3 items, I'm able to select as expected.

Also: Using CMD + Shift + Up arrow when the cursor is at the end of the last item **does** work as expected and selects all text at once.

**Comment by jeremyfelt** [comment]
@afercia It seems like it. I have the same issue with paragraphs. I can imagine it's the same area of code that's responsible. Should we close this one as a duplicate?

**Comment by afercia** [comment]
Probably yes, I'd leave that to the Gutenteam though. For now, I'd remove the "Needs testing" label 🙂

**Comment by ellatrix** [comment]
I think this is alleviated by #14448, but it's still an issue only if the last item is less long than the first item.

**Comment by aduth** [comment]
@ellatrix Can you clarify? I can no longer reproduce this at all, regardless of whether the first line is longer than the last.

![list](https://user-images.githubusercontent.com/1779930/54550332-2feabd80-4982-11e9-9d67-c9be6e8ea7b8.gif)

**Comment by ellatrix** [comment]
@aduth Sorry, I meant: if the last line is longer than the first. :)

**Comment by jeremyfelt** [comment]
I just tested this in WordPress 5.1 with the Gutenberg 5.4.0 plugin activated and I think it is resolved. I can select the full list of items using the keyboard when the last item is longer or shorter than the first.

I had a similar issue with paragraphs and that is working now as well.

**Comment by aduth** [comment]
I can still reproduce the issue under the specific condition that the last entry in the list is longer than those preceding it.

![list](https://user-images.githubusercontent.com/1779930/55738908-0dcee300-59f6-11e9-89a7-dd5191151b3d.gif)

**Comment by jeremyfelt** [comment]
This seems to be resolved in WP 5.3.2 with Gutenberg 7.1.0.

![list-selection](https://user-images.githubusercontent.com/286171/71137428-f1a65700-21bc-11ea-9641-3920a52622ca.gif)

**Comment by aduth** [comment]
I'm still able to reproduce with the same characteristics as in my previous comment https://github.com/WordPress/gutenberg/issues/12656#issuecomment-480893995 .

(macOS 10.15.1, Chrome 79.0.3945.88)
