### ISSUE TITLE
"Add block"("+") grayed out. Classic block just converts to classic-block-with-text-blocks. At a loss.

### ISSUE THREAD

**Issue by davemoz** [WordPress/gutenberg#12657]
I really like the idea of Gutenberg. I tried the plugin in early stages, but didn't dive in until I really had to with today's release of WP 5.0. I can't for the life of me figure out how to just do it, or better yet, why editing any of my existing or new posts/pages with Gutenberg seems to be working at all.

**Describe the bug**
To preface, I've disabled my custom theme, activating the new "Twenty-Nineteen" theme, and disabled all plugins. The "Add block"(+) button is greyed out on posts/pages with existing content, as well as when I create new posts.

**To Reproduce**
1. On posts with existing content, I click inside the "Classic block" to select, and then the "Block" tab in the right-hand column, but it says "No block selected".
2. I then click back inside the "Classic block" to select, find the "Block navigation" icon and click it, exposing a single tooltip'd option called "Classic Block".
3. I click on the "Classic Block" option which then reveals a "More"/three-dots icon.
4. I click the "More"/three-dots icon and choose "Convert to blocks"
5. When I click "Convert to blocks" my content inside the "Classic block" is wrapped in tags such as `<!-- wp:paragraph -->` and `<!-- wp:heading -->`, but no visual preview of these blocks shows up. It still appears that the blocks have been 'converted', but inside a classic block(?)

**Expected behavior**
I thought, and was excited, that with the wide release of WP 5.0 and Gutenberg into core, I would be able to easily convert my content to blocks and the visual preview inside the editor would allow be to hit the ground running editing with the new WP editor. This has not been the case at all.

**Screenshots**
![ezgif-1-642588005266](https://user-images.githubusercontent.com/5570825/49612126-8cd4e180-f958-11e8-91ff-31fe8cb5a5a3.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.2
 - Browser: Chrome
 - Version: 70.0.3538.110

**Additional context**
- I just updated to WP 5.0, so I'm using the latest version with core.

**Comment by designsimply** [comment]
Thanks for commenting and welcome!

It looks a little like you have the visual editor disabled. Can you go to Users > Your Profile and make sure the option for "Disable the visual editor when writing" is unchecked?

**Comment by davemoz** [comment]
Agh! Good to know! Thank you!

**Comment by chrisdempsey** [comment]
Same issue and option for _Disable the visual editor when writing_ was unchecked.

Resolved by checking _Disable the visual editor when writing_, updating the user profile then unchecking and updating again.

Presume the issue was caused by an incomplete profile as the user was manually created by updating the database manually.

**Comment by fragbait** [comment]
Interesting problem with the latest upgrade to 5.0.1
I hade a grey (+) for adding a block.
And just like chrisdempsey I had to add this option then take it away for things to work!

**Comment by ShadowGames-Dev** [comment]
I have tried this work around but I still have the same issue as described. All I have tried and the (+) button is still greyed out for me. I have checked "Disable the visual editor when writing", gone to the post editor, when back, unchecked it and nothing has changed at all... I cannot add blocks!!!

**Comment by bigboydrs** [comment]
Same issue with Guts. Tried the remedy of checking disable in profile settings, saving then changing back.... with no cure.

Can't get my site up and running.... I was counting on using a widget only available from the block manager because it works best.

**Comment by designsimply** [comment]
@ShadowGames-Dev and @bigboydrs, if the problem where the inserter, the (+) button, is grayed out persists even after making sure that the option at Users > Your Profile > Personal Options > "Disable the visual editor when writing" is unchecked, it's possible that your web host is not passing headers through properly. Others who have hosting using AWS CloudFront identified the following solutions for their case:

> There's two methods for resolution that we've landed on:
> 
> 1. Change the CloudFront behaviors to pass on headers. This is detailed in [this post by user g3luka][1].
> 2. Add code to functions.php that will enable the `user_can_richedit` flag [as detailed in my post][2]. Many thanks to https://webhost.io/, our host, for coming up with this one.
> 
> [1]:https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/page/2/#post-11014978
> [2]:https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/page/3/#post-11032983

Source: https://github.com/WordPress/gutenberg/issues/12927#issuecomment-450880090

Sites hosted using AWS CloudFront are affected and there could be other hosts with the same problem. If you're not sure how to check the configuration of your server to make sure it is passing headers through, please ask your web host for help as they should know the ins and outs of the setup you are using.

If you find that neither of the proposed solutions above is helpful, please open a new issue at https://wordpress.org/support/forum/wp-advanced/ or https://wordpress.stackexchange.com/ and include as much relevant information you can about what versions you are testing with, where your site is hosted, whether you have checked if headers are being passed through correctly, and whether you have already tried any changes to your web server configuration to address the problem and what didn't work.

**Comment by bigboydrs** [comment]
thank you designsimply. I have done all of the above and my web hosting guy just got back to me to confirm that they shouldn't have anything blocking headers from getting to the application. My host uses no load balancing.

I'll continue to try fixes and probably will post in the wp-advanced forum. Thanks again!

**Comment by adampatterson** [comment]
> Thanks for commenting and welcome!
> 
> It looks a little like you have the visual editor disabled. Can you go to Users > Your Profile and make sure the option for "Disable the visual editor when writing" is unchecked?

Thank you! It might be worth considering a UX feature or a CTA for this. When I started off I used the classic editor plugin by WordPress Contributors. After getting my syntax highlighting dialed in for my code snippets I was ready to finally make the move and Blamo, Stuck!

I'm not sure if the classic editor sets that option for me or if WordPress later added it but it was not abundantly clear that it was selected and nothing in Gutenberg hinted at that being the case.

**Comment by TheMovieStore** [comment]
> 
> 
> @ShadowGames-Dev and @bigboydrs, if the problem where the inserter, the (+) button, is grayed out persists even after making sure that the option at Users > Your Profile > Personal Options > "Disable the visual editor when writing" is unchecked, it's possible that your web host is not passing headers through properly. Others who have hosting using AWS CloudFront identified the following solutions for their case:
> 
> > There's two methods for resolution that we've landed on:
> > 
> > 1. Change the CloudFront behaviors to pass on headers. This is detailed in [this post by user g3luka](https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/page/2/#post-11014978).
> > 2. Add code to functions.php that will enable the `user_can_richedit` flag [as detailed in my post](https://wordpress.org/support/topic/block-editor-no-longer-working-only-shows-html/page/3/#post-11032983). Many thanks to https://webhost.io/, our host, for coming up with this one.
> 
> Source: [#12927 (comment)](https://github.com/WordPress/gutenberg/issues/12927#issuecomment-450880090)
> 
> Sites hosted using AWS CloudFront are affected and there could be other hosts with the same problem. If you're not sure how to check the configuration of your server to make sure it is passing headers through, please ask your web host for help as they should know the ins and outs of the setup you are using.
> 
> If you find that neither of the proposed solutions above is helpful, please open a new issue at https://wordpress.org/support/forum/wp-advanced/ or https://wordpress.stackexchange.com/ and include as much relevant information you can about what versions you are testing with, where your site is hosted, whether you have checked if headers are being passed through correctly, and whether you have already tried any changes to your web server configuration to address the problem and what didn't work.

Thanks , worked perfectly.

**Comment by fardxd** [comment]
> thank you designsimply. I have done all of the above and my web hosting guy just got back to me to confirm that they shouldn't have anything blocking headers from getting to the application. My host uses no load balancing.
> 
> I'll continue to try fixes and probably will post in the wp-advanced forum. Thanks again!
> 
> EDIT: I just realized I did not try adding the following code to functions.php:
> function richedit_wp_cloudfront () {
> add_filter('user_can_richedit','__return_true');
> }
> 
> add_action( 'init', 'richedit_wp_cloudfront', 9 );
> 
> After doing so, looks like my button is back again. Thank you for pointing me in the right direction.... This was stopping me from finishing my website build.

I had the same issue with Newspaper theme and TagDiv composer that's the only solution that works. Thanks a world!
