### ISSUE TITLE
Blocks Menu Opens Incorrectly on iOS Portrait

### ISSUE THREAD

**Issue by mrjarbenne** [WordPress/gutenberg#1280]
In iOS Safari, the + menu in the top bar opens correctly on iOS in Landscape mode

![img_6167](https://user-images.githubusercontent.com/480667/27309118-51d8be0e-5520-11e7-87eb-e05472976b1b.PNG)

but in portrait mode, the menu opens upwards, sitting above the viewport. You can see the bottom of the menu peeking out from the top in this image:

![img_6168](https://user-images.githubusercontent.com/480667/27309169-90e19a3a-5520-11e7-83c4-a8fe4c1aa168.PNG)

**Comment by mrjarbenne** [comment]
Previous screenshots were taken on iPhone 6S. I can confirm similar behaviour on iPad Air. Both instances are on WP Multisite 4.8, with the WP plugin repo version of the Gutenberg plugin: 0.1.0

![img_0339](https://user-images.githubusercontent.com/480667/27311012-0790419e-552c-11e7-89b5-e7fc162920c3.PNG)

**Comment by jasmussen** [comment]
Thanks for the report!

**Comment by aduth** [comment]
_Possibly_ resolved by Popover refactoring in #1204.

**Comment by mtias** [comment]
Closing as fixed by updated popover.

**Comment by mrjarbenne** [comment]
@mtias I believe this needs to be re-opened. 

The updated popover has fixed this issue in landscape, but portrait issues still persist. Using version 0.9 of the plugin, the popover will open upwards. If you switch the orientation while the popover is open, the popover stretches beyond the screen. 

![2017-08-20_20-16-40](https://user-images.githubusercontent.com/480667/29499729-c86536b0-85e5-11e7-8845-ae3eff3b3244.gif)

One item to note, which may be worthy of its own issue, but may also be impacting/causing the behaviour: 

When the Insert Block button is pressed, the popover opens and the search field is activated, which then triggers the keyboard, and throws everything upwards and out of view (this is also seen in the attached video). Perhaps this is making it difficult for the popover to detect visible real estate. 


Related: 
https://github.com/WordPress/gutenberg/issues/1961
https://github.com/WordPress/gutenberg/issues/2471

**Comment by karmatosed** [comment]
Closing as we now have a single place to include all issues for mobile inserter in #2691
