### ISSUE TITLE
Webpack does not watch for block.json changes

### ISSUE THREAD

**Issue by Jackie6** [WordPress/gutenberg#15135]
**Describe the bug**
Since #14770, the block.json is introduced. However, the webpack does not watch for the json files changes.

**To reproduce**
1. `npm run dev`
2. modify a block.json file
The webpack does not rebuild the package automatically.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Chrome
 - Version: Gutenberg5.5

**Comment by gziolo** [comment]
Great catch @Jackie6 👍I totally missed it.

**Comment by aduth** [comment]
**Implementation notes:**

- I would expect this should be working by default, since the implementation in #14770 leverages Webpack's built-in JSON import capability. As with any other dependency, Webpack should be monitoring these dependencies for changes and triggering a rebuild automatically.
- Alternatively, while JSON imports are available by default, perhaps it is an option to still specify a [`json-loader`](https://github.com/webpack-contrib/json-loader) configuration if it is more reliable with triggering a rebuild (perhaps it's even enough to include the `rules` entry to test `.json` files, but specify no `use` loader)
- If none of the above works, consider some third-party plugin which would provide the ability to hook into Webpack's internal watch mechanism to extend the files monitored to include `block.json` files ([example](https://github.com/pigcan/extra-watch-webpack-plugin)).

**Comment by gziolo** [comment]
I think the issue is only on Gutenberg side. We whitelist file patterns in packages to be watched for changes and we don't have `json` included there. I proposed a fix in #15455.

**Comment by talldan** [comment]
It seems like this issue wasn't completely solved. I've opened #16104. It is unusual that webpack doesn't pick up the changes.
