### ISSUE TITLE
Add toggle to hide Post/Page Title

### ISSUE THREAD

**Issue by melchoyce** [WordPress/gutenberg#16776]
I know `the_title()` isn't a block yet, but it would still be great to have a toggle to turn it off on posts/pages — maybe even the whole header, in case there's also post meta.

Quick idea:

![image](https://user-images.githubusercontent.com/2846578/61969182-dd608400-afa7-11e9-8f9e-8e7e93b4f444.png)

![image](https://user-images.githubusercontent.com/2846578/61969203-e6e9ec00-afa7-11e9-8d3e-44c464f4d16e.png)

**Comment by melchoyce** [comment]
(We probably can't hide the title because then how do you unhide it? But something to ponder.)

**Comment by senadir** [comment]
will hiding it in the editor also hide it in the front-end?
how about the posts/pages list? what will be the post named? or is this just a visual enhancement inside the editor but doesn't effect the general flow?

**Comment by melchoyce** [comment]
It would hide it on the front-end of the page/post itself, nowhere else. It would really only act as art direction in the individual post/page context. (Honestly, we might even just want to keep the appearance as-is in the editor and only hide it on the front end.)

**Comment by senadir** [comment]
this seems a bit hard to interpolate into the frontend, since many themes uses `the_title()` in other places not just the post title, so it means introducing a new function all together, or new arguments to it? since you can't detect where the function is being called. 

this seems like it would fit more as a theme feature and not directly from Gutenberg, at least till there is a much broader support for blocks in the frontend

**Comment by paaljoachim** [comment]
Here are two issues I made some time ago:
"Disable/hide blocks?"
https://github.com/WordPress/gutenberg/issues/4573
and
"Hide a block from being previewed on the front end."
https://github.com/WordPress/gutenberg/issues/13373

To me the process seems like this:
1. Make title into a block (one can not remove but could be moved in the layout).
2. Add a new location for post title (likely top bar above layout) when title block is removed. 
3. Default post title to top bar and have a post title block to add to the layout. 

Adding in a few more associated issues:
"Expanding the Editor outside of post_content"
https://github.com/WordPress/gutenberg/issues/16281
"Add Block: Title"
https://github.com/WordPress/gutenberg/issues/11553

**Comment by phpbits** [comment]
I have this feature available on my [EditorsKit](https://wordpress.org/plugins/block-options/) Plugin and here's the preview on how my integration works. I hope this could help. Thanks!

https://twitter.com/phpbits/status/1133710787686494211

**Comment by senadir** [comment]
@phpbits how do you handle this on the frontend?

**Comment by phpbits** [comment]
@senadir I'm using `the_title` filter and returning nothing whenever user use the Title Toggle. I'm also adding `editorskit-title-hidden` body class in order for them to add custom CSS to hide meta and other elements.

**Comment by senadir** [comment]
@phpbits how do you handle other uses for `the_title` when it's needed? say for example on the homepage loop?

**Comment by karmatosed** [comment]
I wonder if it's not a document setting?

**Comment by karmatosed** [comment]
I sketched a little mock what this could look like on the document itself.

<img width="1107" alt="titleshow" src="https://user-images.githubusercontent.com/253067/64067182-6b213600-cc1c-11e9-9585-ed90846c2012.png">

**Comment by nickcernis** [comment]
@karmatosed Should there be a hide title checkbox in the Document sidebar? I didn't see one or otherwise understand how the title would be hidden based on the mockup in https://github.com/WordPress/gutenberg/issues/16776#issuecomment-526849730.

**Comment by karmatosed** [comment]
Ah eep @nickcernis, I had uploaded wrong image and thank you for spotting that! All fixed now.

**Comment by simison** [comment]
Once the title is hidden in the content area, it could still show up in the document sidebar where folks could still modify it?

**Comment by mapk** [comment]
Ideally, a piece of content is a block. A block can be added or removed from any post/page. If there is information necessary for the post/page to exist, that information should reside in the Document settings sidebar. 

Because there are explorations around a Title block happening, I'd like to close this issue.

**Comment by dogooddesignco** [comment]
For now I'm using this code (with ACF). It just immediately removes the element from the DOM.

```
function dogooddesign_remove_post_title( $title, $id = null ) {
	if ( is_page() && is_singular() ) {
		$title = ( get_field( 'hide_title' ) ) ?
			'<script type="text/javascript">
                const postTitle = document.querySelector(".wp-block-post-title").remove();
                postTitle.parentNode.removeChild(postTitle);
                </script>'
			: $title;
	}

	return $title;
}
add_filter( 'the_title', 'dogooddesign_remove_post_title', 10, 2 );
```
