### ISSUE TITLE
Unable to centre buttons in Button Blocks

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#17059]
**Describe the bug**
It's no longer possible to centre a button within a Button Block

![Gutenberg-CentredButton](https://user-images.githubusercontent.com/2078245/63140783-65293380-c026-11e9-86a0-4e6e0fcad2c8.gif)

**To reproduce**
1. Insert Button Block
2. Use the Block Toolbar to centre the button
3. See issue

**Expected behavior**
Buttons should centre within the button block when it's selected from the alignment menu

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Firefox Quantum 68.0.1 (64-bit)
 - Version: 6.3.0
 - Theme: Have tested multiple themes. Above gif is using TwentySeventeen

**Comment by helgatheviking** [comment]
Was this fix published in the plugin? I am still experiencing this issue.

**Comment by maddisondesigns** [comment]
@helgatheviking Buttons work differently now, since I first raised this issue. Although the issue was resolved and merged into Core, the single _Button Block_, has now been replaced with a _Buttons Block_ that allows you to add one of more individual Buttons. The alignment option is now on the _Buttons Block_, rather than the individual Button Blocks, within that Buttons Block. And yep, the alignment option is working as intended (see image below with the menu item highlighted and the centered button just visible behind the dropdown menu)

<img width="1347" alt="screenshot_619" src="https://user-images.githubusercontent.com/2078245/116648516-95626280-a9c0-11eb-8cc9-ca46efbe8596.png">

**Comment by helgatheviking** [comment]
Thanks so much for the explanation! Navigating up to the buttons block was not initially obvious. I'm still having an issue with is not displaying, but I am pretty sure it's related to the fact that the buttons block is inside an Advanced column block from a plugin.

![A button is displayed with "justify items center" selected but the button is left-aligned](https://user-images.githubusercontent.com/507025/116708572-1142b780-a98d-11eb-9ce9-223d93474a47.png)

Inside a default column, I am seeing it center align as you've shown. Thanks!
