### ISSUE TITLE
Block Drag Icons don't display properly on Wide & Full Aligned blocks

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#18432]
**Describe the bug**
When a block is set to Wide (or Full) Alignment, the drag icons don't display properly. Only the Up arrow shows when in Wide Alignment, and when in Full, the down icon is cropped.

**Wide Width**
![Gutenberg_BlockDragIconsNotDisplayingProperly-Wide](https://user-images.githubusercontent.com/2078245/68593039-a24b7780-04e8-11ea-94db-68b1a71f2047.png)

**Full Width**
![Gutenberg_BlockDragIconsNotDisplayingProperly-Full](https://user-images.githubusercontent.com/2078245/68593044-a5466800-04e8-11ea-8318-e4920232de87.jpg)

**To reproduce**
1. Insert an image block
2. Set alignment to Wide (or Full) Alignment
3. View cropped drag icons

**Expected behavior**
Toolbar buttons should always display properly

**Desktop (please complete the following information):**
- OS: macOS Mojave 10.14.6
- Browser: Firefox 70.0.1
- Version: WP 5.3-RC4-46680
- Theme: TwentyNineteen

**Comment by derweili** [comment]
The error is caused when the screen with is between 1290px and 1080px.

The toolbar switches the a different alignment when the screen is wider than 1080px. `break-xlarge()`-mixin.
But this alignment only looks great when the screen is wider than 1280px so `break-wide()` breakpoint should be used.

https://github.com/WordPress/gutenberg/blob/923aa53e4828afd4928c35ad98bea3a60290ef82/packages/block-editor/src/components/block-list/style.scss#L542-L549

**Comment by mapk** [comment]
Looks like this has been resolved with the G2 work that got merged into the plugin recently. 

![drag](https://user-images.githubusercontent.com/617986/76885853-24540000-683d-11ea-8c2b-ce28fa17e757.gif)

**Comment by paaljoachim** [comment]
I still see some issues with this.
I am using Chrome.
Desktop Server. Local site.
Gutenberg version 7.7.1.

![Wide-Gutenberg](https://user-images.githubusercontent.com/5323259/76908381-d248c400-68a8-11ea-8128-31f1b3f48e18.gif)
