### ISSUE TITLE
Blocks Overlapping Eachother in Editor on Firefox

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#19476]
**Describe the bug**

When adding new blocks in Firefox 71 they appear overlapping existings blocks. This behaviour was not encountered in Safari when tested on MacOS Catalina.

The blocks don't push the next block out of the way and appear on top of eachother. I've replicated this using private blocks in a client project, and in frontenberg with the latest gutenberg 

Of note this doesn't happen with paragraph blocks and bullet lists, but does happen with columns, and sometimes it jumps to the correct layout

**To reproduce**
1. Add a block or blocks
2. Observe overlapping

**Expected behavior**
I expect behaviour to match behaviour in Safari as is normal for block insertion

**Screenshots**

https://youtu.be/6RQpVWZvFc0 

<img width="779" alt="Screenshot 2020-01-07 at 15 16 23" src="https://user-images.githubusercontent.com/58855/71906092-5cfe9b80-3161-11ea-8643-793f3c8f3a77.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Firefox
 - Version 71

**Additional context**
- Gutenberg 7.1, and stock WP 5.3

**Comment by iniOr** [comment]
Same issue here, what a mess.

**Comment by talldan** [comment]
Hi @tomjn @iniOr - apologies for the amount of time responding, there's a bit of a backlog of new issues that I'm trying to triage.

I couldn't reproduce this issue in Firefox 72 using Gutenberg 7.1, though I am still on Mojave (and not quite ready to upgrade yet).

It does feel like there'd be a huge number of reports of this issue. Anything unique about your environments that you can think of that might help with a reproduction? Browser add-ons?

**Comment by noisysocks** [comment]
I can’t reproduce this using Firefox 71 on Catalina. I followed the steps in the video and used https://frontenberg.tomjn.com/. There was a brief flash where it looked like the Columns block overlapped the List block, but then everything was fine.

**Comment by iniOr** [comment]
Just got the issue using the latest version of Firefox 72.0.2 on Linux Mint 19.3

![Screenshot from 2020-02-06 13-02-06](https://user-images.githubusercontent.com/43171930/73935478-859cc100-48d8-11ea-89a8-6a31155a28ea.png)

On the screenshot you can clearly see tag cloud block overlapping latest posts block.

Currently editing a page with this bug is really hard.

**Comment by iniOr** [comment]
I confirm that editing using Gutenberg on Firefox Linux Mint 19.3 is totally impossible right now.

**Comment by tomjn** [comment]
I still get this with latest Gutenberg and the latest Firefox:

<img width="874" alt="Screenshot 2020-03-09 at 12 49 39" src="https://user-images.githubusercontent.com/58855/76216218-16ccc380-6208-11ea-91e6-a2be255e7a6a.png">
<img width="849" alt="Screenshot 2020-03-09 at 13 14 36" src="https://user-images.githubusercontent.com/58855/76216226-19c7b400-6208-11ea-8f3d-c371f4dd59af.png">

The thing is initially it behaves as expected, but you have to interact and insert blocks to reproduce it. I don't believe the instructions to reproduce are reliable, there is something else going on that's needed and i haven't identified how. I just know that pretty much all attempts to use the block editor in Firefox eventually lead to this problem. Using images and custom blocks seem to reproduce this easier than using paragraphs. Paragraphs themselves only show the issue in the context of other non-paragraph blocks

**Comment by tomjn** [comment]
Of note, saving as a draft and re-loading the page shows the blocks as they're meant to be shown, and I can interact with them fine:

<img width="858" alt="Screenshot 2020-03-09 at 13 18 58" src="https://user-images.githubusercontent.com/58855/76216596-d02b9900-6208-11ea-8527-620cc025df75.png">

The problem reappears when I try to insert a block though. I used the inserter to add a heading between the two images, and it showed normally for a brief moment then dissapeared behind the block underneath. It shows normally when I type in the block but then reverts back to the overlapping behaviour:

https://www.youtube.com/watch?v=2jOGygMf6b4

**Comment by tomjn** [comment]
If the heading block is removed, a gap appears inbetween the 2 image blocks.

I believe a contributor to this issue is a transform CSS parameter being applied to the next block element:

<img width="922" alt="Screenshot 2020-03-09 at 13 27 47" src="https://user-images.githubusercontent.com/58855/76217182-d706db80-6209-11ea-925e-c9b804126f09.png">

**Comment by tomjn** [comment]
I also managed to reproduce this bug by using the mover controls. The block does not move when using the arrows, and subsequent clicks causes more overlapping, gaps, and confusion:

<img width="629" alt="Screenshot 2020-03-09 at 13 38 53" src="https://user-images.githubusercontent.com/58855/76218014-5ba62980-620b-11ea-8327-f91cd4c910c7.png">
<img width="604" alt="Screenshot 2020-03-09 at 13 38 59" src="https://user-images.githubusercontent.com/58855/76218018-5cd75680-620b-11ea-89a6-17e4eb3f5b93.png">

Here's another recording:

https://www.youtube.com/watch?v=FxxlG2d0yf0

I would also note that between this comment and the previous comment, I turned on reduce motion in system preferences, and closed/reopened Firefox. This was based on a hunch that this is related to block movement animations. I suspected this because I could find only one case of `translate3d` in a github search which referenced animation of blocks when moving them, and the checking of motion preferences in `packages/block-editor/src/components/block-list/moving-animation.js`

**Comment by tomjn** [comment]
It also seems that `window.matchMedia('(prefers-reduced-motion: reduce)')` returns `false` for me despite it being turned on at the OS level when using Firefox 73 :/

**Comment by tomjn** [comment]
The problem is eliminated when adding this CSS rule:

```css
.wp-block {
    transform: none !important;
}
```

**Comment by tomjn** [comment]
**I have found the source of the problem**

The `react-spring` library does not work when `privacy.resistFingerprinting` is set to true in `about:config`. Here is the relevant issue:

https://github.com/react-spring/react-spring/issues/664

`react-spring` is being used for block movement animations, hence why blocks are overlapping, and why animations never happen, they begin but cannot progress.

Turning off the privacy fingerprinting resist option resolve the issue

**Comment by youknowriad** [comment]
I spent some time trying to see if we can detect this option from our codebase, it doesn't seem like that's something we can do.

Not sure what can be done here. Tempted to just close the issue.

**Comment by tomjn** [comment]
I'd be happy if we could just force animations off regardless of reduce motion preferences. As great as having our cake and eating it would be, privacy > animations. Perhaps a checkbox in the options panel

**Comment by youknowriad** [comment]
@tomjn Agreed, this is tracked here https://github.com/WordPress/gutenberg/issues/16354

**Comment by paaljoachim** [comment]
Hey @tomjn Tom is this issue still valid?

**Comment by tomjn** [comment]
I don’t know, I switched back to chrome a long time ago and haven’t
retested this since

**Comment by FlyingDR** [comment]
@paaljoachim Issue is reproducible in WordPress 5.7. Firefox Developer Edition 89.0b9 on Windows 7. 

Steps to reproduce: Copy / paste several paragraphs of text (from lipsum.com in my case) and move them up / down using block moving controls. Result can be seen below:

![image](https://user-images.githubusercontent.com/822673/114929670-c5e0c300-9e3c-11eb-8639-99ca3f3ea81d.png)

Toggling of `privacy.resistFingerprinting` in `about:config` immediately recovers blocks appearance.

**Comment by paaljoachim** [comment]
Ugh...not good... Hopefully someone can pick it up and fix it.
Thanks for testing @FlyingDR Alexander!

**Comment by FlyingDR** [comment]
@paaljoachim There is interesting nuance that can only be seen in action so I've recorded small video, see below.

Please notice that as soon as `privacy.resistFingerprinting` setting is turned off - all stuck animations are **automatically** get resumed and played till the end. 

So probably the only thing that is required for the fix is to detect fingerprint resistance and either disable animations or find out what prevents them from completion. It is also possible to submit bugreport with request for comments from Mozilla engineers.

![wordpress-gutenberg](https://user-images.githubusercontent.com/822673/115000055-11ca5100-9eab-11eb-92ab-0de56dea72bd.gif)

**Comment by mcsf** [comment]
Seems to be [fixed in `react-spring` as of `v9rc3`](https://github.com/pmndrs/react-spring/issues/664#issuecomment-801947139), so it should be a matter of upgrading that dependency in Gutenberg, if someone is interested.

**Comment by paaljoachim** [comment]
Perhaps @gwwar Kerry is able to check it out later on.

**Comment by gwwar** [comment]
Yes, this is still an issue. Tested on OSX/FF88:

https://user-images.githubusercontent.com/1270189/115307648-60cbec80-a11e-11eb-852b-1f2328704229.mp4

**Comment by gwwar** [comment]
I'm at EOD but here's a quick draft PR of the dep update: https://github.com/WordPress/gutenberg/pull/30979

**Comment by gwwar** [comment]
🙈 So when `privacy.resistFingerprinting` is true FF will reduce the JavaScript time precision to 100 ms!

For context, animations need 16ms frames to achieve 60 frames per second. So a resolution of 100ms is going to do really funny things with any sort of animation, regardless of what framework we're using.

> In Firefox, you can also enable privacy.resistFingerprinting — this changes the precision to 100ms or the value of privacy.resistFingerprinting.reduceTimerPrecision.microseconds, whichever is larger.

https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#reduced_time_precision

We might need to test if we need to add the following headers to enable higher precision:

> Cross-Origin-Opener-Policy: same-origin
> Cross-Origin-Embedder-Policy: require-corp

**Comment by tomjn** [comment]
For those unaware, the last comment makes more sense after reading this:

https://github.com/WordPress/gutenberg/pull/30979#issuecomment-838987839

**Comment by gwwar** [comment]
This one should be fixed by https://github.com/WordPress/gutenberg/pull/30979
