### ISSUE TITLE
Navigation loader is over the return icon

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#19544]
I see the following for the loader, I would suggest it should be beside maybe?

![2020-01-09 21 57 24](https://user-images.githubusercontent.com/253067/72108293-2b393080-332b-11ea-8bcb-a8f8cb0b98ac.gif)

**Comment by draganescu** [comment]
Hi I can't see the enter icon, neither in Chrome nor in Firefox:

![link-enter](https://user-images.githubusercontent.com/107534/72206948-69099680-349c-11ea-8063-55a07cd4e3dc.gif)

what am I doing wrong?

**Comment by karmatosed** [comment]
Oh ace, this is fixed! I don't know how or why but going to celebrate as just tested and latest build works for me.

**Comment by draganescu** [comment]
Unfortunately it is not fixed, it is one of those "incoming" bugs, you maybe spotted while testing #19462. There is a comment by @aduth on this as well [here](https://github.com/WordPress/gutenberg/pull/19462#discussion_r365988980).

**Comment by aduth** [comment]
@draganescu Correct me if I'm wrong, but this "Submit" button is proposed to be added in #19462. But it doesn't exist in master. So while #19462 could introduce a bug here, there's no issue currently.

**Comment by draganescu** [comment]
You are right @aduth :)

**Comment by aduth** [comment]
Thanks for clarifying. I think it makes sense to close then, if it's not presently an issue in `master`.
