### ISSUE TITLE
post formats not working correctly

### ISSUE THREAD

**Issue by lqdjp** [WordPress/gutenberg#19805]
I set up the post formats with the code attached to be modified within the editor.
The post formats section shows up but unfortunately does not save any values.

![Untitled8](https://user-images.githubusercontent.com/5467523/72876963-19985580-3d3b-11ea-98a4-12ca374a1e0b.gif)

```
add_theme_support( 'post-formats', array( 'aside' ) );
add_post_type_support( 'page', 'post-formats' );
```

add_post_type_support() | Function:
https://developer.wordpress.org/reference/functions/add_post_type_support/

WordPress: 5.2.3
Theme: Twenty Twenty
May be relevant: #14725

**Comment by jorgefilipecosta** [comment]
Hi @lqdjp thank you for reporting this issue 👍  I'm not able to reproduce it on the last version of Gutenberg editor. I think the issue was solved meanwhile since many Gutenberg releases happened since WordPress: 5.2.3. The problem should be fixed on the last release of the Gutenberg plugin and on the next release of WordPress. If the problem is persisting in a test site with the Gutenberg plugin please leave a comment so we can look further into the issue.

**Comment by lqdjp** [comment]
Hi @jorgefilipecosta, thank you for your feedback!

Last version of Gutenberg editor plugin 7.3.0 did not solve the issue.
"Post" work fine, but not "Page".
To use the post format on a page:
```
add_theme_support( 'post-formats', array( 'aside' ) );
add_post_type_support( 'page', 'post-formats' );
```
Please test with this code.

**Comment by lqdjp** [comment]
> Hi @jorgefilipecosta, thank you for your feedback!
> 
> Last version of Gutenberg editor plugin 7.3.0 did not solve the issue.
> "Post" work fine, but not "Page".
> To use the post format on a page:
> 
> ```
> add_theme_support( 'post-formats', array( 'aside' ) );
> add_post_type_support( 'page', 'post-formats' );
> ```
> 
> Please test with this code.

Hi @jorgefilipecosta 
Please check additional information.

**Comment by jorgefilipecosta** [comment]
Thank you for referring that the issue just happens when the post format is used with a page.

I was able to reproduce the issue.


The root cause of the problem is the rest API. The page has a specific schema that does not include post format(https://developer.wordpress.org/rest-api/reference/pages/) and even though the block editor is sending the post format change is ignored on server side.

A similar issue is reported at https://github.com/WordPress/gutenberg/issues/14725.


I will create a trac issue so this is fixed on the core rest API side.

This gist was shared publicly was a way to allow saving Page order on a "post" I think you may use very similar logic as a temporary workaround to fix the issue https://gist.github.com/jesgs/e619bfbfe10ad998d8a61ac41cc958a7.

**Comment by lqdjp** [comment]
Thank you.
