### ISSUE TITLE
CSS overflow issue on editor post sidebar

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#20206]
*This bug was previously reported downstream in trac, https://core.trac.wordpress.org/ticket/49405. I've copied that report here.*

**Describe the bug**
This issue only appear on trunk version.

In the editor,the right sidebar content doesn't fit into its parent, and provokes a x-axis overflow (see attached screenshot).

----
Editor sidebar on trunk
![Screenshot_2020-02-11 Ajouter un nouvel article ‹ Justin Ahinon — WordPress(1)](https://user-images.githubusercontent.com/677833/74404424-6ddbb480-4e65-11ea-855d-efb8971db1f2.png)

----
Editor sidebar on 5.3.2
![Screenshot_2020-02-11 Ajouter un nouvel article ‹ Lurking — WordPress](https://user-images.githubusercontent.com/677833/74404445-7c29d080-4e65-11ea-9c94-50e0c68b70c7.png)

----
Adding some new details about the issue here:
I now notice the same behaviour on WordPress 5.4 beta 1.
It appears on Firefox Developer Edition 74.0beta.
The viewport is `width=device-width,initial-scale=1.0`.

**Comment by tellthemachines** [comment]
I can reproduce this issue on Firefox 73.0 (stable), whenever the sidebar is long enough to provoke a vertical scrollbar. Using latest development version of WP and latest Gutenberg.

**Comment by talldan** [comment]
Adding this tentatively as a WP5.4 must have. I haven't quite been able to reproduce it, but judging from the info reported it seems like it may have been introduced recently.

**Comment by jorgefilipecosta** [comment]
This issue seems hard to resolve, I tried lots of combinations of overflow-x, overflow-y, flex-grow, etc and ultimately I was not able to achieve to look we have in chrome.

In firefox, it seems the width of the element is computed without the scroll bar y when the scrollbar y is needed the width does not recompute and as the scroll bar y takes some space, a need for scrollbar x appears (instead I think the browser should have recomputed the width of the element as chrome does).
If we include something like "overflow-y: scroll" the problem does not happen but then we get the scroll bar always visible even if the scroll is not possible.
This seems like a browser bug to me.
@youknowriad, as it seems you worked around the layout structure in the past, do you have some insights (mainly to make sure I'm not missing a possible easy fix)?

**Comment by youknowriad** [comment]
We did some refactorings a few releases back to centralize all the canvas CSS in the EditorSkeleton component. It's probably related. Maybe @jasmussen already encountered this and have ideas about it.

**Comment by sybrew** [comment]
Reproducible with The SEO Framework plugin. You may need to slide the postbox to the sidebar via the Classic Editor before loading Gutenberg to see it.

![image](https://user-images.githubusercontent.com/7662236/74597141-118db600-505a-11ea-9b61-601c4bbe0dc4.png)

The culprit is that the `.poststuff` class obtains the `min-width` styles from the postbox located beneath the editor. This `min-width` style is then shared with the sidebar.

This should resolve the issue:
```css
.metabox-location-side .poststuff { min-width: unset }
``` 

During live-edits via the developer console, you may want to resize the window to invoke repainting.

**Comment by youknowriad** [comment]
They recently renamed `#poststuff` to `. poststuff` in trunk but there are still some CSS selectors using `#poststuff` in Gutenberg, maybe this is related and could be fixed by fixing these selectors. cc @afercia

**Comment by jasmussen** [comment]
This fixes it:

![Screenshot 2020-02-17 at 11 03 01](https://user-images.githubusercontent.com/1204802/74643498-185d1b80-5175-11ea-8d51-d6abf31ee062.png)

That is:

- `.block-editor-editor-skeleton__sidebar` gets overflow property removed
- `.block-editor-editor-skeleton__sidebar > div` receives `height: 100%;`
- `.edit-post-sidebar` receives `overflow: auto;`

But the > div is ugly and likely some necessary fragment. And the top-fixed tabs break (CC: @epiqueras I think we discussed this recently).

**Comment by epiqueras** [comment]
Yeah, I raised an issue about the tabs not being fixed consistently between mobile and desktop.

**Comment by afercia** [comment]
@youknowriad  I didn't follow the core change closely. I see the Trac ticket has been reopened because of some backwards compatibility concerns. Reference:
https://core.trac.wordpress.org/changeset/47222
https://core.trac.wordpress.org/ticket/46964

Best person to ask @audrasjb I guess 🙂

**Comment by jasmussen** [comment]
This was fixed by #20355.

**Comment by epiqueras** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by leadclown** [comment]
this bug still exist. can confirm i have a scrollbar on full hd (1920x1080) because of multiple elements which are not border-box.

please test multiple resolutions and devices before you mark bugs as completed!

**Comment by Louis7777** [comment]
Bug is still there.
