### ISSUE TITLE
Image size select defaults to 'Thumbnail' when an image is added but it's the full size image

### ISSUE THREAD

**Issue by ninetyninew** [WordPress/gutenberg#21681]
**Describe the bug**
When using the image block if you add an image then the image is added to the block at full size, which is fine but the settings panel's Image Size select field shows the image size as Thumbnail. Maybe if no size is selected this should be "Not set/custom" or similar.

**To reproduce**
1. Add an image block
2. Select an image
3. In the block settings view the Image Size select field
4. The selected option is Thumbnail

**Expected behavior**
As the image was added at full size don't show the select field value as Thumbnail, as no specific size is set maybe Custom or Not Set.

**Screenshots**

**Editor version (please complete the following information):**
- WordPress version: 5.4 / Gutenberg included in core

**Comment by shane-sigma** [comment]
Perhaps related to the bug I raised in #21650 but mine is specifically related to the gallery block?

**Comment by talldan** [comment]
This does sound similar to #21650 and similarly I'm not able to reproduce the problem. I left a comment there about providing some extra info that would be helpful: https://github.com/WordPress/gutenberg/issues/21650#issuecomment-616298301

If you're able to provide that info as well @ninetyninew, that would be great.

**Comment by ninetyninew** [comment]
@talldan

Image in code editor: `<!-- wp:image {"align":"center","id":116,"sizeSlug":"large","linkDestination":"custom","className":"image-fancy-right"} -->`

Setting shown in editor:

![image](https://user-images.githubusercontent.com/56840277/79728587-1420bc00-82e6-11ea-99b0-c184551b94df.png)

Plugins enabled on site are Font Awesome, Rank Math and Contact Form 7 Only, disabling these doesn't make any difference.

**Comment by mrwweb** [comment]
I just ran into this on two different sites in an hour. Both running WP 5.4 with no Gutenberg plugin.

**Comment by annezazu** [comment]
**Here's my setup:**

- WordPress 5.4
- Gutenberg 7.9.1
- PHP 7.3.16
- MacOS 10.14.6
- Chrome 81.0.4044.122 

**Large Image (790 x 1420 ) Test: Unable to replicate**

Video of my test: https://cloudup.com/cS2XhFfPFAi

I wasn't able to replicate the described issue  both with and without the Gutenberg plugin installed.

**✅Medium Image (300 x 77) Test: Able to replicate**

I was able to replicate the problem with images of this size!

<img width="1326" alt="Screen Shot 2020-04-22 at 5 05 04 PM" src="https://user-images.githubusercontent.com/26996883/80045157-6d8e1400-84bb-11ea-9c6a-6acb2d2d6e8d.png">

**Small Image Test (137 x 103): Unable to replicate**

As a final test, I tried using a very small image and found this defaulted to "Full Size" in the Image Size settings

<img width="1239" alt="Screen Shot 2020-04-22 at 5 00 41 PM" src="https://user-images.githubusercontent.com/26996883/80044994-01abab80-84bb-11ea-886c-7757cbba2ac8.png">

Based on the recent dialogue in #21650 it seems this might be related to file size in particular this "in between"/medium size. 

**Removing needs testing label and changing to bug.**

**Comment by supernovia** [comment]
Just noting I ran into this today. The size setting doesn't seem to do anything.

**Comment by jerrysarcastic** [comment]
Also noting that this issue popped up for me today, both with a site owner that cannot change image sizes (thumb, medium, large, etc.) with no change.

Tried this on a test site and had the same issue.  When I add an image, it is not possible to change the size of the image using those presets.  I recorded a screencast of the issue here:  https://d.pr/v/MdWbBs

As shown in my screencast, the Gutenberg markup is updated to reflect the correct size, but no change is seen in the editor view, nor on the live site when published.

**Comment by zdenys** [comment]
The issue is present on WordPress.com sites too: https://github.com/Automattic/wp-calypso/issues/43197

After some more testing, I can see the issue on a fresh install of https://jurassic.ninja/ + latest Gutenberg Plugin. Here's the screencast: https://d.pr/v/cOXxJF

On https://jurassic.ninja/ site without Gutenberg Plugin the Image Block has no issues: https://d.pr/v/jEUheH

**Comment by razvanpapadopol** [comment]
The broken image size preset selector was fixed in https://github.com/WordPress/gutenberg/pull/23342 and will be included in the [next release](https://github.com/WordPress/gutenberg/milestone/123?closed=1).

**Comment by paaljoachim** [comment]
The error is back.
https://github.com/WordPress/gutenberg/issues/27198
