### ISSUE TITLE
Calendar alignment issues

### ISSUE THREAD

**Issue by jancavan** [WordPress/gutenberg#22387]
I'm working on adding timezone when scheduling posts/pages and noticed a few things we can improve to make our calendar look better. Looking at the current calendar:

![Screen Shot 2020-05-15 at 10 47 51 AM](https://user-images.githubusercontent.com/4924246/82080504-885a3f80-9699-11ea-8e92-932f0b68104d.png)

- Days are misaligned with the corresponding days of the week
- Month/year is off-center
- Entire calendar is off-center within the card
- Days that fall outside of the current month are missing (which I think is pretty non-standard for calendars. This means I have to go over another month if I happen to be looking for a day that falls outside the month I'm on)
- Help link is misaligned
- The hour and date fields can contain more than 2 digits
- The year field can contain more than 4 digits (it's trying to be scalable, but might be a bit much?)

Here's a mockup addressing the items mentioned above.

I also:

- Expanded the month dropdown to get rid of the extra white space on its right
- Updated the left/right arrows:
-- to use the ones we are using in the Welcome modal
-- use darker colors. The arrows are really faint right now, they almost look like they're disabled
- Another idea, although I missed including it in the mockups, is to condense AM/PM into a dropdown

![Screen Shot 2020-05-15 at 10 49 59 AM](https://user-images.githubusercontent.com/4924246/82080650-d4a57f80-9699-11ea-9a2a-41efd56f764d.png)

Out of curiosity, do we need "Calendar Help"? Maybe "Navigating with a keyboard" might be helpful, but "Click to Select" is not necessary it seems?
![Screen Shot 2020-05-15 at 11 04 39 AM](https://user-images.githubusercontent.com/4924246/82081856-e12ad780-969b-11ea-92b5-706ef21c292a.png)

**Comment by spencerfinnell** [comment]
When using `DatePicker` (no time) there is an extra border at the top as well:

<img width="301" alt="Screen Shot 2020-05-15 at 2 53 36 PM" src="https://user-images.githubusercontent.com/491124/82086055-edbf2800-96bb-11ea-8cf8-23fbcfa610ea.png">

**Comment by mapk** [comment]
@jancavan, really good! Looking at the current and your proposed design solution is night and day. 

I've got a bit of feedback:

### 1. Change or Edit?
Do we use the word, "Change" for editing in other areas? I noticed in the wp-admin we tend to use the word "Edit." Are you opposed to that option?

### 2. AM PM
I'm not entirely sure if we need AM/PM as toggles or a dropdown. We can check with Accessibility Team on that.

### 3. Calendar help
This, I believe, is carried over from the Classic editor. Removing the "click to select" feels okay, but I'd leave the keyboards instructions.

### 4. Additional link missing
Keep in mind that there is also a recent change that brought a "reset" link into the DatePicker now.

![Screen Shot 2020-05-27 at 5 25 28 PM](https://user-images.githubusercontent.com/617986/83084897-2a393f00-a03f-11ea-9980-787e80a0c76a.png)

**Comment by jancavan** [comment]
> Do we use the word, "Change" for editing in other areas? I noticed in the wp-admin we tend to use the word "Edit." Are you opposed to that option?

I only saw one in account settings, although I am fine using "edit".

![Screen Shot 2020-05-28 at 1 38 54 PM](https://user-images.githubusercontent.com/4924246/83191263-958b1b80-a0e8-11ea-9617-5b5ed4661022.png)

**Comment by mapk** [comment]
Yea, let's go with "Edit." I know "Edit" appears all over the wp-admin. 

Oh BTW, the "reset" link is only visible if you've scheduled a post. Also, how does the "Edit" option you're presenting work with post scheduling? Have you thought through that flow?

**Comment by jancavan** [comment]
Yes, my thought is for it to just go to /settings/general. But I'd really like for uniformity in the timezones in the calendar and in settings. And for the timezones to be more helpful - ie: with offset and example city instead of just city names and ambiguous offsets.

**Comment by carolinan** [comment]
I believe the alignment issues have been solved. Is adding a reset link still relevant?
Current design:
![Date picker, with dates aligning under week days.](https://user-images.githubusercontent.com/7422055/177986916-6e4284f3-b4a7-447f-9e89-9a1feb680df4.png)

**Comment by skorasaurus** [comment]
think all of these issues are now resolved except for "Days that fall outside of the current month are missing (which I think is pretty non-standard for calendars. This means I have to go over another month if I happen to be looking for a day that falls outside the month I'm on)"

**Comment by Higher-order-functionssu** [comment]
https://lnkr.fun/caf7178



review this solution

**Comment by youknowriad** [comment]
Going to close this issue right now, the days outside current month are still not rendered but I don't think it's worth keeping this large issue open for that.
