### ISSUE TITLE
On nested Heading blocks, the "Change heading level" button loses padding when clicked

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#22683]
## The issue
When you click the heading level button in a Heading block toolbar, some of its left spacing disappears for some reason. But this only happens when the Heading block is nested in another block.
![image](https://user-images.githubusercontent.com/19592990/83040519-f6412800-a004-11ea-9d69-7a69facfd7c9.png)

(Ignore the mover placement in the screenshot; I took the picture on another branch, but I tested to make sure the bug was in `master`.)

I think this regressed due to changes in #20246. The cause appears to be due to a style rule being applied when this `<span>` is created upon clicking the button:
![image](https://user-images.githubusercontent.com/19592990/83053876-124dc500-a017-11ea-8509-b12df283b989.png)

## How to reproduce
1. Insert a Group block.
2. In that block, insert a Heading block.
3. Click the "Change heading level" button.
4. Notice how the padding on the left side of the button shrinks.

**Comment by ZebulanStanphill** [comment]
Something else I just noticed is that the "Change heading level" button label tooltip doesn't appear when the block is nested. Possibly related?

**Comment by ntsekouras** [comment]
> Notice how the padding on the left side of the button shrinks.

Hey @ZebulanStanphill, it seems that this has been fixed and the button takes [these styles](https://github.com/WordPress/gutenberg/blob/f89d3fe606e4d14ab93fb1e6b2c5c40e3f284d8a/packages/components/src/toolbar-group/style.scss#L111), introduced in this PR https://github.com/WordPress/gutenberg/pull/21252.

Can you please verify it's okay now?

**Comment by ZebulanStanphill** [comment]
@ntsekouras It was still broken when #21252 was merged (this issue wasn't even open yet back then), but something has changed since then and everything seems to be working now! :smile:
