### ISSUE TITLE
Revisions saved on blur even when there's no content

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#2385]
To reproduce:

- go in the Gutenberg "New Post" page
- click on the title then use the keyboard and tab a few times to tab in and then away from the Paragraph block 
- wait a few seconds
- a revision gets saved and "1 Revision" appears on the sidebar

The same happens when clicking inside the paragraph and then outside without entering any content.

I haven't added any content, but there's a Revision now. I realize content is sent to TinyMCE on blur and Gutenberg adds its own delimiter comments (plus an empty paragraph added by TinyMCE?) but I guess this is not the intended behavior. Inspecting the Revisions screens, here's what gets saved:

![screen shot 2017-08-12 at 11 22 43](https://user-images.githubusercontent.com/1682452/29239657-c3ca4944-7f53-11e7-82ae-11f047fb2403.png)

- repeat the above steps and wait for the first Revision to get saved
- add a new Paragraph and don't enter any content
- click outside of the Paragraph
- wait a few seconds
- a second Revision gets saved, the sidebar now displays "2 Revisions"

Inspecting the second revision content, here's what gets saved:

![screen shot 2017-08-12 at 11 38 12](https://user-images.githubusercontent.com/1682452/29239682-19cefc04-7f54-11e7-8877-692094c2b3da.png)

(Note: it's also wrong because the new content it the _second_ paragraph)

I'd consider to find a way to don't save revisions when there's no actual content entered, to avoid saving a huge amount of revisions in the DB.

**Comment by adamsilverstein** [comment]
This should be addressed by https://github.com/WordPress/gutenberg/pull/4156

**Comment by karmatosed** [comment]
Closing this as should have been addressed, we can always reopen if not.

**Comment by adamsilverstein** [comment]
Fine to close, however wanted to note that this is currently being tracked in https://github.com/WordPress/gutenberg/pull/4218 and is not yet resolved in master.
