### ISSUE TITLE
Default wp-env environment not functional: database connection errors

### ISSUE THREAD

**Issue by chrisRidgers** [WordPress/gutenberg#25717]
**Describe the bug**
`wp-env start` creates environment where wordress container cannot access mysql (mariadb) container.

**To reproduce**

Following documentation at: 

- https://developer.wordpress.org/block-editor/tutorials/devenv/
- https://developer.wordpress.org/block-editor/packages/packages-env/

```
➜  wp-create-block starter-block

Creating a new WordPress block in "starter-block" folder.

Creating a "block.json" file.

Creating a "package.json" file.

Installing packages. It might take a couple of minutes.

Formatting JavaScript files.

Compiling block.

Done: block "Starter Block" bootstrapped in the "starter-block" folder.

Inside that directory, you can run several commands:

  $ npm start
    Starts the build for development.

  $ npm run build
    Builds the code for production.

  $ npm run format:js
    Formats JavaScript files.

  $ npm run lint:css
    Lints CSS files.

  $ npm run lint:js
    Lints JavaScript files.

  $ npm run packages-update
    Updates WordPress packages to the latest version.

You can start by typing:

  $ cd starter-block
  $ npm start

Code is Poetry
➜  cd starter-block 
➜  wp-env start
✖ Error while running docker-compose command.
Starting 8a9345b875a8c995d91bc92a44fa1ff5_mysql_1 ... done
Starting 8a9345b875a8c995d91bc92a44fa1ff5_wordpress_1 ... done
Creating 8a9345b875a8c995d91bc92a44fa1ff5_cli_run     ... done
mysqlcheck: Got error: 1130: Host '172.21.0.5' is not allowed to connect to this MariaDB server when trying to connect
```

Which generates docker-compose.yml:

```
version: '3.7'
services:
  mysql:
    image: mariadb
    ports:
      - '3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql:/var/lib/mysql'
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - '${WP_ENV_PORT:-8888}:80'
    environment:
      WORDPRESS_DB_NAME: wordpress
    volumes: &ref_0
      - 'wordpress:/var/www/html'
      - >-
        /home/chris/Development/Personal/wordpress-demo/starter-block:/var/www/html/wp-content/plugins/starter-block
  tests-wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - '${WP_ENV_TESTS_PORT:-8889}:80'
    environment:
      WORDPRESS_DB_NAME: tests-wordpress
    volumes: &ref_1
      - 'tests-wordpress:/var/www/html'
      - >-
        /home/chris/Development/Personal/wordpress-demo/starter-block:/var/www/html/wp-content/plugins/starter-block
  cli:
    depends_on:
      - wordpress
    image: 'wordpress:cli'
    volumes: *ref_0
    user: '33:33'
  tests-cli:
    depends_on:
      - tests-wordpress
    image: 'wordpress:cli'
    volumes: *ref_1
    user: '33:33'
  composer:
    image: composer
    volumes:
      - '/home/chris/Development/Personal/wordpress-demo/starter-block:/app'
  phpunit:
    image: 'wordpressdevelop/phpunit:${LOCAL_PHP-latest}'
    depends_on:
      - tests-wordpress
    volumes:
      - 'tests-wordpress:/var/www/html'
      - >-
        /home/chris/Development/Personal/wordpress-demo/starter-block:/var/www/html/wp-content/plugins/starter-block
      - 'phpunit-uploads:/var/www/html/wp-content/uploads'
    environment:
      LOCAL_DIR: html
      WP_PHPUNIT__TESTS_CONFIG: /var/www/html/phpunit-wp-config.php
volumes:
  wordpress: {}
  tests-wordpress: {}
  mysql: {}
  phpunit-uploads: {}
```

And subsequently you receive generic database connection errors when visiting localhost:8888 and /wp/wp-admin

Logs:

```
wordpress_1        | WordPress not found in /var/www/html - copying now...
wordpress_1        | Complete! WordPress has been successfully copied to /var/www/html
wordpress_1        | [29-Sep-2020 19:30:50 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:50 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:50 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:30:53 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:53 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:53 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:30:56 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:56 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:56 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:30:59 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:59 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:30:59 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:02 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:02 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:02 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:05 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:05 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:05 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:08 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:08 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:08 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:11 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:11 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:11 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:14 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:14 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:14 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | [29-Sep-2020 19:31:17 UTC] PHP Warning:  Packets out of order. Expected 0 received 1. Packet size=69 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:17 UTC] PHP Warning:  mysqli::__construct(): Error while reading greeting packet. PID=186 in Standard input code on line 22
wordpress_1        | [29-Sep-2020 19:31:17 UTC] PHP Warning:  mysqli::__construct(): (HY000/2006): MySQL server has gone away in Standard input code on line 22
wordpress_1        | 
wordpress_1        | MySQL Connection Error: (2006) MySQL server has gone away
wordpress_1        | 
wordpress_1        | WARNING: unable to establish a database connection to 'mysql'
wordpress_1        |   continuing anyways (which might have unexpected results)
wordpress_1        | 
wordpress_1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.3. Set the 'ServerName' directive globally to suppress this message
wordpress_1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.3. Set the 'ServerName' directive globally to suppress this message
wordpress_1        | [Tue Sep 29 19:31:17.263850 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.10 configured -- resuming normal operations
wordpress_1        | [Tue Sep 29 19:31:17.263880 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
wordpress_1        | 172.22.0.1 - - [29/Sep/2020:19:40:19 +0000] "GET /wp-admin/ HTTP/1.1" 500 3583 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
```

**Expected behavior**
Running `wp-env start` from a plugin directory should result in a working dev environment with my plugin installed (if not active).

**Editor version (please complete the following information):**
- WordPress version: 5.5.1]
- Does the website has Gutenberg plugin installed, or is it using the block editor that comes by default? Not sure how to check this but presuming yes being a recent WordPress version
- If the Gutenberg plugin is installed, which version is it? Unknown

**Desktop (please complete the following information):**
 - OS: 
   LSB Version:	n/a
   Distributor ID:	ManjaroLinux
   Description:	        Manjaro Linux
   Release:	20.1
   Codename:	Mikah

**Additional context**
- Docker version 19.03.12-ce, build 48a66213fe
- Node Version: v12.18.4
- NPM Version: 6.14.6

Attempting to run other database containers and connect to the database results in a similar error:

```
➜  8a9345b875a8c995d91bc92a44fa1ff5 docker-compose run --rm mysql mysql -h mysql -uroot   
Creating 8a9345b875a8c995d91bc92a44fa1ff5_mysql_run ... done
ERROR 1130 (HY000): Host '172.22.0.5' is not allowed to connect to this MariaDB server
```

**Comment by chrisRidgers** [comment]
Possibly related?

https://github.com/docker-library/mysql/issues/275

**Comment by noahtallen** [comment]
@chrisRidgers Sorry you experienced this! I use wp-env on linux (Pop OS) and macOS quite frequently with no issues. (As does our automated CI.) So this is definitely not a common problem.

Unfortunately, I'm not sure how to troubleshot this given our environment differences. If you want to dig into the code, I would be happy to review any PRs if you come across a fix! The related source code is here: https://github.com/WordPress/gutenberg/blob/master/packages/env/lib/commands/start.js

**Comment by linkseed** [comment]
I have the same problem.

**Comment by chrisRidgers** [comment]
Ill try and throw some time at this this weekend

**Comment by dd32** [comment]
> mysqlcheck: Got error: 1130: Host '172.21.0.5' is not allowed to connect to this MariaDB server when trying to connect

Just noting that after debugging a similar issue on a windows platform, it appears that the initial setup of the mariadb container was probably aborted which left the mariadb volume with a database in it, but one that hadn't had the proper setup scripts run.
Those setup scripts are the ones which grant `root@%` access to the database, in this case I almost guarantee that the mariadb container is set to only allow `root@localhost` (localhost being the mariadb container, not the host) connections.

Subsequent runs of wp-env would re-use the same container (to keep any content) but would fail to connect as the setup tasks wouldn't be run on a subsequent loading of the container.

The only way to solve that is to destroy the mariadb container and re-create it to ensure that that the proper access rights are setup.

This might not be the case for all instances of this, but I suspect it's probably at least some of the instances of it, and aligns with docker-library/mysql#275

For those who run into this on a fresh "install", I suspect `npm run wp-env destroy && npm run wp-env start` would probably resolve it.

**Comment by vanduc1102** [comment]
I am having DB connection issue too
<img width="613" alt="Screen Shot 2021-03-17 at 00 48 13" src="https://user-images.githubusercontent.com/3014017/111356034-88144180-86ba-11eb-87ff-e9417e96bf35.png">

Seems the `username_here` is getting the default value https://github.com/docker-library/wordpress/blob/fb920c697693bad49582c3a0c8bf1fa0e7642d2b/wp-config-docker.php#L44 
I havent found a solution yet 😢

**Comment by timnolte** [comment]
I am now running into this issue as well, even on the latest version of `wp-env`. I ended up going back to an earlier version that still required me to manually update both environments `wp-config.php` files with the correct DB username/password.

**Comment by vanduc1102** [comment]
Hi , The issue is fixed in `4.0.0` , `wp-env start` is working on my machine :)

**Comment by psrpinto** [comment]
I'm using `wp-env` `4.1` and was still experiencing this issue. Finally, in my case, the root cause was the host machine running out of memory. This caused the mysql container to be killed, which caused a corrupt database, which in turn caused the `ERROR 1130 (HY000): Host '172.22.0.5' is not allowed to connect to this MariaDB server` error.

If you're seeing something like the following when running `docker-compose logs` (from inside the subdirectory under `~/.wp-env/`), you're likely having the same issue:

```
mysql_1 exited with code 137
```

Increasing the memory of the host machine solved the issue for me.

**Comment by cpiber** [comment]
I have the same problem.

Full docker-compose logs:

```
Attaching to c63a1e3e373419c5fd7cbd38e1d762ba_wordpress_1, c63a1e3e373419c5fd7cbd38e1d762ba_tests-wordpress_1, c63a1e3e373419c5fd7cbd38e1d762ba_mysql_1, c63a1e3e373419c5fd7cbd38e1d762ba_tests-mysql_1
mysql_1            | 2021-08-23 13:58:04+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
mysql_1            | 2021-08-23 13:58:04+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1            | 2021-08-23 13:58:04+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
mysql_1            | 2021-08-23 13:58:04 0 [Note] mysqld (server 10.6.4-MariaDB-1:10.6.4+maria~focal) starting as process 1 ...
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Number of pools: 1
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mysql_1            | 2021-08-23 13:58:04 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Using Linux native AIO
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: 128 rollback segments are active.
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: 10.6.4 started; log sequence number 42111; transaction id 14
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1            | 2021-08-23 13:58:04 0 [Note] Plugin 'FEEDBACK' is disabled.
mysql_1            | 2021-08-23 13:58:04 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
mysql_1            | 2021-08-23 13:58:04 0 [Note] Server socket created on IP: '0.0.0.0'.
mysql_1            | 2021-08-23 13:58:04 0 [Note] Server socket created on IP: '::'.
mysql_1            | 2021-08-23 13:58:04 0 [Warning] 'user' entry 'root@2ebb6d441ca4' ignored in --skip-name-resolve mode.
mysql_1            | 2021-08-23 13:58:04 0 [Warning] 'proxies_priv' entry '@% root@2ebb6d441ca4' ignored in --skip-name-resolve mode.
mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Buffer pool(s) load completed at 210823 13:58:04
mysql_1            | 2021-08-23 13:58:04 0 [Note] mysqld: ready for connections.
mysql_1            | Version: '10.6.4-MariaDB-1:10.6.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
mysql_1            | 2021-08-23 13:58:09 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:10 4 [Warning] Aborted connection 4 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:12 5 [Warning] Aborted connection 5 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:12 6 [Warning] Aborted connection 6 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:15 7 [Warning] Aborted connection 7 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:15 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:18 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:18 10 [Warning] Aborted connection 10 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:21 11 [Warning] Aborted connection 11 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:21 12 [Warning] Aborted connection 12 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:24 13 [Warning] Aborted connection 13 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:24 14 [Warning] Aborted connection 14 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:27 15 [Warning] Aborted connection 15 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:28 16 [Warning] Aborted connection 16 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:31 17 [Warning] Aborted connection 17 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:31 18 [Warning] Aborted connection 18 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:34 19 [Warning] Aborted connection 19 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:34 20 [Warning] Aborted connection 20 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:37 21 [Warning] Aborted connection 21 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:37 22 [Warning] Aborted connection 22 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:40 23 [Warning] Aborted connection 23 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:40 24 [Warning] Aborted connection 24 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:43 25 [Warning] Aborted connection 25 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:43 26 [Warning] Aborted connection 26 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:46 27 [Warning] Aborted connection 27 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:46 28 [Warning] Aborted connection 28 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:49 29 [Warning] Aborted connection 29 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:49 30 [Warning] Aborted connection 30 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:52 31 [Warning] Aborted connection 31 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:53 32 [Warning] Aborted connection 32 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:56 33 [Warning] Aborted connection 33 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:56 34 [Warning] Aborted connection 34 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:59 35 [Warning] Aborted connection 35 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:58:59 36 [Warning] Aborted connection 36 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:03 37 [Warning] Aborted connection 37 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:03 38 [Warning] Aborted connection 38 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:06 39 [Warning] Aborted connection 39 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:06 40 [Warning] Aborted connection 40 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:09 41 [Warning] Aborted connection 41 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:09 42 [Warning] Aborted connection 42 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:13 43 [Warning] Aborted connection 43 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:13 44 [Warning] Aborted connection 44 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:16 45 [Warning] Aborted connection 45 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:16 46 [Warning] Aborted connection 46 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:20 47 [Warning] Aborted connection 47 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:20 48 [Warning] Aborted connection 48 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:23 49 [Warning] Aborted connection 49 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:23 50 [Warning] Aborted connection 50 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:26 51 [Warning] Aborted connection 51 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:26 52 [Warning] Aborted connection 52 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:29 53 [Warning] Aborted connection 53 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:29 54 [Warning] Aborted connection 54 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:33 55 [Warning] Aborted connection 55 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:33 56 [Warning] Aborted connection 56 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:36 57 [Warning] Aborted connection 57 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:36 58 [Warning] Aborted connection 58 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:40 59 [Warning] Aborted connection 59 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:40 60 [Warning] Aborted connection 60 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:43 61 [Warning] Aborted connection 61 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:44 62 [Warning] Aborted connection 62 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:47 63 [Warning] Aborted connection 63 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
mysql_1            | 2021-08-23 13:59:47 64 [Warning] Aborted connection 64 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
tests-mysql_1      | 2021-08-23 13:58:03+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
tests-mysql_1      | 2021-08-23 13:58:03+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
tests-mysql_1      | 2021-08-23 13:58:03+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] mysqld (server 10.6.4-MariaDB-1:10.6.4+maria~focal) starting as process 1 ...
tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] InnoDB: Number of pools: 1
tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] InnoDB: Using Linux native AIO
tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: Completed initialization of buffer pool
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: 128 rollback segments are active.
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: Creating shared tablespace for temporary tables
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: 10.6.4 started; log sequence number 42221; transaction id 14
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] Plugin 'FEEDBACK' is disabled.
tests-mysql_1      | 2021-08-23 13:58:04 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] Server socket created on IP: '0.0.0.0'.
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] Server socket created on IP: '::'.
tests-mysql_1      | 2021-08-23 13:58:04 0 [Warning] 'proxies_priv' entry '@% root@bb8cdc10ab96' ignored in --skip-name-resolve mode.
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: Buffer pool(s) load completed at 210823 13:58:04
tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] mysqld: ready for connections.
tests-mysql_1      | Version: '10.6.4-MariaDB-1:10.6.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
tests-wordpress_1  | WordPress not found in /var/www/html - copying now...
tests-wordpress_1  | Complete! WordPress has been successfully copied to /var/www/html
tests-wordpress_1  | No 'wp-config.php' found in /var/www/html, but 'WORDPRESS_...' variables supplied; copying 'wp-config-docker.php' (WORDPRESS_DB_HOST WORDPRESS_DB_NAME WORDPRESS_DB_PASSWORD WORDPRESS_DB_USER)
tests-wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
tests-wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
tests-wordpress_1  | [Mon Aug 23 13:58:07.658145 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.48 (Debian) PHP/7.4.22 configured -- resuming normal operations
tests-wordpress_1  | [Mon Aug 23 13:58:07.658199 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
wordpress_1        | WordPress not found in /var/www/html - copying now...
wordpress_1        | Complete! WordPress has been successfully copied to /var/www/html
wordpress_1        | No 'wp-config.php' found in /var/www/html, but 'WORDPRESS_...' variables supplied; copying 'wp-config-docker.php' (WORDPRESS_DB_NAME WORDPRESS_DB_PASSWORD WORDPRESS_DB_USER)
wordpress_1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.5. Set the 'ServerName' directive globally to suppress this message
wordpress_1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.5. Set the 'ServerName' directive globally to suppress this message
wordpress_1        | [Mon Aug 23 13:58:07.572291 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.48 (Debian) PHP/7.4.22 configured -- resuming normal operations
wordpress_1        | [Mon Aug 23 13:58:07.572342 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

`2021-08-23 13:58:09 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)` specifically looks a bit odd, are the db and user values correct?

This works fine on my machine in version 3.0.0 and 4.0.0, but not 4.1.0

**Comment by lbgitjp** [comment]
I have the same problem.

**Comment by paladini** [comment]
I was having the same problem as @cpiber . I have it solved by upgrading `wp-env` from 4.2.0 to 4.9.0 . Hope that this info can help someone here in the future.

> ```
> Attaching to c63a1e3e373419c5fd7cbd38e1d762ba_wordpress_1, c63a1e3e373419c5fd7cbd38e1d762ba_tests-wordpress_1, c63a1e3e373419c5fd7cbd38e1d762ba_mysql_1, c63a1e3e373419c5fd7cbd38e1d762ba_tests-mysql_1
> mysql_1            | 2021-08-23 13:58:04+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
> mysql_1            | 2021-08-23 13:58:04+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
> mysql_1            | 2021-08-23 13:58:04+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
> mysql_1            | 2021-08-23 13:58:04 0 [Note] mysqld (server 10.6.4-MariaDB-1:10.6.4+maria~focal) starting as process 1 ...
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Number of pools: 1
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
> mysql_1            | 2021-08-23 13:58:04 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Using Linux native AIO
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Completed initialization of buffer pool
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: 128 rollback segments are active.
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Creating shared tablespace for temporary tables
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: 10.6.4 started; log sequence number 42111; transaction id 14
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
> mysql_1            | 2021-08-23 13:58:04 0 [Note] Plugin 'FEEDBACK' is disabled.
> mysql_1            | 2021-08-23 13:58:04 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
> mysql_1            | 2021-08-23 13:58:04 0 [Note] Server socket created on IP: '0.0.0.0'.
> mysql_1            | 2021-08-23 13:58:04 0 [Note] Server socket created on IP: '::'.
> mysql_1            | 2021-08-23 13:58:04 0 [Warning] 'user' entry 'root@2ebb6d441ca4' ignored in --skip-name-resolve mode.
> mysql_1            | 2021-08-23 13:58:04 0 [Warning] 'proxies_priv' entry '@% root@2ebb6d441ca4' ignored in --skip-name-resolve mode.
> mysql_1            | 2021-08-23 13:58:04 0 [Note] InnoDB: Buffer pool(s) load completed at 210823 13:58:04
> mysql_1            | 2021-08-23 13:58:04 0 [Note] mysqld: ready for connections.
> mysql_1            | Version: '10.6.4-MariaDB-1:10.6.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
> mysql_1            | 2021-08-23 13:58:09 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:10 4 [Warning] Aborted connection 4 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:12 5 [Warning] Aborted connection 5 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:12 6 [Warning] Aborted connection 6 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:15 7 [Warning] Aborted connection 7 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:15 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:18 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:18 10 [Warning] Aborted connection 10 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:21 11 [Warning] Aborted connection 11 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:21 12 [Warning] Aborted connection 12 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:24 13 [Warning] Aborted connection 13 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:24 14 [Warning] Aborted connection 14 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:27 15 [Warning] Aborted connection 15 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:28 16 [Warning] Aborted connection 16 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:31 17 [Warning] Aborted connection 17 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:31 18 [Warning] Aborted connection 18 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:34 19 [Warning] Aborted connection 19 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:34 20 [Warning] Aborted connection 20 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:37 21 [Warning] Aborted connection 21 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:37 22 [Warning] Aborted connection 22 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:40 23 [Warning] Aborted connection 23 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:40 24 [Warning] Aborted connection 24 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:43 25 [Warning] Aborted connection 25 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:43 26 [Warning] Aborted connection 26 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:46 27 [Warning] Aborted connection 27 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:46 28 [Warning] Aborted connection 28 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:49 29 [Warning] Aborted connection 29 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:49 30 [Warning] Aborted connection 30 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:52 31 [Warning] Aborted connection 31 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:53 32 [Warning] Aborted connection 32 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:56 33 [Warning] Aborted connection 33 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:56 34 [Warning] Aborted connection 34 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:59 35 [Warning] Aborted connection 35 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:58:59 36 [Warning] Aborted connection 36 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:03 37 [Warning] Aborted connection 37 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:03 38 [Warning] Aborted connection 38 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:06 39 [Warning] Aborted connection 39 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:06 40 [Warning] Aborted connection 40 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:09 41 [Warning] Aborted connection 41 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:09 42 [Warning] Aborted connection 42 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:13 43 [Warning] Aborted connection 43 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:13 44 [Warning] Aborted connection 44 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:16 45 [Warning] Aborted connection 45 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:16 46 [Warning] Aborted connection 46 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:20 47 [Warning] Aborted connection 47 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:20 48 [Warning] Aborted connection 48 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:23 49 [Warning] Aborted connection 49 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:23 50 [Warning] Aborted connection 50 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:26 51 [Warning] Aborted connection 51 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:26 52 [Warning] Aborted connection 52 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:29 53 [Warning] Aborted connection 53 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:29 54 [Warning] Aborted connection 54 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:33 55 [Warning] Aborted connection 55 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:33 56 [Warning] Aborted connection 56 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:36 57 [Warning] Aborted connection 57 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:36 58 [Warning] Aborted connection 58 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:40 59 [Warning] Aborted connection 59 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:40 60 [Warning] Aborted connection 60 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:43 61 [Warning] Aborted connection 61 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:44 62 [Warning] Aborted connection 62 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:47 63 [Warning] Aborted connection 63 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> mysql_1            | 2021-08-23 13:59:47 64 [Warning] Aborted connection 64 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.6' (This connection closed normally without authentication)
> tests-mysql_1      | 2021-08-23 13:58:03+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
> tests-mysql_1      | 2021-08-23 13:58:03+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
> tests-mysql_1      | 2021-08-23 13:58:03+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.6.4+maria~focal started.
> tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] mysqld (server 10.6.4-MariaDB-1:10.6.4+maria~focal) starting as process 1 ...
> tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
> tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] InnoDB: Number of pools: 1
> tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
> tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
> tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] InnoDB: Using Linux native AIO
> tests-mysql_1      | 2021-08-23 13:58:03 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: Completed initialization of buffer pool
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: 128 rollback segments are active.
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: Creating shared tablespace for temporary tables
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: 10.6.4 started; log sequence number 42221; transaction id 14
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] Plugin 'FEEDBACK' is disabled.
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] Server socket created on IP: '0.0.0.0'.
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] Server socket created on IP: '::'.
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Warning] 'proxies_priv' entry '@% root@bb8cdc10ab96' ignored in --skip-name-resolve mode.
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] InnoDB: Buffer pool(s) load completed at 210823 13:58:04
> tests-mysql_1      | 2021-08-23 13:58:04 0 [Note] mysqld: ready for connections.
> tests-mysql_1      | Version: '10.6.4-MariaDB-1:10.6.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
> tests-wordpress_1  | WordPress not found in /var/www/html - copying now...
> tests-wordpress_1  | Complete! WordPress has been successfully copied to /var/www/html
> tests-wordpress_1  | No 'wp-config.php' found in /var/www/html, but 'WORDPRESS_...' variables supplied; copying 'wp-config-docker.php' (WORDPRESS_DB_HOST WORDPRESS_DB_NAME WORDPRESS_DB_PASSWORD WORDPRESS_DB_USER)
> tests-wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
> tests-wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
> tests-wordpress_1  | [Mon Aug 23 13:58:07.658145 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.48 (Debian) PHP/7.4.22 configured -- resuming normal operations
> tests-wordpress_1  | [Mon Aug 23 13:58:07.658199 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
> wordpress_1        | WordPress not found in /var/www/html - copying now...
> wordpress_1        | Complete! WordPress has been successfully copied to /var/www/html
> wordpress_1        | No 'wp-config.php' found in /var/www/html, but 'WORDPRESS_...' variables supplied; copying 'wp-config-docker.php' (WORDPRESS_DB_NAME WORDPRESS_DB_PASSWORD WORDPRESS_DB_USER)
> wordpress_1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.5. Set the 'ServerName' directive globally to suppress this message
> wordpress_1        | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.5. Set the 'ServerName' directive globally to suppress this message
> wordpress_1        | [Mon Aug 23 13:58:07.572291 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.48 (Debian) PHP/7.4.22 configured -- resuming normal operations
> wordpress_1        | [Mon Aug 23 13:58:07.572342 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
> ```

**Comment by iazel** [comment]
Hello, #45217 has been merged, so give a try to the trunk branch and it should work now :)

Please be aware that you first have to run:

```shell
wp-env destroy
```

Or at least delete the MariaDB container.

Cheers!

**Comment by noisysocks** [comment]
It sounds like this is fixed so closing the issue.
