### ISSUE TITLE
& converted to &amp; in HTML and Shortcode blocks

### ISSUE THREAD

**Issue by coollorenzo** [WordPress/gutenberg#26362]
When using a url with parameters in HTML or Shortcode block I have the following problem:
After saving the post closing it and opening it up again the & in the url is changed to &amp; which results in the url paramenters not working.

For example when you have the following code as custom html block:
<img src="mydomain.nl/imagetool.php?param1=hello&param2=bye" />
After saving the post, closing it and opening it back up again the value of the custom html block will be:
<img src="mydomain.nl/imagetool.php?param1=hello&amp;param2=bye" />
This will cause param2 to not work.

I don't see any reason to convert & to &amp; in a HTML or Shortcode block so this seems like a bug.

Tested on multiple wordpress installations and server setups. Also the latest wordpress version 5.5.1

**Comment by coollorenzo** [comment]
Any updates on this?

**Comment by annezazu** [comment]
Hey @coollorenzo ! Thanks for reporting this. I've labeled this appropriately so the right people can take a look. Keep in mind this might take a while as there are other larger initiatives underway to move gutenberg forward. Thanks for your patience!

**Comment by tellthemachines** [comment]
I can't reproduce this with the HTML block in either WP 5.5.3 or the latest from this repo. It might have been fixed in the meantime; @coollorenzo could you update your WP version and check again?

**Comment by skorasaurus** [comment]
I'm able to still reproduce this in WordPress 5.6 with Gutenberg 9.6.2 installed. 

1. created new post; 
2. created new html block; 
3. pasted in the following in HTML block `<img src="mydomain.nl/imagetool.php?param1=hello&param2=bye" />`
4. published post
5. viewed the post from the frontend as the user; 
6. clicked on the edit link in my toolbar (e.g. /wp-admin/post.php?post=25421&action=edit
6. viewed post in editor.

**Comment by skorasaurus** [comment]
This was also reported in #19371 and the reporter there included some good details of how the `&` character sometimes did not escape.

**Comment by skorasaurus** [comment]
still applicable in gutenberg 14.7.0.

**Comment by CodeRevolutionPlugins** [comment]
Checked on this myself on latest WordPress 6.1.1 without any plugins active: the issue is still happening.

I added in the Gutenberg shortcode block the following:
`[wp_random_shortcode url="https://wordpress.org?a=x&b=y"]`

After page refresh, it was changed to:
`[wp_random_shortcode url="https://wordpress.org?a=x&amp;b=y"]`

Issue happens 100% of time, please check.

Thank you for your time investigating this.

Cheers!
