### ISSUE TITLE
Add type validation and/or theme.json schema

### ISSUE THREAD

**Issue by oandregal** [WordPress/gutenberg#26955]
See https://github.com/WordPress/gutenberg/pull/26803#discussion_r520939643

In https://github.com/WordPress/gutenberg/pull/26803 we evolved the theme.json schema validation mechanism by checking the structure of the input adhered to what we expected.

Adding type validation at the leaf level can bring more security but also opportunities to report invalid data input to theme authors.

**Comment by skorasaurus** [comment]
has this been resolved with https://github.com/WordPress/gutenberg/pull/32404 ?

**Comment by oandregal** [comment]
#32404 surfaces existing syntax errors to users. However, we still don't do type validation for the data that comes from `theme.json`.

**Comment by ajlende** [comment]
I made a JSON schema for theme.json that I'm [adding it to schemastore](https://github.com/SchemaStore/schemastore/pull/1837). Schemastore is where all the popular schemas, like tsconfig, are stored, but we also have the option to host the schema ourselves and still add it to the schemastore catalog if we want to move the schema source into gutenberg.

I mostly use the schema for autocompletion in VS Code, but it could also be used for the full validation here. WordPress has a PHP JSON schema validator that we use for the REST API that we could use. Our PHP validator supports draft-04, but not completely, so it might need some draft-04 features added to fully work.

**Comment by oandregal** [comment]
There's been a few years since this one was created and Alex implemented a schema that is working for people, so I'm closing this one.
