### ISSUE TITLE
Changing the Alpha Slider on Color Picker changes RGB values on some colors

### ISSUE THREAD

**Issue by noknokcody** [WordPress/gutenberg#28758]
## Description
When using some RGBA colors on the color picker, adjusting the alpha slider also adjusts RGB values slightly. For example, if you enter the RGBA values 246, 110, 4, 1 on an Alpha-Enabled color picker and then adjust the Alpha slider, the Green value of "110" get's changed to "109".  While the color change is minimal to the human eye, it makes it impossible to detect whether a change to the RGB values was intentional or not which is what I'm trying to detect.

## Step-by-step reproduction instructions
1. Go to https://wordpress.github.io/gutenberg/?path=/docs/components-colorpicker--alpha-enabled 
2. Change the RGBA values to 246, 110, 4, 1 (You may need to click outside the box to trigger an state update)
3. Adjust the Alpha slider to any value

## Expected behaviour
When adjusting the Alpha slider using this preset color configuration the none of the RGB values should change. Only the Alpha value

## Actual behaviour
The green value changes from 110 to 109

## Screenshots or screen recording (optional)
![GIF](https://i.imgur.com/2kU0y2D.gif)

## WordPress information
No Wordpress (Using github.io)

## Device information
- Device: Desktop Computer
- Operating system: Windows 10
- Browser: Chrome  88.0.4324.104 (Official Build) (64-bit)

**Comment by talldan** [comment]
Thanks for reporting this. It seems like it always changes by `1`, which makes me wonder if it's a rounding issue.

**Comment by noknokcody** [comment]
I thought something similar although I believe I found a few colors where the number was changing by more than 1 value. Not sure if that helps or not. Will report back if I find any more info :)

**Comment by mirka** [comment]
Looks like an upstream bug in `react-colorful` (https://github.com/omgovich/react-colorful/issues/163). I can reproduce it in this [sandbox](https://codesandbox.io/s/react-colorful-rgb-o9q0t?file=/src/App.js).

**Comment by t-hamano** [comment]
I am not sure if this is an appropriate fix, but I wrote [a PR](https://github.com/omgovich/react-colorful/pull/184) for the library.
Hopefully this PR works correctly 😅

**Comment by youknowriad** [comment]
I think this is fixed, at least I can't reproduce in storybook.

**Comment by t-hamano** [comment]
@youknowriad This issue is still reproducible.

- Access: https://wordpress.github.io/gutenberg/?path=/story/components-colorpicker--default&args=enableAlpha:!true
- Change the color format to RGB
- Change the RGBA values to `246`, `110`, `4`, `1`.
- Adjust the Alpha slider to any value
- The RGB values ​​change to `245`, `109`, `5`.

https://github.com/user-attachments/assets/8afc2119-b5f0-40cc-889c-9dc6837d1d30

**Comment by youknowriad** [comment]
I swear I did the same yesterday haha but I think I've used the input to change the alpha value and not the slider.

**Comment by mirka** [comment]
Upstream issue was [fixed](https://github.com/WordPress/gutenberg/issues/28758#issuecomment-985027699). We may be able to fix when the next version is released.
