### ISSUE TITLE
Gutenberg Plugin 10.2.1 - Editor defaulting to system serif font, not WordPress's default

### ISSUE THREAD

**Issue by cngodles** [WordPress/gutenberg#30046]
## Description
Block Editor font is defaulting to "serif" font. There appear to be inline styles placed before the editor that adds the following CSS class declaration. This is affecting at the very least the Paragraph and Header blocks. The post title also reverts to serif.

```
.editor-styles-wrapper {
font-family: serif;
font-size: medium;
line-height: normal;
color: initial;
}
```

Example editor text:

![image](https://user-images.githubusercontent.com/5685764/111838122-427c9200-88cf-11eb-924d-2e811351f771.png)

If I disable the Gutenberg Plugin:

![image](https://user-images.githubusercontent.com/5685764/111838207-5e803380-88cf-11eb-877b-323c9bd1fb19.png)

This was not happening prior to updating the Gutenberg Plugin. Once I deactivated the plugin, the fonts are now showing correcty.

## Step-by-step reproduction instructions
1. Update Gutenberg Plugin 10 10.2.1
2. Open the WordPress Gutenberg editor for any page or post.

## Expected behaviour
Fonts to appear using default fonts. `-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif`

## Actual behaviour
Fonts are appearing using default system serif font.

## Code snippet (optional)

Inline code is appearing here in F12 tools:

![image](https://user-images.githubusercontent.com/5685764/111838768-2decc980-88d0-11eb-99bd-daad87dac2bd.png)

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.2.1
- Are all plugins except Gutenberg deactivated? No.
- Are you using a default theme (e.g. Twenty Twenty-One)? No.

## Device information
- Device: Desktop
- Operating system: Windows 10
- Browser: Chrome Latest. Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by skorasaurus** [comment]
I was about to report this as well; confirmed on 10.2.1.

**Comment by cngodles** [comment]
For reference, the contents of the style container is:

```.editor-styles-wrapper {
padding: 10px;
}

.editor-styles-wrapper .block-editor-block-list__layout.is-root-container>.wp-block[data-align=full] {
margin-left: -10px;
margin-right: -10px;
}

.editor-styles-wrapper .wp-align-wrapper {
max-width: 840px;
}

.editor-styles-wrapper .wp-align-wrapper.wp-align-full,
.editor-styles-wrapper .wp-align-wrapper>.wp-block {
max-width: none;
}

.editor-styles-wrapper .wp-align-wrapper.wp-align-wide {
max-width: 840px;
}

.editor-styles-wrapper a {
transition: none;
}

.editor-styles-wrapper code,
.editor-styles-wrapper kbd {
padding: 0;
margin: 0;
background: inherit;
font-size: inherit;
font-family: monospace;
}

.editor-styles-wrapper {
font-family: serif;
font-size: medium;
line-height: normal;
color: initial;
}

.editor-styles-wrapper p {
font-size: revert;
line-height: revert;
}

.editor-styles-wrapper ol,
.editor-styles-wrapper p,
.editor-styles-wrapper ul {
margin: revert;
}

.editor-styles-wrapper ol,
.editor-styles-wrapper ul {
padding: revert;
}

.editor-styles-wrapper ol li,
.editor-styles-wrapper ol ol,
.editor-styles-wrapper ol ul,
.editor-styles-wrapper ul li,
.editor-styles-wrapper ul ol,
.editor-styles-wrapper ul ul {
margin: revert;
}

.editor-styles-wrapper ol,
.editor-styles-wrapper ol ul,
.editor-styles-wrapper ul,
.editor-styles-wrapper ul ul {
list-style-type: revert;
}

.editor-styles-wrapper h1,
.editor-styles-wrapper h2,
.editor-styles-wrapper h3,
.editor-styles-wrapper h4,
.editor-styles-wrapper h5,
.editor-styles-wrapper h6 {
font-size: revert;
margin: revert;
color: revert;
line-height: revert;
font-weight: revert;
}

**Comment by skorasaurus** [comment]
@cngodles 

What theme are you using? Is your theme enqueuing any fonts in the editor? 

I am not able to reproduce this with my combination of firefox and ubuntu. 


possibly related to 
https://github.com/WordPress/gutenberg/pull/29590

**Comment by tomjn** [comment]
A sidenote, would it not make more sense for the block editor to set the system font stack using an ultra low specificity styling rule so that the worst case scenario still looks okay?

**Comment by cngodles** [comment]
@skorasaurus Theme is Dollah.

I did download the theme and searched the files for any reference to portions of the CSS, and I didn't see any in there. So it did not appear to be adding this, but I can't be sure.

It was curious that disabling the Gutenberg Plugin fixes it.

**Comment by ashleyleia** [comment]
I'm having the same issue, with serif font showing with Gutenberg 10.2.1 active, and sans serif with it deactivated.  I'm using Wordpress.com and Dara theme.

The screenshot below comes from Google Chrome with Gutenberg activated.  The editor text is serif, and it's getting that from div.editor-styles-wrapper.

<img width="879" alt="Screen Shot 2021-03-21 at 4 57 11 PM" src="https://user-images.githubusercontent.com/77593027/111925678-11cf6080-8a67-11eb-9e7f-e1a37024973b.png">

The screenshot below is with Gutenberg deactivated.  The editor text is sans serif system font, from div.editor-styles-wrapper.

<img width="1009" alt="Screen Shot 2021-03-21 at 4 58 59 PM" src="https://user-images.githubusercontent.com/77593027/111925740-565afc00-8a67-11eb-8e4b-1a42f7134747.png">

Some fellow bloggers have commented that the font size in the editor is really small since the last update.  The 16px is okay when it's displaying as sans serif, but in serif it's tough to read.

**Comment by tomjn** [comment]
I can confirm the current release of the Gutenberg plugin has this problem, with the same rules overriding the system font and replacing it with `serif`:

<img width="507" alt="Screenshot 2021-03-29 at 18 43 55" src="https://user-images.githubusercontent.com/58855/112877662-f1cf1b00-90be-11eb-9a9a-00da7604f72f.png">

Which I believe comes from here:

https://github.com/WordPress/gutenberg/blob/883d7d42f62171e79c860a96ef5b9081d4789ea4/packages/block-library/src/reset.scss#L15

This is included in the editor initialisation routine, on a theme that does not register editor styles. The rules specificity is too high and overrides the correct rule

**Comment by tomjn** [comment]
Given that the `reset.scss` file doesn't exist on the latest version of the main branch, it's possible this has been fixed already/accidentally, it will need retesting. I'd also advise that testing of the plugin be done on a barebones minimal theme such as underscores which lacks an editor stylesheet

**Comment by amir2mi** [comment]
I have had this problem both in Linux and Windows 10, also when I disable the Gutenberg plugin it seems to be solved.

**Comment by cngodles** [comment]
I gave this another try with version `10.4.1`, I'm still seeing the issue, but it's not like before. I originally reported from version `10.2.1`

Here is a comparison of the styling of the paragraph block for the enabled plugin (top) vs the disabled plugin (bottom)

I think this is not as bad as it was when first reported, however, `color` and `line-height` are still affected.

![image](https://user-images.githubusercontent.com/5685764/116095647-9ae54300-a676-11eb-9d7f-c1b1c1f669f7.png)

**Comment by tomjn** [comment]
@cngodles the issue reports that the system font stack in your last response was _not_ being used, and that `serif` was being used instead. Does your response not indicate that the problem has been fixed?

Any other changes would be a new and separate issue

**Comment by cngodles** [comment]
We shall continue this over at #31211.

@amir2mi I believe updating to at least the latest version of the plugin 10.4.1 will fix the font issue. Working on getting the rest solved.
