### ISSUE TITLE
Block editor crashes when using thousands of reusable blocks

### ISSUE THREAD

**Issue by mishterk** [WordPress/gutenberg#31442]
## Description
When working with large numbers of reusable blocks (thousands), the editor crashes the browser when attempting to access the **Reusable** tab in the block inserter. I know the number of blocks might seem excessive but we have a large sized site with a lot of content that needs to be distributed across products and post types so we'll need to be able to use many thousands of reusable blocks to keep management of the content sane. 😅 

## Step-by-step reproduction instructions
1. Create a reusable block
2. Create 3000 clones of it using the function [in this Gist](https://gist.github.com/mishterk/9d91431afc66e8338fcd976bce80e135). May need to do this in batches of 1000.
3. Create a new page/post and open the inserter using the **add block** "+" icon in the top left corner.
4. Wait while the **Reusable** tab appears (this takes a while).
5. Click on the **Reusable** tab — this is where the browser tab crashes. 

## Expected behaviour
I would have expected the reusable block system not to attempt to load all reusable blocks on page load but instead, use an AJAX-based system that shows paginated result sets. 

## Actual behaviour
The browser appears to attempt to load all reusable blocks on page load, 100 at a time until it eventually hits a RangeError (see screenshot below).

## Screenshots or screen recording (optional)
What I'm seeing in Chrome dev tools:
![CleanShot 2021-05-04 at 08 58 30@2x](https://user-images.githubusercontent.com/2113020/116944731-677b6780-acb9-11eb-9d53-de4163afcf8b.jpg)

The browsers eventual response:
![CleanShot 2021-05-04 at 09 02 56@2x](https://user-images.githubusercontent.com/2113020/116944792-811caf00-acb9-11eb-988e-810776e3c106.jpg)

## WordPress information
- WordPress version: 5.7.1
- Gutenberg version: Plugin not installed — using core version.
- Are all plugins except Gutenberg deactivated? Yes.
- Are you using a default theme (e.g. Twenty Twenty-One)? Was using a bare-bones/empty theme but problem also occurs on Twenty Twenty-One.

## Device information
- Device: MacBook Pro (2017, 3.1 GHz Quad-Core Intel Core i7, 16 GB 2133 MHz LPDDR3)
- Operating system: macOSS Catalina version 10.15.7
- Browser: Crome Version 90.0.4430.93 (Official Build) (x86_64)

**Comment by getsource** [comment]
Hi @mishterk!

Thanks for the report. This was discussed in [a triage meeting today](https://wordpress.slack.com/archives/C02QB2JS7/p1627968584058600).

Folks present agreed that it was a bug, and @peterwilsoncc was able to reproduce, so marking it as such.

@Mamaduka mentioned that #33749 is related and might have changed the rendering behavior.

**Comment by talldan** [comment]
For anyone using `wp-env`, this is the wp cli command for creating lots of reusable blocks, just change the count to whatever you want:
```
npx wp-env run cli "wp post generate --count=5000 --post_type=wp_block --post_title='Ready'"
```

On the latest version I tested using about 6,000 reusable blocks, and it did work, but it was slow and wasn't very usable. Ideally the results would be paginated. 

That's on well-specced machine, so I'd hate to see what it's like on a phone or tablet.

**Comment by talldan** [comment]
Looks like this was fixed or improved by https://github.com/WordPress/gutenberg/pull/35763.

I'll close the issue, but it can be reopened if there are still problems.

**Comment by sathyapulse** [comment]
@talldan Issue #35763 improved the performance of the block inserter popup and reduced the time to open the block inserter popup. I believe the underlying issue still exists, and it crashes only on 5.7.x. Installing the GB plugin version (10.7.4) shipped with 5.8 resolves the problem.

With 5.8, it didn't crash the browser, but the reusable blocks tab is very slow and isn't usable. As you mentioned in the previous comment, the paginated results or equivalent would be better.

**Comment by talldan** [comment]
@sathyapulse Just to clarify, are you saying that the issue is resolved, but could still use some improvement? Are there still performance issues or is it more of a UX problem?

When testing, it's important to try with the latest version of WordPress and the Gutenberg plugin. This performance patch won't be backported to old WordPress or Gutenberg versions. The plugin also only supports the most recent two versions of WordPress, and support for 5.7 will soon be dropped with the release of WordPress 5.9.

Gutenberg 10.7.4 predates the performance fix, so I'd still expect issues. Gutenberg 11.9 and onwards would be the version to test with.
