### ISSUE TITLE
Post Content Block creates confusing UX when deleting content within the block

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31798]
## Description

When trying to add the post content block to a new blank template that's been customized in template editing mode, the block sometimes gets added multiple times and, upon removal, gets removed in all locations including the original post. cc @youknowriad 

## Step-by-step reproduction instructions

1. Have a site set up with template editing mode
2. Add a new blank template
3. Remove and re-add the post content block with
4. Notice it sometimes gets added in multiple times.
5. Try removing one of the instances only to find it removes the post content everywhere. 

## Expected behaviour

Expect the block not to be duplicated or mass removed. 

## Actual behaviour

Block is duplicated + mass removed. 

## Screenshots or screen recording (optional)

https://user-images.githubusercontent.com/26996883/118151837-4f020000-b3d1-11eb-9097-782c7c9b7bcd.mov

## WordPress information
- WordPress version: 5.7
- Gutenberg version: 10.6
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? TT1 Blocks

## Device information
- Device: Desktop
- Operating system: MacOS
- Browser: Chrome

**Comment by annezazu** [comment]
Just replicated this with a brand new test site using Gutenberg 10.6.1 and WordPress 5.7.2:

https://user-images.githubusercontent.com/26996883/118712732-5c0e5d00-b7de-11eb-976f-639a1ff02704.mov

At first, I wasn't able to replicate until I started just trying to add, edit, remove, etc a few times.

**Comment by bobbingwide** [comment]
See also https://github.com/WordPress/gutenberg/issues/26923

**Comment by youknowriad** [comment]
I think this is now fixed. Anyone can do some tests and confirm?

**Comment by annezazu** [comment]
On my list for today and will loop back to confirm.

**Comment by annezazu** [comment]
I am still seeing some strange behavior. Here's as specific as I can get right now with the first item listed the bigger problem to solve:

1. Because the Post Content Block acts as a container of sorts in the Template Editor, it's very easy to accidentally delete the content of the post itself rather than just the block. Here's a video showing this happening where I think I'm deleting the post content block but am actually editing the post content directly and removing the paragraph block. This is a super confusing UX:

https://user-images.githubusercontent.com/26996883/119027920-1bd8e700-b964-11eb-8026-ebc120115e27.mov

2. I think the duplication is due to there being a Post Content Block "container" where, if the content block is empty, the "Type / to choose block" prompt comes up making it seem as if it's just a paragraph block rather than a paragraph block within the Post Content block. This causes the "Block cannot be rendered inside itself" error to show up, causes the duplication effect, and makes it tricky to fully remove the post content block:

https://user-images.githubusercontent.com/26996883/119028586-dd8ff780-b964-11eb-8db8-5252d01deb7d.mov

Note that the "Block cannot be rendered inside itself." error isn't visible when placed inside the Cover Block for some reason.

**Comment by annezazu** [comment]
Updated my comment above and the issue description to be more specific as the issue is more about how there is a parent/child dynamic between the Post Content Block and the actual contents of the post content (paragraph, image, etc).

**Comment by youknowriad** [comment]
@WordPress/gutenberg-core This one is worth-investigating if anyone has time.

**Comment by youknowriad** [comment]
> Because the Post Content Block acts as a container of sorts in the Template Editor, it's very easy to accidentally delete the content of the post itself rather than just the block. Here's a video showing this happening where I think I'm deleting the post content block but am actually editing the post content directly and removing the paragraph block. This is a super confusing UX:

This is not an issue for me, you can edit the post content in template mode, that's a fact but I think @jameskoster and others are exploring adding friction to these blocks separately.

**Comment by youknowriad** [comment]
The second item is also not a bug. So I'm going to update the issue to reflect its state.

**Comment by annezazu** [comment]
Closing this out as I can no long replicate what's described here. I do still find it confusing that you can edit the post content directly, including deleting items, while in template editing mode but that's not a true bug :)
