### ISSUE TITLE
Feedback on Template Part Width Settings in Template Editor

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#31862]
## What problem does this address?

Currently, the dynamic between a template part's width and the width of the blocks within creates a bit of a confusing workflow as described below from feedback on the [sixth call for testing for the FSE Outreach Program](https://make.wordpress.org/test/2021/05/12/fse-program-testing-call-6-stick-the-landing-pages/):

>One part that was somewhat unclear is the alignment options aren’t reflected in the editor vs how they display on the site. Specifically for the custom footer section, when selecting full width I see it is applied when I view on the front-end, but in editor it was not full-width. I figured out that I needed to set the footer to full width as well as the columns within to full width to see it reflected in editor.

Here's a video that better shows this problem in action where, in the editor, setting the columns of a block within the template part causes the block to be full width on the front end but not in the editor until you also set the template part block to full width:

https://user-images.githubusercontent.com/26996883/118373195-c9b65100-b572-11eb-82c5-f203fb2b51fc.mov

## What is your proposed solution?

It seems like there needs to be some clarification or hierarchy around template part width and any nested blocks. This somewhat relates to overall feedback around widths and alignments in this issue https://github.com/WordPress/gutenberg/issues/30724

cc @carolinan can you confirm this doesn't happen to be a TT1 blocks issue either? It occurred to me while writing this that that might be the case.

**Comment by carolinan** [comment]
With Gutenberg 10.6.0 and TT 1 Blocks version: 0.4.5, the template part is full width when I place it in the site editor, _and it does not have alignment options._
I need to know if the template part was inside another block.

**Comment by annezazu** [comment]
The template part was not inside another block! It was created just beneath a Cover Block.

**Comment by circlecube** [comment]
Yes, I experienced this. I added a template part and dropped a column block inside, then I set up my column content and it seemed to look fine in the editor (without adjusting the alignment settings on either the custom template part or the columns block). 
Here's the blocks in list view to be clear: 
<img width="298" alt="Screen Shot 2021-05-21 at 15 50 19" src="https://user-images.githubusercontent.com/698049/119191752-0d1a2f00-ba4d-11eb-8b66-bb54456e54ad.png">
The editor view:
<img width="1350" alt="Screen Shot 2021-05-21 at 15 50 42" src="https://user-images.githubusercontent.com/698049/119191810-23c08600-ba4d-11eb-9b39-d3f5c52e5e6e.png">

But on the front-end the alignment did not match the editor. The front view: 
<img width="1534" alt="Screen Shot 2021-05-21 at 15 51 32" src="https://user-images.githubusercontent.com/698049/119191851-2fac4800-ba4d-11eb-9ca8-b0c5794aaa25.png">


It took a second and I think may be a "feature" since the template part and the columns can each have their own alignment settings and when combined can achieve some complex layouts, but the real issue is that as a user I didn't expect I had to set the alignment in the editor because it looked good to go already. The custom template part has a no alignment at first and then if I select either the wide or the full alignment option, it adjusts to look better. Seems like the unselected alignment is where it is having issues reflecting what is on the front. 
<img width="230" alt="Screen Shot 2021-05-21 at 15 59 54" src="https://user-images.githubusercontent.com/698049/119192149-a5b0af00-ba4d-11eb-9bdb-1fcccecca08c.png">

Maybe it should force an alignment and have one preselected as default? We just need to make sure the alignment displays in editor like it will on the front, I think that would solve this.

**Comment by carolinan** [comment]
I see the confusion now, I tested in the _site editor_ but both the image and video above is from the _template editor._

**Comment by annezazu** [comment]
Thanks for following up @circlecube with more screenshots. That's correct, Carolina! I'll update the issue title to make that clearer.

**Comment by carolinan** [comment]
Tested again today.
A template part at the root level (not inside another block) does not have wide and full width options. Unless it is aligned to the left or right it always displays at full width.
The front and editor match, both the template part and the inner columns block display at full width.

**Comment by gingerling** [comment]
Hi, I seem to have the opposite issue, or at least there is a lack of clarity.

These two footers look the same in the editor. The top one is the default footer changed from white to green, the bottom one is a pattern changed from black to green. The settings for both blocks seem to be identical, I checked one by one, they were the same.

![Screenshot from 2022-01-15 16-14-29](https://user-images.githubusercontent.com/2853040/149750534-ed4f68f7-78d1-432d-a013-b69eaa92dac5.png)

Yet on the live site I see:

![Screenshot from 2022-01-15 16-14-33](https://user-images.githubusercontent.com/2853040/149750756-61ab94a9-292d-461a-a32c-93abecfc0e34.png)

I had a similar issue earlier with just changing a background to blue

![Screenshot from 2022-01-15 11-56-23](https://user-images.githubusercontent.com/2853040/149750988-5b1d8f05-e45d-40d5-8557-fdd0228ccab9.png)

The editor shows it full width but on the live site there is white space at each side.

![Screenshot from 2022-01-15 11-56-30](https://user-images.githubusercontent.com/2853040/149750931-1aca0439-104b-4f23-ac0a-4628e8033c0c.png)

I didn't check all the settings then as it was just at the start of my testing the editor.

I think that if there is white space on the front of the site it should also be visible in the editor

**Comment by gingerling** [comment]
Note may have been solved by https://github.com/WordPress/twentytwentytwo/pull/336#event-5889749579 apparently, I'm not able to check this with my set up though.

**Comment by kathrynwp** [comment]
@annezazu Hey there :) Circling back to see if this should this be kept open, or can it be closed? Thanks!

**Comment by annezazu** [comment]
Whew, just having time to circle back. I'd like to keep this open. The problem remains with certain template parts. For some reason, GitHub won't let me upload a video but I will try again. For now, here's a link where anyone can view it: https://drive.google.com/file/d/1Fg4lsz67QsRAzFqWXo8ZxbPgx1SjpCTd/view?usp=sharing

**Comment by annezazu** [comment]
Closing this out as two years on we aren't getting much momentum and the issue is inconsistent. Let's reopen or create a new issue if it becomes widespread.
