### ISSUE TITLE
Block editor: "Select all" keyboard shortcut doesn't work anymore in WP 5.8

### ISSUE THREAD

**Issue by audrasjb** [WordPress/gutenberg#33358]
## Description

It looks like there is a regression in the block editor. The `cmd + A` / `ctrl + A` keyboard shortcut doesn't work anymore.

- In 5.7.2 and before, one could use this shortcut to select all the blocks available in the current post.
- In 5.8 RC 2, using this shortcut results in selecting the whole HTML content of the editor screen (see screenshot below).

## Screenshots or screen recording (optional)
![0ef437364445b2d958a40f53ed158c42](https://user-images.githubusercontent.com/1590998/125295038-1e810880-e325-11eb-8601-57764dba28f9.gif)

## WordPress information
- WordPress version: 5.8 RC 2
- Gutenberg version: Not installed
- Are all plugins except Gutenberg deactivated? Yes
- Are you using a default theme (e.g. Twenty Twenty-One)? Yes (Twenty Twenty)

## Device information
- Device: Desktop
- Operating system: OSX
- Browser: Chrome last version

**Comment by gziolo** [comment]
I see that a related fix #33167 from @adamziel might have been already cherry-picked to WP 5.8 recently. Although, it addresses a different issue.

**Comment by audrasjb** [comment]
> I see that a related fix #33167 from @adamziel might have been already cherry-picked to WP 5.8 recently. Although, it addresses a different issue.

Cool. Indeed it addresses a different issue but hopefully it may fix the problem?
That said, it wasn't backported for now

**Comment by gziolo** [comment]
I can confirm that this is a regression.

I found this code in WP 5.7 and it's missing in 5.8:
```js
useShortcut(
		'core/block-editor/select-all',
		useCallback(
			( event ) => {
				event.preventDefault();
				multiSelect(
					first( rootBlocksClientIds ),
					last( rootBlocksClientIds )
				);
			},
			[ rootBlocksClientIds, multiSelect ]
		)
	);
```

It was moved to a different file (`packages/block-editor/src/components/writing-flow/use-select-all.js`) in https://github.com/WordPress/gutenberg/commit/5d0b0f61e01a96e7de4a8138d5b8120fdf75e70a.

It was further refactored in https://github.com/WordPress/gutenberg/commit/37c5148e964022333cc070d0a077a5b9f334e38a to stop using `useShortcut` call, but I see that `'core/block-editor/select-all'` shortcut is still being registered in this place:

https://github.com/WordPress/gutenberg/blob/64f1de6587425808b02a339f82d5fb95193c0011/packages/block-editor/src/components/keyboard-shortcuts/index.js#L218-L228

@ellatrix, any hints on how to resolve this issue?

**Comment by ellatrix** [comment]
It looks like the content is not focused nor is nothing selected when you press cmd+a?

**Comment by Mamaduka** [comment]
> It looks like the content is not focused nor is nothing selected when you press cmd+a?

Yes, this happens when content isn't focused or selected. However, if I focus on content, then the shortcut works as expected.

**Comment by gziolo** [comment]
#33446 should fix it.

**Comment by audrasjb** [comment]
Thanks all for working on this issue <3

**Comment by audrasjb** [comment]
Hi, while testing WP 5.8 RC4 package, I noticed it didn't fix the issue.
I think it's worth to reopen this issue to make it sure it can be addressed before 5.8 is released, if it's even possible :)

**Comment by audrasjb** [comment]
Ok so if you first put the focus on the editor area then it works fine. I think it’s not as good as the previous behavior, but it’s not a blocker anymore for 5.8 in my opinion.
