### ISSUE TITLE
[Post Featured Image]: Add image size controls

### ISSUE THREAD

**Issue by ntsekouras** [WordPress/gutenberg#33789]
## What problem does this address?
We should add image size controls to `Post Featured Image` block (e.g. full, thumbnail, medium, large, custom-theme-size, etc..). Here is @justintadlock 's [comment](https://github.com/WordPress/gutenberg/issues/27620#issuecomment-851016057) for reference.

>To make sure feedback isn't lost from this recent WP Tavern post, I'm sharing here as it's relevant to the discussion above:

>There is no way to set the size of the image output by the Post Featured Image block. The only way to get a uniform size at the moment is to pre-crop the images before uploading them to WordPress. There is no reason this should not essentially be a variation of the Image block. The only thing featured images need that is different is the option to link to the post.

>This was identified as a current pain point in the FSE experience.

Initial design from @jasmussen:

<img width="1440" alt="Featured Image i3" src="https://user-images.githubusercontent.com/1204802/120147692-56a21100-c1e7-11eb-8885-4afea2a523e7.png">

**Comment by Mamaduka** [comment]
This looks like a good enhancement for the [ImageSizeControl](https://github.com/WordPress/gutenberg/tree/trunk/packages/block-editor/src/components/image-size-control) component.

**Comment by markhowellsmead** [comment]
An additional note on this: the [current function](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-featured-image/index.php#L22) (which uses `get_the_post_thumbnail`) currently outputs the thumbnail HTML for the full-sized image. This means that in a basic install where the registered image size `thumbnail` is set to cropped 400x400, this small thumbnail isn't used.

**Comment by ibes** [comment]
@markhowellsmead 
I don't get why the full-size image is pulled after all. 
Can you support me understand that? 'post-thumbnail' is default so I don't get where 'full' is introduced. 

I try to figure out a way how to use existing filters to make that work. 
All I found so far is https://generatepress.com/forums/topic/query-loop-post-template-image-size/
Which has no effect on the image that is actually loaded - just effects the image display dimensions.

**Comment by markhowellsmead** [comment]
There appears to be a little confusion in the code, in as far as there being two thumbnail sizes in the code: `thumbnail` and `post-thumbnail`. I've run through the function stack and debugged this process and it doesn't look as though this is the problem.

The function [`wp_get_attachment_thumb_file`](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L6534) looks for the thumbnail for the image. I've regenerated the thumbnails for my images and they are correctly stored, and the attachment meta data is created. This function searches for an array entry `$imagedata['thumb']`.

However, as far as I can see, the image regeneration function [`wp_create_image_subsizes`](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/image.php#L226) doesn't add an entry to the meta data array with the key `thumb`, so this will never be found. Therefore, the full-size image is selected.

**Comment by markhowellsmead** [comment]
I've added this to Trac at https://core.trac.wordpress.org/ticket/54383.

**Comment by markhowellsmead** [comment]
The response in Trac is that the issue was first flagged in https://core.trac.wordpress.org/ticket/17262.

Eleven years ago. 

You might want to find a different solution.

**Comment by ibes** [comment]
Oh wow - this is absurd. 
Useless gutenberg blocks because a core function was not fixed in 11 years ... 

Thanks for going down the rabbit hole @markhowellsmead 


@markhowellsmead Would you be open to climb down the rabbit hole together to figure out where to put some tape?
Maybe there is a way to deliver  `wp_get_attachment_thumb_file` with the `$imagedata['thumbnail]` and than hook into that process to end up with a more healthy fallback than `full`?!

I used the `latest posts` blocks for blog posts. But am back with wanting to query CPTs. 
And I would like to stay as good with core blocks as possible. Not pulling into a whole group of oppinionated blocks just to compensate for this strange behaviour.

**Comment by ibes** [comment]
```
add_filter( 'post_thumbnail_size', 'update_default_thumbnail_size_for_function_get_the_post_thumbnail' );
function update_default_thumbnail_size_for_function_get_the_post_thumbnail( $size ) {
	if ( $size === 'post-thumbnail' ) {
		return 'medium';
	}
	return $size;
}
```

this might help to set an default image size smaller than `full`

It replaces the unset `post-thumbnail` with `medium`. 

Seems to work for me in the frontend, but not in the editor/backend. 
Don't get why.

**Comment by markhowellsmead** [comment]
I don't think it's a brilliant idea to remove the opportunity to use the post thumbnail in this way. (It might make sense for an individual developer to use this, if that's a project requirement.)

Replacing `post-thumbnail` with `thumbnail` using this filter works, returning the correctly-sized thumbnail image for the `post-featured-image` block.

```
add_filter( 'post_thumbnail_size', 'update_default_thumbnail_size_for_function_get_the_post_thumbnail' );
function update_default_thumbnail_size_for_function_get_the_post_thumbnail( $size ) {
	if ( $size === 'post-thumbnail' ) {
		return 'thumbnail';
	}
	return $size;
}
```

**Comment by markhowellsmead** [comment]
For the post-featured-image block, I suggest modifying the call in the `render_block_core_post_featured_image` method from

`$featured_image = get_the_post_thumbnail( $post_ID );`

to

`$featured_image = get_the_post_thumbnail( $post_ID, 'thumbnail' );`

**Comment by dreamwhisper** [comment]
I'd like to see the full, thumbnail, medium, large, & custom-theme-size(s) selectable to allow for greater flexibility in theme design, especially when the same image may be shown at different sizes throughout a site.

**Comment by hanopcan** [comment]
I'm also keen to see this feature hit production as from a performance point of view not being able to control the size of the featured image is a problem 💚

**Comment by Mamaduka** [comment]
I am assigning this to myself. I will have PR ready shortly.

**Comment by NicoHood** [comment]
You can only choose the dimensions, not the image size type, right? Like medium, large, etc. It seems to be missing in WordPress 6

**Comment by kangabell** [comment]
I'm not seeing the dropdown to select image size (thumbnail, medium, etc.) either. Tested in 6.0 with the "Twenty Twenty-Two" theme, no plugins active. Is there a workaround to get this to appear?

**Comment by Majirefy** [comment]
> You can only choose the dimensions, not the image size type, right? Like medium, large, etc. It seems to be missing in WordPress 6

Same problem, anyone know why?

**Comment by NicoHood** [comment]
I dont know why, but I dont have this feature in my wordpress 6.1 installation. Is this a bug of the astra theme?
![image](https://user-images.githubusercontent.com/6888294/200867373-a3220a2c-f814-44d5-a2b2-29ef49861b76.png)

**Comment by errotu** [comment]
It's rather hidden: You have to click on the three dots next to "Dimensions" ("Größe") and select "Image Size".

**Comment by markhowellsmead** [comment]
@errotu The controls for the Post Featured Image block in the Single template are completely different than in the Archive view. Hardly any of those controls are available and there's no option to choose the image size from the list of preset sizes.

**Comment by EricWorrall** [comment]
You can use editor.PostFeaturedImage to append checkboxes and other controls to the featured image block on the post editor. The options can then be used to modify the display of the featured image. I did this with Magazine Plus, which uses some non-standard hooks for displaying posts,  but you can also do it with more standard hooks. If all else fails you can use the options to control whether CSS scripts are enqueued which create the outcome you want. 

[This post](https://wordpress.stackexchange.com/questions/343447/gutenberg-block-post-featured-image-filter-hook) got me pointed in the right direction.

**Comment by justintadlock** [comment]
You should see an "Image Size" option if you click the "vertical ellipsis" button under the "Dimensions" panel. If you check that option, a new "Image Size" dropdown select should appear:

![image](https://user-images.githubusercontent.com/1816309/208190545-f1725015-c6d0-4329-b483-019229b9e973.png)

**Comment by nicmare** [comment]
> You should see an "Image Size" option if you click the "vertical ellipsis" button under the "Dimensions" panel. If you check that option, a new "Image Size" dropdown select should appear:
> 
> ![image](https://user-images.githubusercontent.com/1816309/208190545-f1725015-c6d0-4329-b483-019229b9e973.png)

wow unbelievable i had to google this and making at least 3 clicks for this hidden feature. thank you  !

**Comment by scrobbleme** [comment]
This should be opened again. There is still no option to choose a predefined size for single templates.

**Comment by vayurobins** [comment]
It's still available @scrobbleme ;-), it's just called "Resolution" now. 
<img width="286" alt="Screenshot 2023-09-03 at 20 37 49" src="https://github.com/WordPress/gutenberg/assets/1386354/c524e695-2c13-4acf-846d-6c313105317a">

**Comment by scrobbleme** [comment]
> It's still available @scrobbleme ;-), it's just called "Resolution" now. 

@vayurobins Yes, but **not** when editing templates within the site editor. The is no resolution available.

**Comment by vayurobins** [comment]
@scrobbleme, that screenshot is from the Full Site Editor, and I was editing the Archives Template. Using Twenty Twenty Three theme.

**Comment by scrobbleme** [comment]
> @scrobbleme, that screenshot is from the Full Site Editor, and I was editing the Archives Template. Using Twenty Twenty Three theme.

@vayurobins Sorry, it is not working for single templates. "Loops" are fine. I just saw, that there is a new issue for this: #50271

**Comment by markhowellsmead** [comment]
If I choose the thumbnail size, then the following HTML is generated.

`<img width="200" height="150" src="https://WEBSITE/wp-content/uploads/2016/05/20160521_DSCF6661-200x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="" decoding="async" style="object-fit:cover;">`

If I choose the "medium" size, then the following HTML is generated. My medium size is 720px, but the srcset options go up to 1600px. Is this intended behaviour? 🤔

`<img width="720" height="480" src="https://WEBSITE/wp-content/uploads/2016/05/20160521_DSCF6661-720x480.jpg" class="attachment-medium size-medium wp-post-image" alt="" decoding="async" style="object-fit:cover;" fetchpriority="high" srcset="https://WEBSITE/wp-content/uploads/2016/05/20160521_DSCF6661-720x480.jpg 720w, https://WEBSITE/wp-content/uploads/2016/05/20160521_DSCF6661-1600x1067.jpg 1600w, https://WEBSITE/wp-content/uploads/2016/05/20160521_DSCF6661-1024x683.jpg 1024w" sizes="(max-width: 720px) 100vw, 720px">`

**Comment by nicmare** [comment]
> If I choose the thumbnail size, then the following HTML is generated.
> 
> `<img width="200" height="150" src="https://WEBSITE/wp-content/uploads/2016/05/20160521_DSCF6661-200x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="" decoding="async" style="object-fit:cover;">`
> 
> If I choose the "medium" size, then the following HTML is generated. My medium size is 720px, but the srcset options go up to 1600px. Is this intended behaviour? 🤔
> 
> `<img width="720" height="480" src="https://WEBSITE/wp-content/uploads/2016/05/20160521_DSCF6661-720x480.jpg" class="attachment-medium size-medium wp-post-image" alt="" decoding="async" style="object-fit:cover;" fetchpriority="high" srcset="https://WEBSITE/wp-content/uploads/2016/05/20160521_DSCF6661-720x480.jpg 720w, https://WEBSITE/wp-content/uploads/2016/05/20160521_DSCF6661-1600x1067.jpg 1600w, https://WEBSITE/wp-content/uploads/2016/05/20160521_DSCF6661-1024x683.jpg 1024w" sizes="(max-width: 720px) 100vw, 720px">`

yes sure what else did you expect?

**Comment by markhowellsmead** [comment]
Errr… that the image displayed in the frontend would be the "medium" image size. (It isn't: it's always the "large" image size. And yes, I'm fully aware of how the `srcset` works on retina screens.)

**Comment by nicmare** [comment]
if the viewport is large enough its loading the high resolution image from the srcset. by default your medium image (20160521_DSCF6661-720x480.jpg)

**Comment by markhowellsmead** [comment]
Nope, it always loads 20160521_DSCF6661-1600x1067.jpg, <s>irrespective of screen size</s> on screens at or larger than 720px.

**Comment by nicmare** [comment]
if you expect something different or have more in depth questions to that specific behavior, you should better create a new thread. this one here is about the image size / resolution control in gutenberg.

**Comment by nicmare** [comment]
> 

thats true. noticed this as well. but as a work around simply copy the featured image block from loop with "resolution" to medium or what ever set and paste it in your single page template. you will notice it now loads the right image size

**Comment by markhowellsmead** [comment]
Forgive me for misunderstanding: how does adding the block in the single template fix the issue in the post loop?

**Comment by nicmare** [comment]
> > @scrobbleme, that screenshot is from the Full Site Editor, and I was editing the Archives Template. Using Twenty Twenty Three theme.
> 
> @vayurobins Sorry, it is not working for single templates. "Loops" are fine. I just saw, that there is a new issue for this: #50271

thats true. noticed this as well. but as a work around simply copy the featured image block from loop with "resolution" to medium or what ever set and paste it in your single page template. you will notice it now loads the right image size

**Comment by scrobbleme** [comment]
> Forgive me for misunderstanding: how does adding the block in the single template fix the issue in the post loop?

@markhowellsmead It doesn't ;)
"Loop" (like archive or just query loop block) and "Single" are different… loop is working as expected ;)

But there are requirements to show a custom  resolution ("add_image_size") in a single template as well (i.e. migrating legacy sites to the block editor)

**Comment by Luke-SF** [comment]
> @vayurobins Yes, but **not** when editing templates within the site editor. The is no resolution available.

Not seeing the resolution picker on normal Image block. Oddly enough resolution does show in the [ settings     ... ]  line drop down menu on the block editor.

**Comment by sinanisler** [comment]
custom sizes are not visible.
![image](https://github.com/WordPress/gutenberg/assets/1686324/b47eb9ac-7d5a-47c3-875b-36c536112d0f)


add_image_size( 'size-400', 400, 400, true );

**Comment by vollyimnetz** [comment]
If you are programming your own block-theme you may use the attribute "**sizeSlug**" to set the custom-image-size "by hand".
```
<!-- wp:post-featured-image {"sizeSlug":"artikelbild","overlayColor":"contrast","dimRatio":0,"style":{"spacing":{"margin":{"bottom":"var:preset|spacing|50","top":"calc(-1 * var(--wp--preset--spacing--50))"}}}} /-->
```

Found in: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-featured-image/block.json

**Comment by SalvatoreNoschese** [comment]
I'm here exactly for same reason. 
I use bitàcora and updated WordPress+litespeed server/plugin.
Cannot found any way to set small or medium featured image size and this cause a poor lcp value.
![Screenshot_20240524-154304](https://github.com/WordPress/gutenberg/assets/16841896/1e2f25b4-0673-429e-ae3f-7231ec50d5ac)

**Comment by justintadlock** [comment]
Folks, if y'all are running into other issues, please open new tickets. The specific issue was addressed.

@sinanisler - Custom image sizes do not automatically appear. You have to add those you want to the dropdown via: https://developer.wordpress.org/reference/hooks/image_size_names_choose/

**Comment by markhowellsmead** [comment]
The image resolution control for the Post Featured Image Block is still not available on the Single Posts (single.html) view in the Site Editor. Running 6.6.1.

**Comment by ajgagnon** [comment]
Yes, why was this skipped for featured images?

**Comment by rosa2** [comment]
> If you are programming your own block-theme you may use the attribute "**sizeSlug**" to set the custom-image-size "by hand".
> 
> ```
> 
> ```
> 
> Found in: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-featured-image/block.json

@vollyimnetz  Thanks a lot. I could make it with your solution editing in the Code Editor in the block on full site theme.
I think this feature is very needed to make easy for interface users the images speed optimization.

**Comment by shanemac10** [comment]
How is this not already added? [This was added to the Gutenberg plugin YEARS ago](https://github.com/WordPress/gutenberg/pull/38044). This is blowing up my page sizes where I use Query Loop blocks with the Featured Image block. I should be able to select a Resolution. The regular Image block waits unlit the Image is loaded in the editor before it loads Resolution options, but the Featured Image block doesn't load or have them at all.

And yes, this hack of adding `"sizeSlug":"medium"` does work
`<!-- wp:post-featured-image {"isLink":true,"width":"","height":"","sizeSlug":"medium"} /-->`
