### ISSUE TITLE
Copying and pasting text in a paragraph block surrounds with spaces

### ISSUE THREAD

**Issue by nyanpasu64** [WordPress/gutenberg#34214]
### Description

When I copy and paste text in certain blocks (including paragraph), it gets surrounded by spaces upon paste.

### Step-by-step reproduction instructions

1. Edit a post with a paragraph.
2. Copy text in the paragraph.
3. Paste text.

Paragraph, heading, and quote citation blocks experience this bug. Quote bodies and page titles do not get surrounded by spaces. Text pasted from outside apps rather than WordPress is not surrounded by spaces.

### Screenshots, screen recording, code snippet

https://user-images.githubusercontent.com/913957/130326447-16a9668a-fb7a-4955-91ef-f6eed38c4b3d.mp4

### Environment info

- Version: Wordpress 5.8, built-in editor, Argon and 2021 theme
- Browser: Firefox and Edge
- Device: Laptop with Windows 10 x64

### Pre-checks

- [X] I have searched the existing issues.
- [X] I have tested with all plugins deactivated except Gutenberg.

**Comment by ramonjd** [comment]
I think this has been resolved by https://github.com/WordPress/gutenberg/issues/33283

The latest version of Gutenberg should have the fixed included. Could you test with 11.3 and try again?

Thank you!

**Comment by nyanpasu64** [comment]
Still happens on 11.3. Note that https://github.com/WordPress/gutenberg/commit/db733694e8ed001971f2dd450769d70a26b0bb27 says it's only in 11.4.0-rc1, and I didn't see any 11.3.x tags that might've included newer commits like this. Maybe it'll be fixed when 11.4 gets released.

**Comment by ramonjd** [comment]
Oh, thanks for testing. 

Sorry, I assumed that it was in 11.3 since it was merged 14 days ago.

11.4.0 should be released sometime next week after Wednesday or thereabout.

**Comment by nyanpasu64** [comment]
Seems fixed. I assume it will be fixed in a WordPress release (without the Gutenberg plugin) at some point?
