### ISSUE TITLE
Navigation Block expands to fill all available space, breaks justification.

### ISSUE THREAD

**Issue by pbking** [WordPress/gutenberg#35742]
### Description

Seemingly due to this change the `wp-block-navigation__responsive-container`  class now has a `width:100%` which causes the container to fill all available space.  This breaks the justification of the menu layout, particularly right-aligned content such as Blockbase's header (as noted in [this related issue](https://github.com/Automattic/themes/issues/4860)).

### Step-by-step reproduction instructions

Activate Blockbase theme.  Configure menus in customizer.   (Bonus points for applying social menus).

Note that the navigation block does not justify content to the right despite that block's right justification option:
`
`

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/146530/137777221-5650b511-39f3-4204-8035-a07783129159.png)

### Environment info

/trunk of Gutenberg

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by jasmussen** [comment]
Thanks for the ticket. Can you try this against latest version of trunk? Just 5 hours ago I merged a change which I think might have fixed this: https://github.com/WordPress/gutenberg/pull/35722

**Comment by pbking** [comment]
I pulled recent changes to /trunk and indeed the problem persists.

It is only an issue when the block is in a container with display:flex as illustrated here:
```
<!-- wp:group {"align":"wide","layout":{"type":"flex"}} -->
<div class="wp-block-group alignwide"><!-- wp:navigation -->
<!-- wp:navigation-link {"label":"A test","url":"http://inter.net","isTopLevelLink":true} /-->
<!-- /wp:navigation --></div>
<!-- /wp:group -->
```

The problem is coupled with an attribute that Blockbase applies to the header to achieve the design target:
```
.wp-site-blocks .site-header .wp-block-navigation {
    flex-grow: 1;
}
```
So the two things don't play nice together.

It may be that the same design target can be achieved using a  between the menu and the rest of the content and giving that a flex-grow value via CSS instead. But it seems more appropriate to remove the forced 100% width to me.

**Comment by jasmussen** [comment]
I think I found steps to reproduce:

- Insert a row block
- Insert a navigation block inside the row block
- Justify the navigation block _right_

The navigation block will not be right aligned. In my testing using both Empty Theme and Blockbase, this was the case both in the editor and the frontend:
![nav](https://user-images.githubusercontent.com/1204802/137875124-de5ba122-8579-4b36-bedd-528232c070e1.gif)

Also shown in the GIF, though, is that you can justify right on the Row block itself. Does that address the use case?

Let me know if I misunderstood the steps to reproduce. It would be helpful if I could have some full demo content showing the problem.

**Comment by pbking** [comment]
No, that doesn't address our use case in the Blockbase header.  The content of the row can't be aligned right; some content is on the left (Site Title, logo, tagline) and some on the right (navigation).  The elements in that header are dynamic though; there's no guarantee that any of them will be there so the layout mechanism has to take that into account.

**Comment by jasmussen** [comment]
Understood, and if you use space-between, the site logo and site title will be spaced out as well:
<img width="1074" alt="Screenshot 2021-10-19 at 15 29 26" src="https://user-images.githubusercontent.com/1204802/137919761-eb4c274d-633c-40d1-b286-401e49f8c81c.png">

You could add an extra row wrapper around just the site logo and site title, combined with space-between on the topmost row:
<img width="1391" alt="Screenshot 2021-10-19 at 15 31 40" src="https://user-images.githubusercontent.com/1204802/137920147-c952d570-eb39-484b-9576-1c8b0ccb8d56.png">

Adding `flex-grow: 1;` back to the navigation block where it was _would_ accomplish the first example shown, but it was intentionally [scoped to only apply when set to space-between](https://github.com/WordPress/gutenberg/pull/35722). It was interfering with patterns that added blocks other than menu items. For example this pattern, a few items and social links:
<img width="954" alt="Screenshot 2021-10-19 at 15 36 09" src="https://user-images.githubusercontent.com/1204802/137921456-4e6dd462-248c-4189-bb6b-25900bb57fc9.png">

With `flex-grow: 1;` applied to the navigation portion, it would push the social icons to the right:
<img width="1002" alt="Screenshot 2021-10-19 at 15 37 59" src="https://user-images.githubusercontent.com/1204802/137921536-f63d23ba-3f71-4ea9-804d-b8e47b9e3070.png">

Even keeping `flex-grow: 1;` in the space-between state likely needs to be revisited, as even this state should account for other blocks, and arguably space out the social links as well.

---

TwentyTwentyTwo comes with a bunch of patterns that appear to accomplish a similar design. Would the approach taken there work for you?
<img width="2267" alt="Screenshot 2021-10-19 at 15 44 22" src="https://user-images.githubusercontent.com/1204802/137922578-cf859b18-76aa-4b8b-9f5d-be72d2154c0d.png">

Many of these appear to rely on the extra row block grouping site logo/title together on the left:
<img width="274" alt="Screenshot 2021-10-19 at 15 49 55" src="https://user-images.githubusercontent.com/1204802/137923581-0e246a6f-6b34-4643-a94c-8649538b7b54.png">

**Comment by pbking** [comment]
Closing this as the design can be achieved as noted above.  Thank you!

**Comment by jasmussen** [comment]
Thank you! And thank you for the ticket, it's helpful as we explore getting the flex rules just right 👌
