### ISSUE TITLE
Save page button is not working within FSE if edited the content after Saving Changes

### ISSUE THREAD

**Issue by malavvasita** [WordPress/gutenberg#38103]
### Description

Hello There,

I was just checking with FSE and built a demo store.
I have noticed that when we are changing content after Saving the content on-page, the Save button is not getting reactivated.

This can be crucial for v5.9.

Thank you.

### Step-by-step reproduction instructions

Steps to Reproduce:
1. Installed WP 5.9-RC3
2. Created a Page
3. Editing Page with Shortcode 
`[video width="1920" height="1080" src="https://georgeabitbol.fr/content/uploads/2022/01/finalV4.mp4" autoplay="on" preload="auto"][/video]
`
4. Save the page once.
5. Edit the Shortcode Attribute(s).
6. The Save Button is not getting reactivated.

### Screenshots, screen recording, code snippet

Find the video for reproducing the issue:
https://drive.google.com/file/d/1JRot5LM1xeq3nfcJUTsvOJjW2C6w4Ck0/view

### Environment info

WP Version - 5.9 ( RC3 )
PHP Version - 8.0.9
Browser - Google Chrome [ Version 97.0.4692.71 (Official Build) (64-bit) ]
Device - Desktop [Windows 10]

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I can reproduce the issue, but it only happens with a shortcode block.

@malavvasita, do you get similar results with any other blocks?

**Comment by malavvasita** [comment]
@Mamaduka I've tested the commonly used blocks, Although not all blocks.
I am facing an issue with the Shortcode block only.

I will update if I would face an issue like this with other blocks.

**Comment by Mamaduka** [comment]
I think the issue was fixed via #36887.  I couldn't reproduce the bug with Gutenberg 12.2 and later.

Cc @talldan.

**Comment by malavvasita** [comment]
@Mamaduka 

I am using the latest RC for 5.9 i.e. RC-3.
And I can still see the reported issue.

Do WP v5.9 - RC3 have Latest Gutenberg integrated?

**Comment by Mamaduka** [comment]
> Do WP v5.9 - RC3 have Latest Gutenberg integrated?

No latest Gutenberg plugin shipped with 5.9 RC is 11.9 + some bug fixes.

I would appreciate it if you can confirm that the bug doesn't exists when using [Gutenberg 12.4](https://wordpress.org/plugins/gutenberg/).

**Comment by malavvasita** [comment]
Got it.

I have installed the latest version of Gutenberg and the issue doesn't appear anymore.
Thank you @Mamaduka for your help.

**Comment by Mamaduka** [comment]
@malavvasita, let's keep this issue open for now. We might decide to backport the fix to WP 5.9.
