### ISSUE TITLE
WP 5.9 adds default Duotones before closing the body

### ISSUE THREAD

**Issue by mkkeck** [WordPress/gutenberg#38299]
### Description

I've updated my WP to 5.9. Now there is new junk added before `</body>`, some SVG's and Style's.
This does not make sense, because I'm not using FSE and have disabled duotone and gradients.

### Step-by-step reproduction instructions

1. View html code of a page rendered with 5.8
2. View html code of the same page rendered with 5.9
3. In 1.) there are no SVG and Styles before closing body but in 2.)

### Environment info

- Wordpress 5.9 with its Gutenberg
- Own non-FSE theme
- theme.json with dutotone:[], and customDuotone: false

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by johnstonphilip** [comment]
I am seeing this too:
`
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 0 0" width="0" height="0" focusable="false" role="none" style="visibility: hidden; position: absolute; left: -9999px; overflow: hidden;" ><defs><filter id="wp-duotone-dark-grayscale"><feColorMatrix color-interpolation-filters="sRGB" type="matrix" values=" .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 " /><feComponentTransfer color-interpolation-filters="sRGB" ><feFuncR type="table" tableValues="0 0.49803921568627" /><feFuncG type="table" tableValues="0 0.49803921568627" /><feFuncB type="table" tableValues="0 0.49803921568627" /><feFuncA type="table" tableValues="1 1" /></feComponentTransfer><feComposite in2="SourceGraphic" operator="in" /></filter></defs></svg><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 0 0" width="0" height="0" focusable="false" role="none" style="visibility: hidden; position: absolute; left: -9999px; overflow: hidden;" ><defs><filter id="wp-duotone-grayscale"><feColorMatrix color-interpolation-filters="sRGB" type="matrix" values=" .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 " /><feComponentTransfer color-interpolation-filters="sRGB" ><feFuncR type="table" tableValues="0 1" /><feFuncG type="table" tableValues="0 1" /><feFuncB type="table" tableValues="0 1" /><feFuncA type="table" tableValues="1 1" /></feComponentTransfer><feComposite in2="SourceGraphic" operator="in" /></filter></defs></svg><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 0 0" width="0" height="0" focusable="false" role="none" style="visibility: hidden; position: absolute; left: -9999px; overflow: hidden;" ><defs><filter id="wp-duotone-purple-yellow"><feColorMatrix color-interpolation-filters="sRGB" type="matrix" values=" .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 " /><feComponentTransfer color-interpolation-filters="sRGB" ><feFuncR type="table" tableValues="0.54901960784314 0.98823529411765" /><feFuncG type="table" tableValues="0 1" /><feFuncB type="table" tableValues="0.71764705882353 0.25490196078431" /><feFuncA type="table" tableValues="1 1" /></feComponentTransfer><feComposite in2="SourceGraphic" operator="in" /></filter></defs></svg><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 0 0" width="0" height="0" focusable="false" role="none" style="visibility: hidden; position: absolute; left: -9999px; overflow: hidden;" ><defs><filter id="wp-duotone-blue-red"><feColorMatrix color-interpolation-filters="sRGB" type="matrix" values=" .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 " /><feComponentTransfer color-interpolation-filters="sRGB" ><feFuncR type="table" tableValues="0 1" /><feFuncG type="table" tableValues="0 0.27843137254902" /><feFuncB type="table" tableValues="0.5921568627451 0.27843137254902" /><feFuncA type="table" tableValues="1 1" /></feComponentTransfer><feComposite in2="SourceGraphic" operator="in" /></filter></defs></svg><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 0 0" width="0" height="0" focusable="false" role="none" style="visibility: hidden; position: absolute; left: -9999px; overflow: hidden;" ><defs><filter id="wp-duotone-midnight"><feColorMatrix color-interpolation-filters="sRGB" type="matrix" values=" .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 " /><feComponentTransfer color-interpolation-filters="sRGB" ><feFuncR type="table" tableValues="0 0" /><feFuncG type="table" tableValues="0 0.64705882352941" /><feFuncB type="table" tableValues="0 1" /><feFuncA type="table" tableValues="1 1" /></feComponentTransfer><feComposite in2="SourceGraphic" operator="in" /></filter></defs></svg><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 0 0" width="0" height="0" focusable="false" role="none" style="visibility: hidden; position: absolute; left: -9999px; overflow: hidden;" ><defs><filter id="wp-duotone-magenta-yellow"><feColorMatrix color-interpolation-filters="sRGB" type="matrix" values=" .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 " /><feComponentTransfer color-interpolation-filters="sRGB" ><feFuncR type="table" tableValues="0.78039215686275 1" /><feFuncG type="table" tableValues="0 0.94901960784314" /><feFuncB type="table" tableValues="0.35294117647059 0.47058823529412" /><feFuncA type="table" tableValues="1 1" /></feComponentTransfer><feComposite in2="SourceGraphic" operator="in" /></filter></defs></svg><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 0 0" width="0" height="0" focusable="false" role="none" style="visibility: hidden; position: absolute; left: -9999px; overflow: hidden;" ><defs><filter id="wp-duotone-purple-green"><feColorMatrix color-interpolation-filters="sRGB" type="matrix" values=" .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 " /><feComponentTransfer color-interpolation-filters="sRGB" ><feFuncR type="table" tableValues="0.65098039215686 0.40392156862745" /><feFuncG type="table" tableValues="0 1" /><feFuncB type="table" tableValues="0.44705882352941 0.4" /><feFuncA type="table" tableValues="1 1" /></feComponentTransfer><feComposite in2="SourceGraphic" operator="in" /></filter></defs></svg><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 0 0" width="0" height="0" focusable="false" role="none" style="visibility: hidden; position: absolute; left: -9999px; overflow: hidden;" ><defs><filter id="wp-duotone-blue-orange"><feColorMatrix color-interpolation-filters="sRGB" type="matrix" values=" .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 .299 .587 .114 0 0 " /><feComponentTransfer color-interpolation-filters="sRGB" ><feFuncR type="table" tableValues="0.098039215686275 1" /><feFuncG type="table" tableValues="0 0.66274509803922" /><feFuncB type="table" tableValues="0.84705882352941 0.41960784313725" /><feFuncA type="table" tableValues="1 1" /></feComponentTransfer><feComposite in2="SourceGraphic" operator="in" /></filter></defs></svg><script src='http://mydomain.com/wp-includes/js/hoverintent-js.min.js?ver=2.2.1' id='hoverintent-js-js'></script>
`

Looks to be related to duo tone things, which I am not using.

**Comment by lwangdu** [comment]
I am seen the seem issue. I have reported this issue before but nothing happened.
![Screen Shot 2022-01-27 at 2 55 59 PM](https://user-images.githubusercontent.com/24829573/151457582-b84dd8f0-17a5-43a7-9a5d-8015559b5a35.png)
.

**Comment by mkkeck** [comment]
> I am seen the seem issue. I have reported this issue before but nothing happened.

That shows me again, before releasing a new Version and/or feature testing is not done carefull and complete and more and more we have to accept the dictation and forcing us using things we can not opt-out, wether what we want.

**Comment by mkkeck** [comment]
I see at the moment:
The stupied added junk breaks my page layout, there is extra spacing (`blockGap`) added!

WHY? WHY? WHY? WHY IS THIS DONE?!
I CAN EDIT MY THEME AT MY OWN! I DO NOT NEED WORDPRESS FEATURES BREAKING MY PAGES / AND THEMES!
PUT THESE STUPIED JUNK OF FEATURES INTO YOU OWN THEMES!

**Comment by Soean** [comment]
@mkkeck 
>That shows me again, before releasing a new Version and/or feature testing is not done carefull and complete and more and more we have to accept the dictation and forcing us using things we can not opt-out, wether what we want.

It is possible to test the release candidate and give feedback before an update. This way the whole project can benefit from it.

>I DO NOT NEED WORDPRESS FEATURES BREAKING MY PAGES / AND THEMES!

No one has intentionally broken your site. The bug will surely be fixed in one of the next versions.

**Comment by Soean** [comment]
Related:
 - #37927 opend by @lwangdu

**Comment by mkkeck** [comment]
@Soean
> It is possible to test the release candidate and give feedback before an update. This way the whole project can benefit from it.

Okay this point goes to you ;)
You are right.

> No one has intentionally broken your site. The bug will surely be fixed in one of the next versions.

I've not said, that some one has intentionally broken my site ...
But for some time now, features, knitted with the hot needle without documentation, without opt-out and without the possibility of a back port in case of an error, are introduced into WordPress, which often lead to problems and are not thought through to the end. This in turn then shatters painstakingly created layouts or complete websites, makes the work of theme and plugin developers to nothing and leads again and again to frustration.

Why is WordPress now rolling out global CSS styles in the front-end, regardless of loss, ruin and infirmity? Why, and this has been criticized for months, is there no way to adjust this, sometimes seriously interfering with the content and front-end, by an opt-in or opt-out?

**Comment by skorasaurus** [comment]
Hi, 

Thanks for reporting; 
This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/24684. Please share your opinion in that issue. 

As a workaround, you can disable the default colors by [disabling the global styles](https://github.com/WordPress/gutenberg/issues/36834#issuecomment-1021980079).

**Comment by mkkeck** [comment]
Awww,

Why closing? This is really not the same thing as in #24684.

Closing this issue and your answer @skorasaurus shows again, that it does not really make sense to report issues and leave critical comments.

Ciao.

**Comment by skorasaurus** [comment]
@mkkeck 

If you can clarify how this issue is different, I would appreciate it so then I'd know to reopen it. On second review, you mentioned the inclusion of SVG files although that is also mentioned at https://github.com/WordPress/gutenberg/issues/37927. 

Both issues discuss that extra CSS global styles (that define colors) are included in the page even when the default color palette is disabled and that behavior is unexpected.

**Comment by bridgeport** [comment]
@skorasaurus It seems like @mkkeck issue is different from #37927 as it appears @mkkeck doesn't want the SVG inserted at all. Not even one instance, as they're not using duotone. I don't even believe they're experiencing the duplicate issue.

The issue you cited is someone reporting multiple, duplicate STYLE and SVG insertions within the HTML. They don't seem to have any objection to the STYLE and SVG inserted, as long as there's only one proper instance.

@mkkeck appears to want some method or filter to disable the SVG footer output to keep their HTML clean. There doesn't appear to be a way to disable/deactivate this like you would other filters.

For instance, you could use something like the following to prevent the `loading` attribute from being used:

```php
add_filter( 'wp_lazy_loading_enabled', '__return_false' );
```

But there's no equivalent for preventing the SVG HTML from being inserted into the footer of every page and post AFAIK. It's being inserted whether or not there's any block on the page that has duotone enabled.

If you're not using duotone, its existence within the HTML serves no purpose.

**Comment by Kovalchik8** [comment]
```
add_action('init', function() {

  // remove duotone support for Gutenberg blocks
  remove_filter('render_block', 'wp_render_duotone_support');
});
```

**Comment by bridgeport** [comment]
@Kovalchik8 Your code doesn't remove the SVG code from the footer. The duotone SVG HTML is still inserted on every page and post.

A few days ago, someone also posted on the wordpress support forums that this filter removal no longer works:
https://wordpress.org/support/topic/disabling-gutenberg-duotone-filter/#post-15300929

**Comment by mkkeck** [comment]
> @mkkeck 
> 
> If you can clarify how this issue is different, I would appreciate it so then I'd know to reopen it. On second review, you mentioned the inclusion of SVG files although that is also mentioned at https://github.com/WordPress/gutenberg/issues/37927. 

This issue is another new `feature`, which bloats the HTML output, wether using duotone and/or blockGap or not, and has nothing to do with the other also not always needed `features`.

> Both issues discuss that extra CSS global styles (that define colors) are included in the page even when the default color palette is disabled and that behavior is unexpected. 

Yes that's correct, but it's another building site. This issue here exists since WP 5.9 only and has nothing to do with default color palette.

If I don't want and not have configured or have disabled the duotone and blockGap settings, than I don't want, that WordPress bloats the rendered HTML for the frontend with styles and SVGs, which never used, before closing the body.

Reading the reported issue and comparing with changelogs may be help, before simple closing and reporting issues are duplicate of an existing one.

**Comment by mkkeck** [comment]
> Hi, 
> 
> Thanks for reporting; 
> This has been discussed and/or requested in https://github.com/WordPress/gutenberg/issues/24684. Please share your opinion in that issue. 
> 
> As a workaround, you can disable the default colors by [disabling the global styles](https://github.com/WordPress/gutenberg/issues/36834#issuecomment-1021980079). 
> 

I've disabled global styles :)
But it does not solve this issue.

I've also added follow lines in my functions.php to remove the wp-container- styles produced by blockGap and the duotone-styles:

```php
remove_filter('render_block', 'wp_render_duotone_support');
remove_filter('render_block', 'wp_restore_group_inner_container');
remove_filter('render_block', 'wp_render_layout_support_flag');
```

But the junk SVG can not be removed at the moment, missing an action/ filter to remove them. The problem is:

```php
// file: wp-includes/block-supports/duotone.php;
// line: #459 ... 467 
// produces the junk SVG, even if duot0ne is not used.
// Other point: Why fallbacks for stupid Safari,
// which force other browsers to load this junk?
add_action( 
  // Safari doesn't render SVG filters defined in data URIs, 
  // and SVG filters won't render in the head of a document, 
  // so the next best place to put the SVG is in the footer. 
  is_admin() ? 'admin_footer' : 'wp_footer', 
  function () use ( $svg ) { echo $svg; } 
);

**Comment by mkkeck** [comment]
The duotone and blockGap stuff should perhabs moved from the WordPress core to the Twenty-themes.

**Comment by oguilleux** [comment]
Hi @mkkeck 

Try this : 

```
function remove_global_styles() {
  remove_action('wp_enqueue_scripts', 'wp_enqueue_global_styles');
  remove_action('wp_footer', 'wp_enqueue_global_styles', 1);
}
add_action('after_setup_theme', 'remove_global_styles', 10, 0);
```

**Comment by mkkeck** [comment]
> Hi @mkkeck 
> 
> Try this : 
> 
> ```
> function remove_global_styles() {
>   remove_action('wp_enqueue_scripts', 'wp_enqueue_global_styles');
>   remove_action('wp_footer', 'wp_enqueue_global_styles', 1);
> }
> add_action('after_setup_theme', 'remove_global_styles', 10, 0);
> ```

Thanks for your feedback.

I think, this would not remove the duotone SVGs. There's a hardcoded action in file `wp-includes/block-supports/duotone.php#459 ... 467`

**Comment by oguilleux** [comment]
Oh ! Are you sure ? I have the same problem and I don't see the duotone SVGs anymore with these actions removed.

**Comment by mkkeck** [comment]
> Oh ! Are you sure ? I have the same problem and I don't see the duotone SVGs anymore with these actions removed.

Ok, I will give it a try, when I'm in office.
Are using WP5.9 with its shipped Gutenberg, or do you use Gutenberg as a plugin?
I'm using the shipped Gutenberg.

**Comment by oguilleux** [comment]
WP 5.9

**Comment by Soean** [comment]
I reopen the issue. I can reproduce it withe a new theme.

```JSON
{
	"settings": {
		"color": {
			"duotone": [],
			"customDuotone": false
		}
	}
}
```

We have `"defaultGradients": false` and `"defaultPalette": false` but not `"defaultDoutones": false`

**Comment by mkkeck** [comment]
> Hi @mkkeck
> 
> Try this :
> 
> ```
> function remove_global_styles() {
>   remove_action('wp_enqueue_scripts', 'wp_enqueue_global_styles');
>   remove_action('wp_footer', 'wp_enqueue_global_styles', 1);
> }
> add_action('after_setup_theme', 'remove_global_styles', 10, 0);
> ```

This removes the SVGs :)
Thanks.

I've added now to my theme `functions.php`:

```php
add_action('after_setup_theme', function() {

  // remove SVG and global styles
  remove_action('wp_enqueue_scripts', 'wp_enqueue_global_styles');

  // remove wp_footer actions which add's global inline styles
  remove_action('wp_footer', 'wp_enqueue_global_styles', 1);

  // remove render_block filters which adding unnecessary stuff
  remove_filter('render_block', 'wp_render_duotone_support');
  remove_filter('render_block', 'wp_restore_group_inner_container');
  remove_filter('render_block', 'wp_render_layout_support_flag');
});
```

**Comment by mkkeck** [comment]
It's not only adding Duotones, the styles for each wp-container-idxxxx of the blockGap feature, which is disabled in my theme, is also added. So that's why I've said "WP 5.9 adds junk before closing the body". 

There should nothing overwritten, replaced or added or merged with WP global styles, which can break existing themes.
Please note: Not all users are using Twenty-xxx-themes.
And please put such things into the Twenty-xxx-themes and not to the core!

**Comment by Kovalchik8** [comment]
> add_action('init', function() {
>
>  // remove duotone support for Gutenberg blocks
>  remove_filter('render_block', 'wp_render_duotone_support');
>});

I wonder why this doesn't work, though it works partly (after page reloading duotone SVG disappears from time to time).
Need to notice that I didn't search for someone's solutions but found the WP core code where exactly this redundant svg html is adding, so `remove_filter('render_block', 'wp_render_duotone_support')` is exactly what should be added in order to remove it.

Kind of bug  and probably will be fixed soon.

**Comment by Luehrsen** [comment]
A clean classic/hybrid theme will add the SVGs for duotone filters as well.

I really hope this will get fixed soon, as this has a noticable size impact on a lot of sites. 

https://gist.github.com/Luehrsen/d68fc59bff764358d35f24bfa2933371

**Comment by stratboy** [comment]
Me too here. looking forward to see fixes really soon.

**Comment by cbirdsong** [comment]
Removing this filter is not necessary for getting rid of the duotone output and it affects the markup of the group block:

```php
remove_filter('render_block', 'wp_restore_group_inner_container');
```

**Comment by mkkeck** [comment]
> Removing this filter is not necessary for getting rid of the duotone output and it affects the markup of the group block:
> 
> ```php
> remove_filter('render_block', 'wp_restore_group_inner_container');
> ```

For my theme I need to remove this filter, because I don't want additional inline styles adding. It was good for me, that inner containers are removed, so there's no require to restore them.

**Comment by scenicrte** [comment]
Thanks for all the info. I have 112 extra lines of svg and duotone code showing up just before the closing HTML tag in my site and was glad to find this thread.

**Comment by akkis** [comment]
You can disable completely generated SVG code with `theme.json` like jumbo did [here](https://wordpress.org/support/topic/disabling-gutenberg-duotone-filter/#post-15300408)
but it breaks block editor :(

**Comment by Soean** [comment]
@akkis No, `doutone` needs to be an array, null is not a valid value. 

This generates a PHP error:
`Warning:  Undefined variable $filters in /wp-content/plugins/gutenberg/lib/compat/wordpress-5.9/class-wp-theme-json-gutenberg.php on line 1527`

**Comment by akkis** [comment]
Thank you @Soean I did not check any block editor. I stand for front end issue, and it solves my issue. So, we are waiting for a solution/filter/hook for disable the SVG elements.

**Comment by mkkeck** [comment]
> @akkis No, `doutone` needs to be an array, null is not a valid value. 
> 
> This generates a PHP error:
> `Warning:  Undefined variable $filters in /wp-content/plugins/gutenberg/lib/compat/wordpress-5.9/class-wp-theme-json-gutenberg.php on line 1527`

And it breaks Gutenberg's js too

**Comment by akkis** [comment]
But [this solution](https://core.trac.wordpress.org/ticket/54941#comment:6) works without ruins the gutenberg editing interface.

**Comment by vielhuber** [comment]
This is obviously a bug and should be fixed:

The function `wp_get_global_stylesheet()` calls `WP_Theme_JSON_Resolver::get_merged_data()`, which creates an object of class `WP_Theme_JSON` and uses it to call (via `PRESETS_METADATA`) `wp_render_duotone_filter_preset`, in which `add_action` is used to set the SVGs in wp_footer.

At the same time, a transient (in case of `WP_DEBUG = false`) is set in the `wp_get_global_stylesheet()` function, which lives for one minute. If this transient is then available at the next request, it will be used directly (in case of `WP_DEBUG = false`); Apparently the developers forgot (or even intended?) to call `WP_Theme_JSON_Resolver::get_merged_data()` (which then finally leads to the fact that the duotone SVGs are not included in this case).

That means:
- On production environments the SVGs are added once a minute and in between not
- On development environments the SVGs are added always

This does not seem right.

**Comment by ajlende** [comment]
It sounds to me like an acceptable solution would be adding a new `defaultDuotone` option that works the same way as `defaultGradient` and `defaultPalette` in https://github.com/WordPress/gutenberg/pull/36492 and make sure that it is opted out by default for themes without a theme.json like in https://github.com/WordPress/gutenberg/pull/36496.

**Comment by vralle** [comment]
If the theme uses global styles, this workaround will only remove the svg
```php
/**
 * Fix output duotone svg filters in footer
 *
 * @link https://github.com/WordPress/gutenberg/issues/38299
 * @link https://core.trac.wordpress.org/ticket/54941
 *
 * @return void
 */
function fix_output_duotone_svg() {
	$filters = $GLOBALS['wp_filter']['wp_footer'][10];
	if ( empty( $filters ) ) {
		return;
	}

	foreach ( $filters as $callback ) {
		if ( $callback['function'] instanceof \Closure ) {
			$instance  = new \ReflectionFunction( $callback['function'] );
			$variables = $instance->getStaticVariables();
			if ( ! empty( $variables['svg'] ) && strpos( $variables['svg'], 'feColorMatrix' ) ) {
				remove_action( 'wp_footer', $callback['function'], 10 );
			}
		}
	}
}
add_action( 'wp_footer', 'fix_output_duotone_svg', 0 );
```
Tested with WP5.9
The solution is not ideal and will need to be removed when it becomes possible to remove block supports at the global level. Something like `WP_Block_Supports::get_instance()->deregister( 'duotone' );`

**Comment by sitoexpress** [comment]
> If the theme uses global styles, this workaround will only remove the svg
> 
> ```
> /**
>  * Fix output duotone svg filters in footer
>  *
>  * @link https://github.com/WordPress/gutenberg/issues/38299
>  * @link https://core.trac.wordpress.org/ticket/54941
>  *
>  * @return void
>  */
> function fix_output_duotone_svg() {
> 	$filters = $GLOBALS['wp_filter']['wp_footer'][10];
> 	if ( empty( $filters ) ) {
> 		return;
> 	}
> 
> 	foreach ( $filters as $callback ) {
> 		if ( $callback['function'] instanceof \Closure ) {
> 			$instance  = new \ReflectionFunction( $callback['function'] );
> 			$variables = $instance->getStaticVariables();
> 			if ( ! empty( $variables['svg'] ) && strpos( $variables['svg'], 'feColorMatrix' ) ) {
> 				remove_action( 'wp_footer', $callback['function'], 10 );
> 			}
> 		}
> 	}
> }
> add_action( 'wp_footer', 'fix_output_duotone_svg', 0 );
> ```
> 
> Tested with WP5.9 The solution is not ideal and will need to be removed when it becomes possible to remove block supports at the global level. Something like `WP_Block_Supports::get_instance()->deregister( 'duotone' );`

Thanks for this solution, I was thinking to be the only one fighting that mess in the HTML... I'm really worried about this new "WordPress way". 

There's really no reason at all for a SVG duotone filter to be loaded by default as a "most wanted" feature

While I *might* be able to understand why WordPress is shifting towards another direction, I really can't understand how someone could think of forcing the Duotone filter on us :(

Since when duotone has become so popular?

**Comment by mkkeck** [comment]
> There's really no reason at all for a SVG duotone filter to be loaded by default as a "most wanted" feature
> 
> While I *might* be able to understand why WordPress is shifting towards another direction, I really can't understand how someone could think of forcing the Duotone filter on us :(
> 
> Since when duotone has become so popular?

And I think it is mainly added inline before `</body>` to support the Safari on iOS.

**Comment by vralle** [comment]
> Since when duotone has become so popular?

This is just a small mistake that will be fixed quickly. But it is not exactly)

We all need to remember that we are using WP for free. And our choice is also free.

**Comment by Mamaduka** [comment]
@ajlende, I agree that using `defaultDuotone` or something similar sounds like an acceptable solution.

Do you have the capacity to work on PR, and maybe we can ship it with 5.9.1?

@oandregal, what do you think?

**Comment by mkkeck** [comment]
Why not using current avaliable fields only?
If `duotone` null or an empty array and `customDuotone`  false should disable this feature. In my opion, that would be the expected behavior instead forcing disabling a third parameter (too).

And of course it would be nice, if the Safari stuff only is added on Safari browsers, this may be done via javascript.

Why should we punish all other browser supporting and working correctly?

**Comment by mkkeck** [comment]
> @akkis No, `doutone` needs to be an array, null is not a valid value. 
> 
> This generates a PHP error:
> `Warning:  Undefined variable $filters in /wp-content/plugins/gutenberg/lib/compat/wordpress-5.9/class-wp-theme-json-gutenberg.php on line 1527`

That should be fixed too, with a check:
`!empty($...) && is_array($...)` before loops.

**Comment by ajlende** [comment]
> I agree that using `defaultDuotone` or something similar sounds like an acceptable solution.
> 
> Do you have the capacity to work on PR, and maybe we can ship it with 5.9.1?

@Mamaduka I got a branch started. I have to test a few more things, but feel free to take an early look #38681

**Comment by ChadReitsma** [comment]
None of these work in 5.9.1.  It would be nice if there was a filter to disable this completely - we don't like or use Gutenberg on our client sites.

**Comment by akkis** [comment]
> None of these work in 5.9.1. It would be nice if there was a filter to disable this completely - we don't like or use Gutenberg on our client sites.

I use the first solution from this link: https://core.trac.wordpress.org/ticket/54941#comment:6

**Comment by ChadReitsma** [comment]
> > None of these work in 5.9.1. It would be nice if there was a filter to disable this completely - we don't like or use Gutenberg on our client sites.
> 
> I use the first solution from this link: https://core.trac.wordpress.org/ticket/54941#comment:6

Comment #6 doesn't work.  They SVG output appears to be in the body now.

**Comment by Mamaduka** [comment]
Hi, @ChadReitsma

Can you try the following snippet for 5.9.1?

```php
remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
```

Also related PR - #39018

**Comment by mkkeck** [comment]
Why not putting the duotone stuff from core to Twenty themes?

**Comment by ChadReitsma** [comment]
> Hi, @ChadReitsma
> 
> Can you try the following snippet for 5.9.1?
> 
> ```
> remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
> ```
> 
> Also related PR - #39018

Ah. THANK-YOU, that worked!

**Comment by daverobertson** [comment]
> > I agree that using `defaultDuotone` or something similar sounds like an acceptable solution.
> > Do you have the capacity to work on PR, and maybe we can ship it with 5.9.1?
> 
> @Mamaduka I got a branch started. I have to test a few more things, but feel free to take an early look #38681

Being able to set `"defaultDuotones": false`, in theme.json would be great! We're developing a theme that provisions a couple custom duotones. However, all the core/bundled ones (e.g. blue-orange, yellow-purple, etc — that we don't want) are still being rendered in the html alongside our custom ones no matter what. Having a way to disable just those, while preserving only our theme's custom duotones, would be welcome.

**Comment by JiveDig** [comment]
I'd like to clarify a use-case. Our theme uses blocks, but not theme.json. We'd like duotone options available in the block settings, but svgs should only be rendered on pages that duotone is actually used for a block, and only the svgs required for the selected style. 

I'm happy there is a filter now to disable the output completely, but I'm hoping everyone else isn't left with a ton of unused svgs in their markup.

**Comment by Luehrsen** [comment]
By the way, it shows the responsibility of the WordPress project that this showed up on the Facebook/Meta Newsroom: 

https://about.fb.com/news/

![Bildschirmfoto 2022-03-08 um 09 45 40](https://user-images.githubusercontent.com/1105871/157200464-afdfbb6e-350e-48d0-b909-8ba8b1c2bbb9.png)

**Comment by irfan-cloudnix** [comment]
> Hi, @ChadReitsma
> 
> Can you try the following snippet for 5.9.1?
> 
> ```
> remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
> ```
> 
> Also related PR - #39018

Can someone please help me to know where to place this code exactly! I recently upgraded Wordpress version and facing the same problem.

**Comment by akkis** [comment]
> > Hi, @ChadReitsma
> > Can you try the following snippet for 5.9.1?
> > ```
> > remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also related PR - #39018
> 
> Can someone please help me to know where to place this code exactly! I recently upgraded Wordpress version and facing the same problem.

Paste this line at the end of `functions.php` file of the active theme.

**Comment by irfan-cloudnix** [comment]
> > > Hi, @ChadReitsma
> > > Can you try the following snippet for 5.9.1?
> > > ```
> > > remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also related PR - #39018
> > 
> > 
> > Can someone please help me to know where to place this code exactly! I recently upgraded Wordpress version and facing the same problem.
> 
> Paste this line at the end of `functions.php` file of the active theme.

I tried but it didn't work for me, instead
I have added return to the whole wp_global_styles_render_svg_filters function and it worked for me as of now.

Thanks for the reply & help

**Comment by slr1979** [comment]
Anyone able to give me some feedback on my related topic ? -  https://github.com/WordPress/gutenberg/issues/39054 It seems like the duotone implementation is causing a lot of headaches in more ways than this. Fortunately, the suggested fixes in these comments did work for my dev site and live site (which had duotone excess code for weeks!). I still don't understand why duotone svg and filters have been moved away from the elements and into the footer. Is it for speed or something? Anyone care to enlighten me on the changes from 5.8 to 5.9.1. They do seem a little odd.

**Comment by ajlende** [comment]
Would some folks here be able to test out Gutenberg v12.8.0-rc.1? It includes a fix for this. Please test that your themes colors and gradients all work as expected as well. The plugin zip can be found at the bottom of the release page: https://github.com/WordPress/gutenberg/releases/tag/v12.8.0-rc.1

**Comment by Garconis** [comment]
TL;DR. Why is this junk in the body of every page?

**Comment by retlehs** [comment]
@Garconis

1. there was a bug
2. it was fixed already in the gutenberg plugin, and the fix is coming to core soon
3. there are different workarounds/fixes you can apply to your own install depending on which version of wp you are using.

fix for wp 5.9 via @mkkeck https://github.com/WordPress/gutenberg/issues/38299#issuecomment-1025520487

fix for wp 5.9.1 via @Mamaduka https://github.com/WordPress/gutenberg/issues/38299#issuecomment-1049011521

**Comment by lwangdu** [comment]
I am still seeing the issue. I am using WP 5.9.2, Gutenber plugin 12.8.1 and theme TT2 version 1.1
![Screen Shot 2022-03-24 at 9 07 30 AM](https://user-images.githubusercontent.com/24829573/159960943-71c24e96-6aa1-43b2-a9de-c720a5355901.png)

**Comment by skorasaurus** [comment]
> I am still seeing the issue. I am using WP 5.9.2, Gutenber plugin 12.8.1 and theme TT2 version 1.1 ![Screen Shot 2022-03-24 at 9 07 30 AM](https://user-images.githubusercontent.com/24829573/159960943-71c24e96-6aa1-43b2-a9de-c720a5355901.png)
@lwangdu 

A couple issues: 
[the TT2 theme explicitly includes its own gradients in theme.json](https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwentytwo/theme.json#L37) 

You also need to include: `"defaultDuotone": false`, under settings.color in your theme.json to disable the default duotones as well. 

Note: if you have duotones enabled, they'll always load on the page; even on pages that do not contain duotones on them.

Conditionally rendering the duotone code only when the page contains duotones has not yet been implemented yet.  

Note that exact syntax to disable the default duotones is subject to change as noted in the discussion at https://github.com/WordPress/gutenberg/pull/38681#issuecomment-1065112908

**Comment by pimschaaf** [comment]
Repeating @Mamaduka's suggestion like @retlehs, as it's already been buried a bit in here.

`remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );`

It seems to fix my issue with WP 5.9.2 where, for me, there are still duotone filter SVGs bloating the HTML just after the _opening_ `<body>` tag. 

What a hot mess this is.
My two cents worth of sentiment: developing custom themes with Gutenberg and updates remains a bad experience for me and, instead of inspiring me to contribute, it rather makes me consider WordPress alternatives with a roadmap that actually leads me forward.

**Comment by skorasaurus** [comment]
was reopened by https://github.com/WordPress/gutenberg/pull/39966

As I understand from conversation , the intention of reverting the initial fix was to fix the code so that the default duotones are only loaded they are being used on a page. 
Thoughts are at https://github.com/WordPress/gutenberg/pull/38681#issuecomment-1083439131 and https://github.com/WordPress/gutenberg/pull/38681#issuecomment-1080874389

Personally, my thoughts about this are at https://github.com/WordPress/gutenberg/pull/38681#issuecomment-1065197280

**Comment by ajlende** [comment]
tl;dr summary for why this was re-opened since there was a lot of discussion to read through in #38681

1. Block patterns expect a consistent set of styles to be present in a site.
2. Because of this, `defaultPalette` and `defaultGradients` were designed to _not_ disable style generation. They only disable the UI.
3. A new option, `defaultDuotone` should be consistent with the behavior of the other two options to avoid more confusion.

---

> the intention of reverting the initial fix was to fix the code so that the default duotones are only loaded they are being used on a page.

It'll be a partial solution until we can update the whole global styles infrastructure to be aware of the styles used on a page and only render out those styles.

The current interim plan is to only render default duotone SVGs if `filter.duotone` is set in theme.json `styles`. This should cover many cases, but it doesn't solve the root cause of the issue.

**Comment by cbirdsong** [comment]
> 1. Block patterns expect a consistent set of styles to be present in a site.

For custom theme dev the block pattern directory is disabled in almost every case, and the only block patterns present have been _specifically_ designed for the theme. Custom theme dev is also a place where extra boilerplate SVG and CSS adding to page weight is extremely noticeable and most unwelcome. There should be a way to opt out of this extra stuff, at the _very least_. A more ideal solution might be checking to see if `should_load_remote_block_patterns` returns true, and only outputting core boilerplate colors/gradients/etc if it is.

**Comment by sitoexpress** [comment]
It funny to read some comments around the related threads where people talk about duotone filters as something really really really needed, while common/practical sense should suggest that's a niche feature only few people around the world will ever use, thus it shouldn't be in core... But hey, it takes all sorts to make a world!

**Comment by Luehrsen** [comment]
> It funny to read some comments around the related threads where people talk about duotone filters as something really really really needed, while common/practical sense should suggest that's a niche feature only few people around the world will ever use, thus it shouldn't be in core... But hey, it takes all sorts to make a world!

It always baffles me, that such an opinionated design feature made its way into core and is not considered plugin territory. To be fair: Duotone Filters for agency designs were dead the second they hit WordPress core.

**Comment by mkkeck** [comment]
Remove the duotone stuff from core and put into a Twenty theme or a plugin would resolve this issue.
I'm really frustrated, why to be forced to live with a bloated site for feature which perhaps only five people arround the world may use it.

Taking focus on stability, better docs and naming convention would be more usefull instead tons of buggy, experimental, page bloating and page breaking features.

**Comment by vralle** [comment]
I don't think it's because of the duotone. A few lines of code for duotone in the markup of site are not something critical. There are common problems. This is Gutenberg redundancy. Instability. The cost of maintaining each release of WP, as well as plugins for Gutenberg, is already difficult to estimate. All this affects the fatigue of both developers and customers. Instead of best practices, Gutenberg are forcing me to consider moving away from WordPress. This happened with W3C in 2020. And this is happening now with customers who need stability and speed. Maybe bloggers are happy with Gutenberg, but I don't have those clients.

**Comment by mkkeck** [comment]
@vralle yes its true. But I personally think, Gutenberg had potential before all the FSE and experimental stuff. 

Now with each new release, there were new features added, instead of making current features stable and of course more configurable. Docs are incomplete or confusing. Then things, which are only used by really less users went into core, but often without opt out and which are better in plugins or theme based functions.

At the moment, nearly every WordPress update breaks any customer theme, plugin or whole websites. That's not acceptable!

The other point is forcing global styles across all themes, for compatibility reasons, which makes more trouble instead. That's also the result of bad paradigm and naming convention, specially e.g. for CSS classnames and error-prone code and configure duplication. As an example, it does not make sense to configure social services twice, once for Javascript (for the block editor) and once for PHP (for the block renderer), which shares nearly same data.

Personally I think, there's no person, which controls and manages all these things. No qualitity checks are made, no discussions which features make sense to put to core and which are better in a plugin or theme based function.

Perhabs, it would really better, to remove all the theme specific things from the core and put these to the Twenty themes. Keep the core small, simple, and stable. Not everybody needs all features and not everbody needs FSE, Duotones or Gradients. Make these pluggable and of course disabled by default. Maybe releasing a full blown version with tons of features and a extra developer friendly minimal version could be an option. But what I'm really missing is a LTS version, where only bugs and security issues should be fixed.

**Comment by badfeather** [comment]
**Proposal:** For each new custom feature added to Gutenberg, like duotone, SVG filters, etc., it should either be opt-in, or there should be a simple, _consistent_ PHP hook to disable the feature via `add_theme_support()`, similar to `add_theme_support( 'disable-custom-gradients' );` type calls, and to pass empty arrays for default editor presets, similar to `add_theme_support( 'editor-gradient-presets', [] );`.

So, for example, something like `add_theme_support( 'disable-custom-duotone' );` and `add_theme_support( 'editor-duotone-presets', [] );`.

**Comment by james0r** [comment]
Another reason why I think Wordpress should release a Classic Editor version. More and more needed all the time to strip Gutenberg from our custom themes.

**Comment by mkkeck** [comment]
> Another reason why I think Wordpress should release a Classic Editor version. More and more needed all the time to strip Gutenberg from our custom themes.

The problem is not Gutenberg at all, but the philosophy, how and why features are developed and get into the WordPress core. I think there should be change.
All theme specific stuff and junk should be removed from core to the Twenty-××× themes. It's really frustating, that with nearly every release of WordPress (core), the core is bloated and junked with things, these would be better in themes and plugins.
It's a shame, that this stuff and junk is often experimental, really bad documented and often enabled by default but without hooks to disable or remove. But the biggest shame is, that this stuff and junk bloats the core and generated front end and often breaks themes and websites.

**Comment by vralle** [comment]
WP 6.0-RC4. I still see duotone filters in markup. I don't know how to comment on this.

`remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );`
This hook does the trick.

**Comment by sakurawald** [comment]
> 

Duotone is a silly feature.

**Comment by sakurawald** [comment]
> 

They have fixed the bug that the duotone feature can be disabled.

**Comment by JiveDig** [comment]
I'm testing 6.0-RC4 and am also confused on why I'm stilling seeing the SVG's. I'm using our hybrid theme (no theme.json but we use blocks for content).

Here's some weird findings to someone that hasn't followed this issue very closely...


1. I can add a custom duotone filter, but I don't have any predefined duotones registered.

<img width="977" alt="image" src="https://user-images.githubusercontent.com/540990/170055509-9e7b20f1-5b65-4c53-b83e-92aa186612c2.png">

2. If I remove the SVG's via @K85's `remove_action` code [above](https://github.com/WordPress/gutenberg/issues/38299#issuecomment-1134032371), the filter/effect still displays correctly on the front end via the following inline CSS from core.

![CleanShot 2022-05-24 at 10 09 21](https://user-images.githubusercontent.com/540990/170056288-e67f7582-1278-4fe0-9e2d-7136f3afa15e.jpeg)

I guess I plan to remove these SVG's but I'm totally lost now. Can someone explain to me what they are used for and how I can make use of them via blocks so I can see them in action?

**Comment by sakurawald** [comment]
> WP 6.0-RC4. I still see duotone filters in markup. I don't know how to comment on this.
> 
> `remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );` work.

I'm in WP 6.0-RC4, actually, all the approches above are invalid for me.

**Comment by vralle** [comment]
@JiveDig, I see three questions at once.
If we are talking about the default duotone svg-s in the markup, then the hook above helped me. Now in the final version of WP6.0
If your research is about dirty code...
When you use duotone or block, Gutenberg uses the principle of fail-safe for block styles. The block styles will be added to the global styles when you use core block and don't use compiled styles.
If we say that there are still no tools to disable redundant functionality, then I have not yet found a solution.
All three questions above fit into the WordPress philosophy.

**Comment by CreativeDive** [comment]
@K85 Already tested with WP 6.0 stable?

The SVG tags are still there. No filter or action is removing the SVG tags. Do you have any hint for me to solve this issue?

**Comment by CreativeDive** [comment]
OK, now I have figured out what was wrong here. In my case the Gutenberg plugin is activated and the following action is not working:

`remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );`

If the Gutenberg plugin is active, use this action to remove SVGs:

`remove_action( 'wp_body_open', 'gutenberg_global_styles_render_svg_filters' );`

And for both cases:

```
remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
remove_action( 'wp_body_open', 'gutenberg_global_styles_render_svg_filters' );
```

**Comment by sakurawald** [comment]
> OK, now I have figured out what was wrong here. In my case the Gutenberg plugin is activated and the following action is not working:
> 
> `remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );`
> 
> If the Gutenberg plugin is active, use this action to remove SVGs:
> 
> `remove_action( 'wp_body_open', 'gutenberg_global_styles_render_svg_filters' );`
> 
> And for both cases:
> 
> ```
> remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
> remove_action( 'wp_body_open', 'gutenberg_global_styles_render_svg_filters' );
> ```
This is the only correct solution for Wordpress 6.0 RC4
Yes, i kept the gutenberg plugin activated and ONLY add the `remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );`, so the SVGs are still there.
After i add `remove_action( 'wp_body_open', 'gutenberg_global_styles_render_svg_filters' );`, all the duotone SVGs disappear.

**Comment by mkkeck** [comment]
> OK, now I have figured out what was wrong here. In my case the Gutenberg plugin is activated and the following action is not working:
> 
> `remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );`
> 
> If the Gutenberg plugin is active, use this action to remove SVGs:
> 
> `remove_action( 'wp_body_open', 'gutenberg_global_styles_render_svg_filters' );`
> 
> And for both cases:
> 
> ```
> remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );
> remove_action( 'wp_body_open', 'gutenberg_global_styles_render_svg_filters' );
> ```

Oh no what a shame, dear developers! Why different filters to disable the same thing? It's getting worse and worse.

**Comment by sitoexpress** [comment]
@mkkeck That's obvious if you're using the Gutenberg plugin and NOT the built-in core version, because of the need to differentiate the two things

**Comment by mkkeck** [comment]
> @mkkeck That's obvious if you're using the Gutenberg plugin and NOT the built-in core version, because of the need to differentiate the two things

That makes it not better.
The problem is, that there are things pushed to the core, which are really better placed in the Twenty-××× themes or in a seperate plugin.

**Comment by vralle** [comment]
> Oh no what a shame, dear developers! Why different filters to disable the same thing? It's getting worse and worse.

I missed the moment when WordPress started using principles.

**Comment by spencer-j** [comment]
Hello 
`remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );`
works in WP 6, 
BUT
theme.json should be the place where i turn this features on and off, and this DOESN'T WORK like mentioned here:
[https://fullsiteediting.com/lessons/remove-settings-in-theme-json/](https://fullsiteediting.com/lessons/remove-settings-in-theme-json/)
AND by default every bloating not 100% used stuff should be turned off.

**Comment by CUBICinfinity** [comment]
FTR, I'm liking the block themes concept; it just needs work. We need to keep the raw WP installation as clean as possible.
`remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );` works to remove the duotone svgs for me on 6.0, but it's also breaking fonts and font styles. For now, I'm going to leave the SVGs on my site alone. I don't have time to be supporting the removal. Hopefully it'll be fixed up in a new version of WP.

**Comment by mwaterous** [comment]
I can't wrap my head around why anyone thought this, of all things, was a thing that should be automatically enabled, let alone in core at all.

The ethos used to be "that belongs in a plugin or a theme!" and you had to prove prove prove why it belonged in core. Now we have duotone SVGs in core.

**Comment by Generosus** [comment]
Good Day!

Thank you, everyone. I read all of your comments. 

I agree. The added WP 5.9 global inline CSS and SVG duotone code (i.e., files) should be deleted from WP Core and, instead, added to WP's "Twenty-Something" theme.

Meanwhile, please know that we're using the code snippet provide below to remove the added code. It works well for us. However, the second parameter, `remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters')`, causes our page sliders to bounce violently under our current environment (Avada, SG Optimizer activated, Combine JS Files activated). We could not identify the file(s) causing the sliders to bounce, so we simply commented out (disabled) the second parameter below.

```
/* Disable Gutenberg Inline CSS Styles and SVG Duotone Filters from Header (WordPress 5.9+) */
function wp_deregister_styles() {
wp_dequeue_style( 'global-styles' ); // Remove Inline CSS Styles
remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' ); // Remove SVG Duotone Filters
}
add_action( 'wp_enqueue_scripts', 'wp_deregister_styles', 100 `);
```

If any of you would like to confirm the above, that would be great. A fix would be appreciated as well :)

I am hoping the awesome developers at WordPress will fix this soon. How 'bout a quick patch until the next major revision is released?

Thank you!

**Comment by patrickwc** [comment]
Others have already pointed this out but I wanted to reiterate the point. It seems very weird to me that the decision to output an extra ~260lines of HTML worth of SVG filters on every page, regardless of whether duotone's have been disabled in theme.json (or even if a block is used on a page!) was allowed to go live and still hasn't been fixed after months. No wonder a lot of WP sites rank badly on pagespeed insights. This is bad for hosting costs, users data, page speed scores and green credentials. 

This filter removed it for me, thanks @vralle.

```remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );```

The SVGs were being output just after the opening <body> tag for me - ~260 lines of HTML added to every page completely unnecessarily!

**Comment by ocean90** [comment]
As noted in [this blog post](https://geoffgraham.me/how-to-remove-the-svgs-wordpress-injects-for-duotone-support/), you can now set `"duotone": null` in [`theme.json`](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/) which removes the default duotone palette, inline SVGs, and the CSS custom properties.
Though, the JSON schema validation will report a type error but it works™.

**Comment by straightvisions-matthias-bathke** [comment]
> As noted in [this blog post](https://geoffgraham.me/how-to-remove-the-svgs-wordpress-injects-for-duotone-support/), you can now set `"duotone": null` in [`theme.json`](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/) which removes the default duotone palette, inline SVGs, and the CSS custom properties. Though, the JSON schema validation will report a type error but it works™.

_Tested and can confirm that this works now._

**Update**
Unfortunately, "duotone":null results in
`javascript error "TypeError: Cannot reat properties of null (reading 'default') in react-dom.min.js`
on Site Editor

![image](https://user-images.githubusercontent.com/4689792/202465039-77f2ed3d-b9ad-44c8-ac5a-095693a4f7ec.png)

**Comment by kevinlo123** [comment]
`{
    "version": 2,
    "settings": {
        "color": {
            "defaultPalette": false,
            "defaultGradients": false,
            "duotone": [],
            "defaultDuotone": false,
            "palette": [
                {
                    "name": "Dark Blue",
                    "slug": "dark-blue",
                    "color": "#233142"
                },
                {
                    "name": "Yellow",
                    "slug": "yellow",
                    "color": "#facf5a"
                },
                {
                    "name": "Blue",
                    "slug": "blue",
                    "color": "#0170ca"
                },
                {
                    "name": "Red",
                    "slug": "red",
                    "color": "#ff5959"
                },
                {
                    "name": "Green",
                    "slug": "green",
                    "color": "#4f9da6"
                },
                {
                    "name": "White",
                    "slug": "white",
                    "color": "#FFFFFF"
                },
                {
                    "name": "Grey",
                    "slug": "grey",
                    "color": "#f2f2f2"
                },
                {
                    "name": "Purple",
                    "slug": "purple",
                    "color": "#8c6cde"
                }
            ]
        }
    }
}
`

My theme.json that worked for anyone running into this.

**Comment by ngdangtu-vn** [comment]
> WP 6.0-RC4. I still see duotone filters in markup. I don't know how to comment on this.
> 
> `remove_action( 'wp_body_open', 'wp_global_styles_render_svg_filters' );` This hook does the trick.

Mine WP version is `6.1.1`, and it works if I put it in `functions.php` of my theme. Thanks for the tip.

**Comment by 1ucay** [comment]
Hello, I removing all --wp prefix. Im not using blocks.css :)

    add_action( 'wp_enqueue_scripts', 'core_gutenberg_wp_enqueue_scripts', 11 );
    function core_gutenberg_wp_enqueue_scripts() {
        if ( ! is_admin() ) {
            global $wp_styles;
            $gs = $wp_styles->registered['global-styles']->extra['after'];
            wp_styles()->add_data( 'global-styles', 'after', '' ); 
            foreach( array( 'pale-pink', 'vivid-red', 'luminous-vivid-orange', 'luminous-vivid-amber', 'light-green-cyan', 'vivid-green-cyan', 'pale-cyan-blue', 'vivid-cyan-blue', 'vivid-purple', 'very-light-gray', 'cyan-bluish-gray', 'very-dark-gray' ) as $color ) {
                $gs[0] = preg_replace('/.has-' . $color . '-(background|border)-color{.*?}/i', '', $gs[0] );
                $gs[0] = preg_replace('/.has-' . $color . '-color{.*?}/i', '', $gs[0] );
                $gs[0] = preg_replace('/--wp--preset--color--' . $color . ':.*?;/i', '', $gs[0] );
            }
            foreach( array( 'vivid-cyan-blue-to-vivid-purple', 'light-green-cyan-to-vivid-green-cyan', 'luminous-vivid-amber-to-luminous-vivid-orange', 'luminous-vivid-orange-to-vivid-red', 'very-light-gray-to-cyan-bluish-gray', 'cool-to-warm-spectrum', 'blush-light-purple', 'blush-bordeaux', 'luminous-dusk', 'pale-ocean', 'electric-grass', 'midnight' ) as $color ) {
               $gs[0] = preg_replace('/--wp--preset--gradient--' . $color . ':.*?;/i', '', $gs[0] );
               $gs[0] = preg_replace('/.has-' . $color . '-gradient-background{.*?}/i', '', $gs[0] );
            }
            wp_add_inline_style( 'global-styles', str_replace( array( '.wp-', '--wp', 'wp-' ), array( '.', '', '' ), implode( '', $gs ) ) );
            //wp_dequeue_style( 'global-styles' ); // Remove theme.json
        }
    }

**Comment by ajlende** [comment]
We've attempted at a fix for this in https://github.com/WordPress/gutenberg/pull/49103 which should make it into the Gutenberg 15.5 release.

The `wp_global_styles_render_svg_filters` is no longer used to render the SVGs so the workaround is no longer needed.

All global styles are handled by duotone block supports now instead of being part of the global styles stylesheet. It was a rather involved change, so please open an issue if you run into any unexpected side-effects of moving these styles around.

**Comment by renepf** [comment]
I wrote a little script, and added it to the functions.php file of my child theme. For me this worked. Just be careful, in case you add this to your core theme that it won't get updated. So you may want to write an extra script to call this as a php file when not using a childtheme.

```php
add_action( 'wp_footer', 'remove_wp_filters', 10 );
function remove_wp_filters() {
    ?>
    <script type="text/javascript">
        jQuery(document).ready(function($) {
            $('svg').filter(function() {
                return this.innerHTML.indexOf('wp-duotone') !== -1;
            }).remove();
        });
    </script>
    <?php
}
```
