### ISSUE TITLE
Gutenberg breaks on the 5.0 alpha

### ISSUE THREAD

**Issue by hedgefield** [WordPress/gutenberg#3865]
I can't add a new Gutenberg post anymore in the 5.0 builds, I get an unknown error. Opening existing posts, same story. `Attempt Recovery` does nothing.

![screen shot 2017-12-08 at 10 43 22 2](https://user-images.githubusercontent.com/6073772/33762085-908307dc-dc0b-11e7-9481-0e47316f2b3f.png)

Gutenberg 1.8.1, WP 5.0-alpha-42378 (and the nightly before that), VVV

**Comment by hedgefield** [comment]
Seems fixed in 1.9.

**Comment by thebugfixnet** [comment]
This kind of crash is back with Wordpress 5.0-alpha-42808 + Gutenberg Version 2.3.0 

`[sprintf] property "selectedCount" does not exist
h @ react-dom.min.3583f8be.js:162
g @ react-dom.min.3583f8be.js:160
t @ react-dom.min.3583f8be.js:167
x @ react-dom.min.3583f8be.js:166
batchedUpdates @ react-dom.min.3583f8be.js:169
cc @ react-dom.min.3583f8be.js:26
jc @ react-dom.min.3583f8be.js:35`
