### ISSUE TITLE
position: fixed via style.css breaks appearance in Editor

### ISSUE THREAD

**Issue by ponderboy** [WordPress/gutenberg#39596]
In header template part:
`<!-- wp:site-logo {"width":64} /-->`

in Stylesheet: 
`.custom-logo-link {
	    position: fixed;
}`

Now in the Editor it shows up scaled up.

**Comment by karmatosed** [comment]
Hi @ponderboy in order to help a little more would you be able to give some more details as to your issue please? Once you have we can try and find that ideal help.

**Comment by ponderboy** [comment]
Its looks like this on the front end:

![screenshot-hp local-2022 03 30-19_31_43](https://user-images.githubusercontent.com/5340556/160896501-3a3c3af5-a17a-4f9e-99c6-bc263d998ab3.png)


and like this in FSE:

![screenshot-hp local-2022 03 30-19_33_15](https://user-images.githubusercontent.com/5340556/160896859-7c7cffcf-157f-4047-aa6a-59ea62606a4b.png)

I've added a site-logo block to my header template part.

```
<!-- wp:group -->
    <div class="wp-block-group">
        <!-- wp:site-logo {"width":64,"className":"logo-signet"} /-->
    </div>
<!-- /wp:group -->
```

I then styled it via stylesheet:

```
.custom-logo-link {
	--logo-v: 1rem;
	--logo-h: 1.75rem;
	padding: var(--logo-v) var(--logo-h);
	background-color: var(--wp--preset--color--primary);

// this makes the logo appear huge in FSE
	position: fixed; 
}
```

**Comment by adamwoodnz** [comment]
After debugging this I believe the issue is that the image previewed in the editor has no width applied. ie. the `64` in the settings has no effect. When I add `width: 64px` to the `.custom-logo-link` styles the issue is fixed, even with `position: fixed`. Maybe add that to your stylesheet?

![Screen Shot 2022-05-31 at 2 20 27 PM](https://user-images.githubusercontent.com/1017872/171080099-54bb08d2-688d-42fc-af14-24ca2a27ff36.png)

**Comment by adamwoodnz** [comment]
Please close if this resolves your issue

**Comment by ponderboy** [comment]
No, it still shows up in different size. I use css clip-path for the link. That might be a reason. Guess it's sort of an edge case. Working with wordpress always gives me hurdles when I leave the common way of design / structure the system uses. 

Lot's of other little issues with the wp editor in relation to the new theming (block mark up). But at the moment I have no time to investigate deeper into these. I'm sorry.
