### ISSUE TITLE
WP 6.0 Beta 3 – new post defaults to 404-template

### ISSUE THREAD

**Issue by kebbet** [WordPress/gutenberg#40675]
### Description

When creating a new post, the sidebar UI says Template: 404. When saving, the UI is updated with the correct template (Single Post). This is a change from beta 2.

If i save the post as a draft, the UI still says Template: 404, but leaving the editor and returning gives me the correct template (Single Post).

### Step-by-step reproduction instructions

1. Install WP 6.0 beta 3.
2. Use theme 2022.
3. Go to editor, to create a new post. 
4. Look at the sidebar panel ”Template”.
5. Save post
6. Observe the panel ”Template” and see the change.

### Screenshots, screen recording, code snippet

Before saving
<img width="310" alt="bild" src="https://user-images.githubusercontent.com/11491369/165693402-0d5bf4c0-e320-43b9-85c6-b7aa1c1d5a78.png">

After saving.
<img width="326" alt="bild" src="https://user-images.githubusercontent.com/11491369/165693500-b1c5922f-dad4-4dbc-bcfd-3f7d82f6b3b5.png">

### Environment info

- WP 6.0 beta 3, no Gutenberg plugin.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by Mamaduka** [comment]
I was able to reproduce the issue.

The `__experimentalGetTemplateForLink` resolver returns 404 for new posts. The resolution works correctly when the Gutenberg plugin is active.

```
GET https://trunk.test/?p=24&_wp-find-template=true 404
```

**Comment by ndiego** [comment]
I am able to reproduce this as well.

**Comment by petitphp** [comment]
I was able to reproduce the issue.

In [`gutenberg_resolve_template_for_new_post`](https://github.com/WordPress/gutenberg/blob/trunk/lib/compat/wordpress-5.9/block-template.php#L288) we are modifying the `wp_query` to allow the `auto-draft` post status when the URL contain the param "_wp-find-template".

The callback will only run for the first wp_query which trigger the `pre_get_posts` filter and it remove itself immediately. Multiple queries can run during a request and the main query is not always the first to run. The query being modified is not the correct one and the website return a 404 for the post.

Checking for the main query before doing any modifications fix the issue.
<img width="1037" alt="Capture d’écran 2022-05-04 à 00 09 30" src="https://user-images.githubusercontent.com/158572/166574567-3133e6e7-00b0-433b-90fa-b801405738bf.png">

I don't really know why the issue doesn't occur when the gutenberg plugin is active.

I can work on a PR with the fix for Gutenberg. Since this code has been integrated with WordPress core we would need to apply the fix there to.

**Comment by carlomanf** [comment]
Is there any chance of dropping the "_wp-find-template" workaround and implementing this properly through the REST API? Besides potentially solving this issue, it could have other benefits such as suggestion number 3 at #39767.

**Comment by Mamaduka** [comment]
@ndiego, there's PR with a possible fix - #40799. It would be nice to get someone from the core team to review it.

**Comment by SergeyBiryukov** [comment]
Since the associated PR has been merged and backported to WP core, I think this should be resolved now.

**Comment by nuekleer** [comment]
Still having this problem in core.  Have to have the plugin installed to fix.

**Comment by SergeyBiryukov** [comment]
The fix in core will be released with 6.0.1, [planned for July 12](https://make.wordpress.org/core/2022/06/25/wordpress-6-0-x-release-team-and-6-0-1-schedule/).

**Comment by gilsonviana** [comment]
I'm still getting this error.

**Comment by petitphp** [comment]
Hi @gilsonviana,

This issue was raise and fixed (hopefully) during the 6.0 release. Since this issue is closed, can you open a new one with a small description of your problem, reproduction steps and environment infos (PHP and WP version, Gutenberg plugin installed or not etc.) so it can be looked at by the triage team and other contributors ?

Thank you !

**Comment by gilsonviana** [comment]
I just had to upgrade the plugin. Sorry about that.
