### ISSUE TITLE
Style Variations previews on hover not properly reflecting fonts

### ISSUE THREAD

**Issue by annezazu** [WordPress/gutenberg#40699]
### Description

The style variations previews on hover aren't properly rendering the fonts for TT2. 

### Step-by-step reproduction instructions

1. Open Appearance > Editor.
2. Open the Styles interface.
3. Select "browse styles"
4. Hover over the various style options and notice the previews are slightly off. 

### Screenshots, screen recording, code snippet

What it looks like:

https://user-images.githubusercontent.com/26996883/165821137-4b87f008-76b9-4bc6-8596-97510180875e.mov

What it should look like:

![Zx1_3_1RCi](https://user-images.githubusercontent.com/77359364/165822972-5c946f50-edad-48fc-b3d8-cb9e23bc7771.gif)

Specifically, the font that says “default” should be a lot thinner and delicate-looking (source serif light) and the blue option should be quite robust and round (DM sans). 

### Environment info

- WordPress 6.0 beta 3
- TT2

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by ndiego** [comment]
@annezazu in testing this, the font weights are getting pulled in. I think the problem is that the actual font is not getting applied. It is just defaulting to `serif`, `sans-serif`, and `monospace`. 

Edit:
Yup, I confirmed using [Frost](https://github.com/wpengine/frost). The actual font is not getting pulled in. Just defaulting to browser defaults.

**Comment by annezazu** [comment]
Thanks so much for confirming and testing.

**Comment by glendaviesnz** [comment]
Have tested this and it looks like the issue is that the specified fonts are not being loaded into the preview iFrame which is why it is falling back to browser defaults. 

For example, by default, in the Pink style `Courier` is rendered for me instead `IBM Plex Mono`:
<img width="305" alt="Screen Shot 2022-05-03 at 1 14 50 PM" src="https://user-images.githubusercontent.com/3629020/166391386-c370f579-781b-4757-9ef9-68be839465b1.png">

but if I manually inject the Google font `<links>` into the preview iframe in `packages/edit-site/src/components/global-styles/preview.js` the correct font is rendered:

<img width="316" alt="Screen Shot 2022-05-03 at 1 13 13 PM" src="https://user-images.githubusercontent.com/3629020/166391460-1f38e489-d323-466d-ac9f-64dfe609a368.png">

So looks like it is a matter of working out how to get the correct font loading details added to the header of those preview iframes.

**Comment by glendaviesnz** [comment]
@scruffian  - this issue was mentioned in one of the comments [on the PR you did to load them for the site editor ](https://github.com/WordPress/gutenberg/pull/40262). Have you looked at all at how to load them in the preview iframes?

**Comment by glendaviesnz** [comment]
@annezazu  It appears that currently there is no way to access the theme.json custom font settings in the js, they are only enqueued server side. Plumbing through this detail in the global styles settings in the frontend in order to inject them into the preview iframes is probably going to be more of a 'new feature' type job, than an RC quick bug fix, so this potentially needs to be punted to 6.1. That is my view anyway, someone else may see a quick fix for it that I am overlooking.

**Comment by annezazu** [comment]
Sounds good! Thank you for digging in. Heads up @ndiego.

**Comment by ndiego** [comment]
Thanks @annezazu, this has been moved over to the [6.0.1 Project Board](https://github.com/orgs/WordPress/projects/31) and we can triage from there.

**Comment by annezazu** [comment]
Somewhere along the way, this was fixed. Testing in 6.6 beta 3. Closing out:

https://github.com/WordPress/gutenberg/assets/26996883/1a66f801-2ec6-43ee-85a6-504acffbac3e

**Comment by justintadlock** [comment]
@annezazu - I'm still seeing this issue on WP and Gutenberg trunk. Here's an example from Twenty Twenty-Four with the Ember style variation. It uses the "Jost" font, which is not correctly applied (in typography previews or the content canvas) because the font file is never loaded:

![tt4-wrong-font-previews](https://github.com/WordPress/gutenberg/assets/1816309/94306a53-f816-4d53-9b3d-b288c773a0dc)

This is easy to miss if you have Jost installed on your computer (note that its "A" character should have a pointy tip, not a flat tip, so this one is easy to spot).

Also, @getdave mentioned that this issue was not fully yet addressed and needed a ticket here: https://github.com/WordPress/gutenberg/issues/59818#issuecomment-2017659311

I can open a new ticket that's more broad, but I wasn't sure if you considered this one specific to Twenty Twenty-Two or wanted to reopen. Mostly, I just don't want to lose track of this issue since both this and #59818 have been closed, which I think are the only two tickets that mention this ongoing bug.

**Comment by justintadlock** [comment]
Noting that there's an existing ticket, so no need to reopen this one: https://github.com/WordPress/gutenberg/issues/59965
