### ISSUE TITLE
Comments Query Loop - Empty Markup

### ISSUE THREAD

**Issue by bgardner** [WordPress/gutenberg#41957]
### Description

When a page or post has comments disabled (Discussion > Allow comments not checked in sidebar), the Comments Query Loop Block outputs empty markup on the front end:

![image](https://user-images.githubusercontent.com/486261/175778922-126e032a-b63a-4905-adbd-35037f64068e.png)

Because of blockGap, this causes a 30px empty space on pages and posts.

### Step-by-step reproduction instructions

1. Publish a page or post
2. Uncheck Allow comments
3. View front end

### Environment info

WordPress 6.0, with or without Gutenberg 13.5 active.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by cbravobernal** [comment]
As we will add server-side rendering to this block so we can fix the translation.

Could be a possible solution to remove the `save.js` file and let PHP handle the conditional render if comments are allowed or not?

**Comment by ndiego** [comment]
> Could be a possible solution to remove the save.js file and let PHP handle the conditional render if comments are allowed or not?

I just took a look at this. Switching to server-side render as you suggest should solve this. The current [index.php file](https://github.com/WordPress/gutenberg/blob/d00d939f8b505f332f57d9862f00d85419178d74/packages/block-library/src/comments/index.php#L43-L45) already accounts for the situation when comments are disabled. 

@c4rl0sbr4v0 is there already an issue/PR for the translation fix?

**Comment by cbravobernal** [comment]
Hi @ndiego !

[We did the server side rendering fix for 6.0.1 ](https://github.com/WordPress/wordpress-develop/pull/2921), so I guess we can now address this fix.

**Comment by ockham** [comment]
I still get the empty `<div />` when disabling Comments for a post:

![image](https://user-images.githubusercontent.com/96308/185398843-6b1b5eec-f6a3-4738-b68a-4ced12a2bc2d.png)

> I just took a look at this. Switching to server-side render as you suggest should solve this. The current [index.php file](https://github.com/WordPress/gutenberg/blob/d00d939f8b505f332f57d9862f00d85419178d74/packages/block-library/src/comments/index.php#L43-L45) already accounts for the situation when comments are disabled. 

I think the checks are only preventing the empty `<div />` in legacy mode, as we're [rendering the static block](https://github.com/WordPress/gutenberg/blob/d00d939f8b505f332f57d9862f00d85419178d74/packages/block-library/src/comments/index.php#L27-L30) otherwise (and before that "are comments disabled?" check).

I guess we can tweak the logic a bit to render nothing at all if comments are disabled (even if we're not in legacy mode).

**Comment by ockham** [comment]
Okay, I got a fix. I'll file a PR.
