### ISSUE TITLE
Inserter: CORS issue hovering Cover, and loop issue when hovering a few blocks

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#44320]
### Description

When opening the inserter and hovering the Cover block, the console will read a CORS error. When inserting an empty paragraph and then hovering a few blocks, at some point, an endless error loop will occur.

### Step-by-step reproduction instructions

CORS issue

1. Open the inserter
2. Make sure your browser console is open
3. Hover the Cover block.

Observe a cors issue in the console:

```
FastAverageColor: security error (CORS) for resource https://s.w.org/images/core/5.3/Windbuchencom.jpg.
Details: https://developer.mozilla.org/en/docs/Web/HTML/CORS_enabled_image
outputError @ index.esm.js:325
index.esm.js:327 DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at FastAverageColor.getColor (http://local-wordpress.local/wp-content/plugins/gutenberg-symlink/build/block-library/index.min.js?ver=a938d7c6d7de7e89499c:630:39)
    at FastAverageColor.getColorAsync (http://local-wordpress.local/wp-content/plugins/gutenberg-symlink/build/block-library/index.min.js?ver=a938d7c6d7de7e89499c:594:31)
    at http://local-wordpress.local/wp-content/plugins/gutenberg-symlink/build/block-library/index.min.js?ver=a938d7c6d7de7e89499c:13368:34
    at Tj (http://local-wordpress.local/wp-content/plugins/gutenberg-symlink/build/vendors/react-dom.min.js?ver=6.1-alpha-54226:179:399)
    at unstable_runWithPriority (http://local-wordpress.local/wp-content/plugins/gutenberg-symlink/build/vendors/react.min.js?ver=6.1-alpha-54226:24:26)
    at Za (http://local-wordpress.local/wp-content/plugins/gutenberg-symlink/build/vendors/react-dom.min.js?ver=6.1-alpha-54226:73:8)
    at Ra (http://local-wordpress.local/wp-content/plugins/gutenberg-symlink/build/vendors/react-dom.min.js?ver=6.1-alpha-54226:178:368)
    at gf (http://local-wordpress.local/wp-content/plugins/gutenberg-symlink/build/vendors/react-dom.min.js?ver=6.1-alpha-54226:161:497)
    at http://local-wordpress.local/wp-content/plugins/gutenberg-symlink/build/vendors/react-dom.min.js?ver=6.1-alpha-54226:73:230
    at unstable_runWithPriority (http://local-wordpress.local/wp-content/plugins/gutenberg-symlink/build/vendors/react.min.js?ver=6.1-alpha-54226:24:26)
```

Secondly, to reproduce the loop error:

1. Make a linebreak or insert an empty paragraph
2. Open the inserter with the console open
3. Hover a few blocks at random, including the Cover block

Eventually an error loop will begin in the console.

```
inject.js:13 Uncaught TypeError: Cannot read properties of null (reading 'readyState')
    at inject.js:13:17
```

### Screenshots, screen recording, code snippet

GIF showing CORS issue:

![cors issue](https://user-images.githubusercontent.com/1204802/191470108-05b113a0-811a-4059-a123-c20ce36c9172.gif)

GIF showing loop issue:

![loop issue](https://user-images.githubusercontent.com/1204802/191470133-9700e304-8e3e-402b-a802-9fa3f8a14176.gif)

Screenshot of console:
<img width="485" alt="Screenshot 2022-09-21 at 11 28 43" src="https://user-images.githubusercontent.com/1204802/191470186-6c5bdce8-60d3-4968-b76c-82462d1c1269.png">

### Environment info

Trunk, Mac, Chrome.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by ajlende** [comment]
The CORS issue may have been solved by https://github.com/WordPress/gutenberg/pull/44552. I can't seem to reproduce the error in trunk right now.

**Comment by ajlende** [comment]
And I can't seem to reproduce the error loop either. It isn't as clear what was causing that error, but if it was related to the CORS issue, that may have been fixed by https://github.com/WordPress/gutenberg/pull/44552 too.

**Comment by miksansegundo** [comment]
This CORS error is still reproducible when hovering the cover block on the inserter:

https://user-images.githubusercontent.com/1881481/216907217-ea6bdc3c-e4fd-4d43-ab01-ba8d2a0be32c.mov

The same CORS error occurs when the editor loads a pattern with a cover block. I traced the errored request initiator and found that it is coming from [getColorAsync()](https://github.com/WordPress/gutenberg/blob/a84db76d51617ed3e3a518ce8ffeb0ad038b13b1/packages/block-library/src/cover/edit/use-cover-is-dark.js#L44) in [useCoverIsDark](https://github.com/WordPress/gutenberg/blob/a84db76d51617ed3e3a518ce8ffeb0ad038b13b1/packages/block-library/src/cover/edit/use-cover-is-dark.js#L32). 

Related to https://github.com/WordPress/gutenberg/pull/44175
