### ISSUE TITLE
[WP 6.1] Fluid and spacing settings in theme.json are lost when theme export

### ISSUE THREAD

**Issue by ya123123** [WordPress/gutenberg#44546]
### Description

When I use theme export, 

* settings.spacing.spacingScale.steps -> field is lost
* settings.spacing.spacingSizes.slug -> quotation is lost
* settings.typography.fluid -> field is lost

### Step-by-step reproduction instructions

1. Use WP 6.1 nightly and Twenty Twenty Three without gutenberg plugin
2. Go to the site editor.
3. Select Three dots menu > Export

### Screenshots, screen recording, code snippet

spacing before export:
![n1631](https://user-images.githubusercontent.com/114547428/192886474-6d3d6142-7eed-4a4d-a7fc-4e3effe7c320.png)

spacing after export:
![n1632](https://user-images.githubusercontent.com/114547428/192886485-3fb14454-6e26-45eb-8669-5d69128b2072.png)

fluid before export:
![n1633](https://user-images.githubusercontent.com/114547428/192886493-bc1d86bd-9e7f-4cfa-a12c-3c701ed96336.png)

fluid after export:
![n1634](https://user-images.githubusercontent.com/114547428/192886503-9f0c1c8d-cfc9-42f5-bd35-03bbdd4b8bb6.png)

### Environment info

WP 6.1 (latest nightly via Beta Tester plugin), instawp install
TT3 included in WP 6.1 nightly.
Gutenberg plugin deactivated

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by glendaviesnz** [comment]
I have a fix for the spacingScale value [here](https://github.com/WordPress/gutenberg/pull/44555), still trying to work out the fluid font value as it isn't related and only happens in 6.1, not GB trunk

**Comment by glendaviesnz** [comment]
The fluid flag was a different issue and a [potential fix for it is here](https://github.com/WordPress/wordpress-develop/pull/3362)

**Comment by ramonjd** [comment]
Thank you @mayuge3 Also reported in https://core.trac.wordpress.org/ticket/56684 Props to you!

**Comment by ya123123** [comment]
Thank you!

I'm not familiar with technical details, so I opened [another issue #214 at TT3](https://github.com/WordPress/twentytwentythree/issues/214), is it related to this issue's fluid problem...?

**Comment by dream-encode** [comment]
I was looking to merge this, but I want to make sure this comment by @tellthemachines is addressed in the final PR:  
https://github.com/WordPress/gutenberg/pull/44555#pullrequestreview-1124645012

**Comment by glendaviesnz** [comment]
> but I want to make sure this comment by @tellthemachines is addressed in the final PR

thanks @dream-encode,  I will look at the issue with casting to ints on a separate PR as it will be a bit trickier to resolve and test.

**Comment by ndiego** [comment]
@glendaviesnz I just wanted to confirm that this issue is all set, given the merged and closed PRs. I noticed the issue still had the Backport label, so I wanted to double check before I removed it. Thanks!

**Comment by glendaviesnz** [comment]
Thanks @ndiego, have removed the label now.
