### ISSUE TITLE
Block Theme Editor is not working without the theme.json file

### ISSUE THREAD

**Issue by jnfDev** [WordPress/gutenberg#46557]
### Description

I'm currently learning about Block themes. I tried to create my first "hello world" Block Theme like this:

`mytheme/style.css`
```
/*
 Theme Name: My Theme
 Author: jnfdev
*/

```

`mytheme/templates/index.html`
```
<!-- wp:paragraph -->
<p>Hello World/p>
<!-- /wp:paragraph -->
```

The theme appears on the **Appearance/Themes** page as it should, and I can activate it, as usual; however, when I try to go to the **Appearance/Editor**, I get a white screen (see video below)

https://drive.google.com/file/d/1KEK6nO-JgqogTggAeTZjL44b89xptif7/view?usp=share_link

As you can see in the video, whenever I add an empty `theme.json` file, the problem goes away.

Why do I need to add the `theme.json`  if the [documentation says](https://developer.wordpress.org/themes/block-themes/block-theme-setup/) it's optional? Also, it doesn't mention that we must add the `theme.json` file for the Editor to work properly.

Is this a bug? or just the documentation is outdated?

### Step-by-step reproduction instructions

1. Create a new "hello-world" block theme with the following files: `style.css, templates/index.html`
2. Go to **Appearance/Editor**
3. See white screen
4. Then, add an empty `theme.json` file in the theme.
5. Go to **Appearance/Editor** everything is working just fine now

### Video step-by-step on how to reproduce the error
https://drive.google.com/file/d/1KEK6nO-JgqogTggAeTZjL44b89xptif7/view?usp=share_link

### Some screenshots 
<img width="2555" alt="Screenshot 2022-12-14 at 3 51 32 PM" src="https://user-images.githubusercontent.com/36063539/207711304-ae5ae776-d8ef-437b-a819-50b8a5b563ca.png">
<img width="2559" alt="Screenshot 2022-12-14 at 3 51 10 PM" src="https://user-images.githubusercontent.com/36063539/207711315-5c332b3d-15f5-44c6-ba9d-a57210472df2.png">

### Environment info

 - WordPress version: 6.1.1
 - PHP version: 7.4.33

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by DaisyOlsen** [comment]
I've confirmed that this was not an issue in 6.0 but is in 6.1 w/o Gutenberg plugin active. The issue seems resolved with 6.1 + Gutenberg plugin.

**Comment by kathrynwp** [comment]
Thanks for testing, @DaisyOlsen!

@jnfDev Would you like to test this by activating the latest Gutenberg plugin to see if that resolves the issue? (The standalone Gutenberg plugin includes fixes that will be included in the next WordPress release.)

There's also a missing angle bracket here before the second `p`, but that is unrelated to the issue you're running into. :)

`<p>Hello World/p>`

Let me know how it goes!

**Comment by jnfDev** [comment]
Hi @kathrynwp 

I can confirm that the issue gets solved when I install/activate the Gutenberg plugin. It's good to know a fix is coming; thank you for the great work.

Concerning the missing <, yeah, I noticed it, but it was just a typo when I was creating the issue, in the actual code is ok (see images attached), although thank you for noticing it; good eye 😄

**Comment by Mamaduka** [comment]
The issue was fixed in #46073 and will be part of the WP 6.1.2 release (probably early next year).

**Comment by carolinan** [comment]
@Mamaduka This is still a problem with 6.2 alpha, and I don't think there is going to be a 6.1.2 release? Just highlighting so it is not missed.
