### ISSUE TITLE
Converting post with images to blocks changes source of all images

### ISSUE THREAD

**Issue by morganestes** [WordPress/gutenberg#4694]
## Issue Overview
When converting a blog post created in "Classic Editor" to use blocks, the `img src` attribute value changes on all images to that of the first image in the post.

## Steps to Reproduce (for bugs)
1. Create or import a post, in the current editor, adding multiple images.
2. Activate Gutenberg and edit the post.
3. Click the "Convert to blocks" link in Gutenberg editor.
4. Observe all the images are now the same, with the source attribute pointing to another image in the post.
5. Refresh the page without saving, and the original images reappear. (hooray!)

Chrome 63, MacOS 10.12.6, Local by Flywheel dev environment with SSL. WordPress 4.9.2, Gutenberg 2.1.0.

## Expected Behavior
Images should be the same as they were, just converted to individual image blocks.

## Current Behavior
Images are converted to blocks, but their `src` attribute changes.

## Screenshots / Video
Post editor before block conversion:
![images-before-conversion](https://user-images.githubusercontent.com/110755/35448541-2b7c6306-0280-11e8-9718-0049ec066adc.png)

Post editor after block conversion:
![images-after-conversion](https://user-images.githubusercontent.com/110755/35448547-2e76579c-0280-11e8-8829-283d4fc0dbce.png)

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by spencerfinnell** [comment]
Related/Duplicate: #4449

**Comment by jorgefilipecosta** [comment]
This issue should be fixed in master now.

**Comment by ferremek** [comment]
Hi there, I have this exact issue and for me it is not resolved.

**Describe the bug**
I have converted all classic editor to Gutenberg Blocks and this all works as expected. However when I change the thumbnail size of the image it changes to a totally unrelated other image from the media library. This bug does not occur on the new posts that are made with Gutenberg, only the converted posts.

**To reproduce**
Steps to reproduce the behavior:
1. Go to a converted post
2. Click on an image
3. In the right sidebar select a different image thumbnail in the dropdown.
4. See error, the image changes to another image from the library.

**Expected behavior**
When you change the thumbnail size I expect it to stay the same image and only change the thumbnail size.

**Desktop:**
 - OS: Mac OS X 10.15.4
 - Browser: Firefox
 - Version: 75.0

**Versions:**
- WordPress v5.4
- ACF Content Analysis for Yoast SEO v2.3.0
- Advanced Custom Fields PRO v5.7.9
- Polylang Pro v2.6.10
- SearchWP v3.1.11
- Yoast SEO v13.4.1
