### ISSUE TITLE
Publish panel covered by edit panel

### ISSUE THREAD

**Issue by mrfatguy** [WordPress/gutenberg#52991]
### Description

For past 2+ weeks publish panel (Preview + Publish button) are covered with edit panel on nearly every edit:

![Screenshot 2023-07-26 185454](https://github.com/WordPress/gutenberg/assets/2903392/645320cd-7cff-403d-92c9-128ffa351004)

![Gutenberg 02](https://github.com/WordPress/gutenberg/assets/2903392/a6b78291-c2e4-45c6-af3c-de81fb801060)

If this is already reported then please mark this one as a duplicate.

I searched the net and the Gutenberg GitHub Issues and found nothing. I was expected that rolling back or fixing that blatantly obvious bug will take a bit less time than 2+ weeks.

Happens on both new posts (with "Publish" button covered) and in edits (with "Update" button covered). But the issue is not reproducible every time. Happens a bit randomly.

I am currently using version 16.2.1 of Gutenberg.

### Step-by-step reproduction instructions

1. Start editing or updating new post.
2. Observe "Publish" or "Update" button being covered in approx. 90%.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

No

**Comment by Mamaduka** [comment]
I believe this was fixed in #52722.

**Comment by trejder** [comment]
#52722 says about fix being shipped withing 6.3 RC2. I am currently on Version 16.3.0 and the bug remains.

I don't know how to compare `6.3 RC2` to `16.3.0`. Could I be still affected by this bug. Or should I not?

**Comment by jordesign** [comment]
Hey @trejder - I see in that issue that the fix will be included in Gutenberg 16.4 as well. So that's something that will be available in about 2 weeks.

Even though that version is not yet released - I'll close this issue as the problem is resolved, and just coming soon.
Thanks for the report :)
