### ISSUE TITLE
Featured image doesn't display height in edit view if it's an .svg file

### ISSUE THREAD

**Issue by neilorangepeel** [WordPress/gutenberg#5477]
## Issue Overview

If you enable .svg uploads and set one as a featured image the image container collapses and it doesn't know the correct height.

Tested on version 2.3.0

## Steps to Reproduce (for bugs)

1. Enable svg uploads
2. Upload .svg image
3. Set as featured image

## Expected Behavior

Display image at full height within featured image section.

## Current Behavior

Displays image at full height but container height is 0. Image is overflowing.

## Screenshots / Video

<img width="1439" alt="screen shot 2018-03-07 at 14 42 42" src="https://user-images.githubusercontent.com/3746751/37098957-16734b12-2217-11e8-969d-226c959dcc0c.png">

**Comment by Kluny** [comment]
@jorgefilipecosta, I'm interested in working on this if you haven't started already.

**Comment by jorgefilipecosta** [comment]
sure @Kluny feel free to work on it. Thank you for your interest 👍

**Comment by Kluny** [comment]
@jorgefilipecosta, I've pushed a fix for this. Will you review it for me?

**Comment by jorgefilipecosta** [comment]
Hi @Kluny thank you for submitting the PR, another contributor already reviewed it :)

**Comment by gbwashleybrown** [comment]
Hi,

Currently using WP Version 5.0.3 and this is still an issue.

What version is this likely to be corrected?

**Comment by adamziel** [comment]
It seems like there is a related discontinued PR here: https://github.com/WordPress/gutenberg/pull/5577

Reviving it would likely fix this issue.

**Comment by smwcollege** [comment]
I'm not able to replicate this on my site. Here is a rather complex SVG set as a featured image:
![image](https://user-images.githubusercontent.com/42584667/109204689-a9e16f00-7773-11eb-9751-cab1a9a744a3.png)

I wonder if this is an issue with the file not having a set viewbox, because the SVGs I tested all had viewboxes set.

**Comment by rafaelgalani** [comment]
I'll try to reproduce it... 
If I'm able to do it, then I'll work on it using https://github.com/WordPress/gutenberg/pull/5577 as reference.

**Comment by aaronrobertshaw** [comment]
I was able to replicate this issue using a clean install of WP 5.8 and the latest Gutenberg version. 

It didn't appear to be directly related to the presence or not of a `viewbox`, `width` or `height` attribute in the SVG markup.

The post's feature image gets [rendered within a `ResponsiveWrapper`](https://github.com/WordPress/gutenberg/blob/165b92a974cf7f2b508a11dac36cf0da9556d136/packages/editor/src/components/post-featured-image/index.js#L157-L166). That relies on the [image's height and width being able to be determined](https://github.com/WordPress/gutenberg/blob/165b92a974cf7f2b508a11dac36cf0da9556d136/packages/editor/src/components/post-featured-image/index.js#L62-L97). In the `PostFeaturedImage` component, it isn't able to reliably collect a natural height or width for an SVG. This leads the `ResponsiveWrapper` assigning an `undefined` value to the `paddingBottom` style.

One very rough option could be for the responsive wrapper to check for an `undefined` value and in that case set padding bottom to something like `100%`. It worked for me quickly hacking around. 

| Before | After |
|---|---|
| <img width="388" alt="Screen Shot 2021-08-26 at 2 38 16 pm" src="https://user-images.githubusercontent.com/60436221/130906162-f2ecef0d-b0ba-4a6b-9b41-2d41f7f86bcd.png"> | <img width="372" alt="Screen Shot 2021-08-26 at 3 33 12 pm" src="https://user-images.githubusercontent.com/60436221/130906484-bcc65de6-9501-41b3-b006-81de54d65ae0.png"> |

I'm not sure what the consequences of such a change would be. Unfortunately, I don't have the bandwidth at the moment to continue working on this. Happy to assist or review a PR for anyone else that picks this up.

**Comment by Thelmachido** [comment]
I tested this on the most recent Gutenberg version 13.7.3, on the Twenty Twenty-Two theme. 

I wasn't able to replicate the issue as shown in the screenshots below:

On this image, I add the SVG featured image. 

<img width="413" alt="Untitled 2" src="https://user-images.githubusercontent.com/41231764/181707762-6ccc85c2-81b7-4f4a-8e9f-b9b82b3a4e95.png">

The featured image section is looking as expected, the image isn't overflowing as before. 

<img width="297" alt="Untitled" src="https://user-images.githubusercontent.com/41231764/181707727-ebe689a4-431a-4070-a807-2f60e0291628.png">

Closing this issue for now.
