### ISSUE TITLE
Publish date DatePicker displays previous date in calendar

### ISSUE THREAD

**Issue by singhpaul** [WordPress/gutenberg#56844]
### Description

When selecting a publish date:

* Calendar defaults to highlighting yesterday's date
* Clicking on a date inputs the next day's date into the text fields above
* The calendar starts on Sunday, even though "Week Starts On" is set to Monday

### Step-by-step reproduction instructions

Unable to reproduce consistently. Please see screen video. 

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/7103245/fa388361-3589-4ecd-81b4-e7c1be1d2284

### Environment info

WordPress 6.4.1 
Windows 11
Chrome and Edge

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by bhavik001** [comment]
Hello @singhpaul 
Can you assign me this issue.
I am interested in working on it.

**Comment by singhpaul** [comment]
> Hello @singhpaul Can you assign me this issue. I am interested in working on it.

Hi @bhavik001, apologies if I'm missing something but I don't think I can assign to you. I believe it has to be a reviewer but please let me know if there's a way I can assign and I'm happy to do so.

**Comment by bhavik001** [comment]
I think from the Assignees from the right hand column above label you can add me.
Hello @jordesign can you assign me this issue?

**Comment by singhpaul** [comment]
@bhavik001 We're now able to reliably replicate the issue. Please see my comment on Issue #47698: 

https://github.com/WordPress/gutenberg/issues/47698#issuecomment-1922675389

I can't re-open that issue so leaving this open for now.

**Comment by im3dabasia** [comment]
Thank you @singhpaul @bhavik001 for working on this issue

I believe this issue is solved and the issue can be closed now . I have attached the current behaviour in this comment. 


https://github.com/user-attachments/assets/6544395e-d4d6-4e40-bf7e-932c7d23dc6c

cc: @jordesign , @t-hamano @Mamaduka

**Comment by singhpaul** [comment]
@im3dabasia I'm afraid the issue still persists. See attached screen recording. 

https://github.com/user-attachments/assets/685ac047-2431-416f-9580-cfa403582b34

**Comment by t-hamano** [comment]
I haven't been able to reproduce this problem yet, but as @singhpaul says, it might be related to the timezone setting.

**Comment by singhpaul** [comment]
> I haven't been able to reproduce this problem yet, but as [@singhpaul](https://github.com/singhpaul) says, it might be related to the timezone setting.

HI @t-hamano. To reproduce, the client OS time has to be in another time zone date than WP. For instance, in our test, WP is on US east coast time so I am able to reproduce after 8pm NY time by setting my local machine's TZ setting to London (because it will then be midnight in London and thus tomorrow's date relative to NY).

**Comment by t-hamano** [comment]
I suspect this issue has been fixed by #73444. @singhpaul, If the issue has not yet been resolved, we can reopen this issue.
