### ISSUE TITLE
Columns adding block only available on left and right seems stuck

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#5772]
I was using Chrome and got the following interesting formatting happening using the column block and 2 columns.

![2018-03-23 at 22 15](https://user-images.githubusercontent.com/253067/37855594-fae0c8ec-2ee7-11e8-885d-e1c41c184087.png)

Once I added blocks I could only add to one side:

![2018-03-23 at 22 17](https://user-images.githubusercontent.com/253067/37855605-09a9dae4-2ee8-11e8-97c0-570ba32fb490.png)

**Comment by karmatosed** [comment]
This still happens on trunk

![2018-04-05 at 17 25](https://user-images.githubusercontent.com/253067/38378682-57fb9e7c-38f6-11e8-9615-f9ff19683c31.png)

**Comment by aduth** [comment]
In my testing, this occurs only when focus is not within the second column when using the inserter.

**Comment by SuperGeniusZeb** [comment]
This is still happening in `master` and Gutenberg 3.2.

**Comment by ZebulanStanphill** [comment]
Still happening in Gutenberg 3.6.2 and `master`.

**Comment by aduth** [comment]
For clarity's sake, could we get a simple set of reproducible steps here?

Based on the re-reading of the original comment, I'm left to wonder if this is the difference of the default appender being visible only after non-default block (i.e. won't show if the last in a column is Paragraph, which is expected, same as in top-level editor).

Given my previous response, I'm assuming I did find some legitimate issue to exist, though in revisiting it's not exactly obvious what's wrong / expected, and more information could help make this issue actionable.

**Comment by ZebulanStanphill** [comment]
@aduth Inserting a block places a block in the same context as where the text cursor is at. If my text cursor is in a block outside of the Columns block, using the inserter on the right column will insert a block outside of the Columns block. If my text cursor is in the left column, using the inserter on the right column will insert a block in the left column.

**Comment by designsimply** [comment]
I was unable to reproduce the problem using the following testing steps:

1. Add a columns block with at least one paragraph block with content in each column.
1. Add a gallery block below the columns block.
1. Place the cursor in the paragraph block in the left column.
1. Click the sibling inserter for the paragraph block in the right column.

<strong>Result:</strong> I was able to use the sibling inserter to add a new nested block without any trouble. ([34s](https://cloudup.com/cMmRzDy1rHQ))

![nested-block-sibling-inserter-test](https://user-images.githubusercontent.com/1119271/45651659-47a6bf00-ba8f-11e8-8517-1ed41a955e49.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14967&action=edit running WordPress 4.9.8 and Gutenberg 3.9.0-rc.1 using Firefox 62.0 on macOS 10.13.6.</sup>

**Comment by ZebulanStanphill** [comment]
@designsimply The issue does not occur with the sibling inserter. You need to use the inserter that appears in the placeholder automatically created below a non-Paragraph block. Also, your text cursor has to be in the other column when you use the inserter. Please re-open.

**Comment by designsimply** [comment]
Apologies for not seeing your last comment earlier @ZebulanStanphill! Things have changed a bit since your last reply, so I re-tested just now using WordPress 5.0.3 and no active plugins using the following steps (with the testing steps modified per your note) and I think the issue has been resolved.

1. Add a columns block with at least one paragraph block with content in each column.
1. Add a gallery block below the columns block.
1. Place the cursor in the paragraph block in the right column (this will create a default block below it).
1. Place the cursor in the paragraph block in the left column.
1. Click the inserter on the default block below the paragraph block in the right column.

![5772-11s](https://user-images.githubusercontent.com/1119271/52376023-55e57f80-2a1e-11e9-8786-97ef28e209a7.gif)

I'd be happy to loop back around to test again if you spot anything off in the testing steps!

**Comment by ZebulanStanphill** [comment]
@designsimply I am also unable to reproduce the issue in Gutenberg 5.0 on WordPress 5.0.3, so it looks like the issue has been fixed! :smile:

**Comment by Taigistal** [comment]
**Describe the bug**
I still have the same problem in Wordpress 5.1 (without any plugins, Theme: Twenty Nineteen).
I try to add a block to the right column and it appears in the left column.

**To Reproduce**
1. add a columns block to the page.
2. click on the right cross in the right column and add a heading block. ( both columns are empty until here)

![Image of the Bug](http://public.crioco.com/fehler-2-wrong-solumn.gif)

**Expected behavior**
the heading block should be insert in the right colum.


When i first click in the right column and then try to add a block with the plus at the right side of that column, everything works well.
