### ISSUE TITLE
NavigatorButton has double border on focus state

### ISSUE THREAD

**Issue by madhusudhand** [WordPress/gutenberg#61621]
### Description

When NavigatorButton is added inside ItemGroup, the last item gives double order on focus.

<img width="852" alt="image" src="https://github.com/WordPress/gutenberg/assets/1935113/3edfd0d6-3dd4-473d-ab95-f990890ffca1">

### Step-by-step reproduction instructions

* Navigate to typography section in global styles menu
* In Elements item group, change the focus state of last item.
* Observe that there is double border.

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by mirka** [comment]
Reproduced in Storybook. Last item is `<Item as={ NavigatorButton } path="/foo" />`. Not sure if we should call it a double border, but we can see the button styles (border radius) taking precedence.

https://github.com/WordPress/gutenberg/assets/555336/fbff2b77-3eef-47cc-bedc-6e13437568e0

**Comment by im3dabasia** [comment]
Thank you for the issue @madhusudhand .

@mirka , I see that this issue is no longer present in the reported location. We can close this issue as the focus-visible is applied correctly. Sharing a video reference down below.

https://github.com/user-attachments/assets/42ff78ef-4b79-4af5-86bb-b9ba9f83927c

cc: @t-hamano

**Comment by mirka** [comment]
Nice that the issue in the reported location was fixed 🎉 

The repro case I [posted](https://github.com/WordPress/gutenberg/issues/61621#issuecomment-2121292750) doesn't seem resolved yet. Maybe it's a completely different thing — I haven't seen a visual of what the originally reported issue was.

This is how I'm reproducing it in Storybook, by the way:

```diff
diff --git a/packages/components/src/item-group/stories/index.story.tsx b/packages/components/src/item-group/stories/index.story.tsx
index 845843d243..f5531b7772 100644
--- a/packages/components/src/item-group/stories/index.story.tsx
+++ b/packages/components/src/item-group/stories/index.story.tsx
@@ -8,6 +8,7 @@ import type { Meta, StoryFn } from '@storybook/react';
  */
 import { ItemGroup } from '../item-group/component';
 import { Item } from '../item/component';
+import { NavigatorButton } from '../../navigator/navigator-button/component';
 
 type ItemProps = React.ComponentPropsWithoutRef< typeof Item >;
 
@@ -58,8 +59,8 @@ Default.args = {
 			},
 			{
 				children: 'Anchor item',
-				as: 'a',
-				href: 'https://wordpress.org',
+				as: NavigatorButton,
+				path: '/foo',
 			},
 		] as ItemProps[]
 	 ).map( mapPropsToItem ),
```

**Comment by t-hamano** [comment]
I can still reproduce this issue. Note that this issue needs to be tested in the `:focus` state, not the `:focus-visible` state.

Additionally, this issue does not seem to be related to the `NavigatorButton` component. You should be able to reproduce this issue on Stoybook without making any changes.

https://wordpress.github.io/gutenberg/?path=/story/components-experimental-itemgroup--default

You can emulate the `:focus` state using your browser's developer tools or by holding down the primary touchpad key on the button.

![Image](https://github.com/user-attachments/assets/e851c1f0-de5e-4b14-b9c1-db6a93c44f09)

Here's the style that's causing this issue:

https://github.com/WordPress/gutenberg/blob/59a230c1e692ed78d0abfebce3c6ff5b429c1a4b/packages/components/src/item-group/styles.ts#L68-L70

I don't know why only the focus state is excluded, but making the following changes seems to solve the problem.

```diff
--- a/packages/components/src/item-group/styles.ts
+++ b/packages/components/src/item-group/styles.ts
@@ -65,7 +65,7 @@ export const separated = css`
                border-bottom: 1px solid ${ CONFIG.surfaceBorderColor };
        }
 
-       > *:last-of-type > *:not( :focus ) {
+       > *:last-of-type > * {
                border-bottom-color: transparent;
        }
 `;
```

**Comment by im3dabasia** [comment]
Correct @t-hamano. The border was removed previously only when the state was not focused. i.e., other than when the item is focused, the border was removed. To correct this, we need to remove the border styling for all pseudo events and not just target `:not( :focus )`. 

I'll shortly raise a PR for this fix and we can discuss there.
