### ISSUE TITLE
Color Presets: Unexpected scroll to color presets when selecting a style variation

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#61841]
### Description

Related to https://github.com/WordPress/gutenberg/issues/61213 and possibly introduced in https://github.com/WordPress/gutenberg/pull/61334

While testing the new color presets in `trunk`, I noticed that if you select one of the color presets and then go to select a style variation, the first time you click the style variation, the site editor's browse mode side bar unexpectedly scrolls down to the already selected color preset.

### Step-by-step reproduction instructions

1. Open the site editor
2. In the left hand sidebar of the browse mode, navigate to Styles
3. Scroll down and select one of the color presets
4. Then, scroll up and click on one of the style variations
5. Notice that the sidebar scrolls down to the already selected color preset, instead of focus being placed on the style variation that the user clicked on
6. If you then attempt to click on the style variation a second time, it works as expected

### Screenshots, screen recording, code snippet

https://github.com/WordPress/gutenberg/assets/14988353/47f298fb-83de-4727-9359-7ec8f57710ed

### Environment info

- WP 6.5.3
- Gutenberg trunk
- macOS
- Google Chrome

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by amitraj2203** [comment]
Hi @andrewserong, I think the bug mentioned in the issue is fixed in this [PR](https://github.com/WordPress/gutenberg/pull/61617). I also tried to replicate it but couldn't. Let me know if I'm missing anything.

**Comment by andrewserong** [comment]
Thanks @amitraj2203, but after re-testing trunk after #61617, this issue still appears to be present:

https://github.com/WordPress/gutenberg/assets/14988353/42a1b4fe-123f-4b20-b174-a1b7835bb5f3

In case it helps, I found it easier to reproduce on a smaller window size, e.g. a 13" laptop screen, where the Styles sidebar scrolls quite a long way. On larger screen sizes where both the style variations and color palettes are visible at the same time, the scroll issue doesn't appear to occur (I suspect because the elements are all visible?), so it's just when the other components aren't visible where the unexpected scroll seems to be happening.

**Comment by richtabor** [comment]
I'm pretty sure this existed before https://github.com/WordPress/gutenberg/pull/61334. Let's target a fix for 6.6.

**Comment by Sourav61** [comment]
Hey @andrewserong, I tested the above issue and can reproduce this issue But I wanted to confirm whether the scroll on changing the style variation is expected or not.

I think that updating the style variation should automatically scroll to the colour palette associated as the next step so that we can confirm the colour palette and typography to be used

I will be working on the fix for the focus not being placed correctly on the style variation that the user clicked on.

**Comment by andrewserong** [comment]
Thanks for the ping!

> But I wanted to confirm whether the scroll on changing the style variation is expected or not.

I believe the scroll is unexpected. In this case we can't know whether a user wishes to continue toggling through the style variations, so to me it would be unexpected to be scrolled immediately to another part of the UI as these screens aren't explicitly step based.

**Comment by scruffian** [comment]
I can no longer reproduce this, can you @andrewserong ?

**Comment by andrewserong** [comment]
Thanks for the ping! I can still reproduce this @scruffian. It can be a little tricky to reproduce if your theme only has a couple of presets as the issue only occurs when there's enough style variations and palettes that the buttons are out of view. To reproduce / emulate a theme that has a lot of presets, I've reduced my browser window down so that it's very short. I'm testing on Chrome on macOS. Here's how it's looking for me:

### Gutenberg `trunk`

https://github.com/WordPress/gutenberg/assets/14988353/d758b424-470b-41c3-b6a0-658e8d6e497a

### WP 6.6 RC 3 (without Gutenberg)

https://github.com/WordPress/gutenberg/assets/14988353/5db4f737-8a8f-4885-a462-8ca05d6e378b

In the above screengrabs, I select a style variation, then click the color palette and then it snaps back up to the style variation. But it also happens the other way around for me if I select a color palette first and then go to select a variation, it'll snap down to the color palette.

**Comment by ramonjd** [comment]
I can confirm that it still occurs. 

It's weird - almost as if the currently-focussed element doesn't like focus being taken. I have to click twice to "force" it.


https://github.com/user-attachments/assets/f3bf4142-42c0-4d9c-8821-47cbd7919cd4

I removed all the [focus-related props](https://github.com/WordPress/gutenberg/blob/41804e186cbfbbee75f7cfb1b53ca617c9c26625/packages/edit-site/src/components/global-styles/variations/variation.js#L85-L85) on the variations and it didn't change much.

**Comment by ramonjd** [comment]
Note: it's not occurring in Firefox for me.

Maybe related to: https://issues.chromium.org/issues/40846304

**Comment by carolinan** [comment]
Same, can reproduce in Chrome but not Firefox.

Copying this over from the TT5 isssue:

I can reproduce this.
Windows 11, chrome, 6.7-beta3-59248, with or without Gutenberg.

I select a style variation at the top of the list for example "Noon".
Then I scroll down to the bottom. Now, "Noon" is no longer visible in the list of theme theme style variations.
I click on the color palette called "Sunrise".
The color palette is not selected. Instead, when I click on the palette, it seems focus is only moved to the "Noon" theme variation.
Clicking on the color palette a second time applies the palette.

https://github.com/user-attachments/assets/40a32470-6597-4a15-8b8e-8b3f7e13e7f9

**Comment by cbravobernal** [comment]
Punting this issue to 6.8, as it seems it has not been fixed yet nor is a regression.

**Comment by scruffian** [comment]
I was going to look into a fix for this, I still can't reproduce in Chrome or Firefox, sorry!

**Comment by t-hamano** [comment]
As I commented [here](https://github.com/WordPress/gutenberg/issues/65686#issuecomment-3222329492), I can't reproduce the problem anymore. This might be related to [the redesign of the Styles screen](https://github.com/WordPress/gutenberg/pull/65619) 🤔

Is anyone still able to reproduce this issue with the latest Gutenberg?

https://github.com/user-attachments/assets/5a21aedd-654c-450c-ab2a-fdaa786d89f2

**Comment by andrewserong** [comment]
Thanks for the update @t-hamano, after re-testing I can't reproduce the issue. Switching presets feels pretty responsive to me while running the Assembler theme and latest Gutenberg, and I'm not seeing any unexpected scroll behaviour, either.

I'll close this out.
