### ISSUE TITLE
Missing "Reset" from template part Inspector actions

### ISSUE THREAD

**Issue by richtabor** [WordPress/gutenberg#62604]
You can reset templates from the vertical ellipsis, but not template parts. 

I'd expect to be able to "Reset" template parts, as I can templates. 

As seen on templates: 

![CleanShot 2024-06-16 at 16 07 33](https://github.com/WordPress/gutenberg/assets/1813435/ad768761-b90d-4add-994b-89d3e9166a72)

As seen on template parts: 

![CleanShot 2024-06-16 at 16 01 18](https://github.com/WordPress/gutenberg/assets/1813435/e64c11fd-1fc2-46fc-912c-ea818b8c9028)

**Comment by t-hamano** [comment]
This issue does not exist in WordPress 6.5, so I think it should be fixed in WordPress 6.6.

Screenshot in WordPress 6.5

![reset-template-part](https://github.com/WordPress/gutenberg/assets/54422211/7c87216f-fd37-4092-bd04-fa36f4da4c9b)

**Comment by richtabor** [comment]
Is "Reset" available on template parts' ellipsis menu? It's not with Gutenberg, last I checked.

**Comment by Mamaduka** [comment]
I tested this last night. The issue is still there, and I'll try to fix it.
