### ISSUE TITLE
Zoom out: wide blocks are shrunken

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#63519]
### Description

<img width="1352" alt="image" src="https://github.com/user-attachments/assets/01cc7656-36c5-48e4-b527-a8770bfe68b9">

### Step-by-step reproduction instructions

Open a pattern category from the inserter with the demo content

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

**Comment by stokesman** [comment]
So far I’ve only reproduced this for cover blocks (wide aligned or not) and it looks like it has to do with the styles introduced in #59512. I say that because in the browser, when disabling `display: flex` on `.is-root-container`, I see the width as expected (testing with twenty twenty-four). This probably can affect other blocks or theme styles.

**Comment by mdawaffe** [comment]
This also affects Jetpack map blocks:

edit mode:
<img width="600" alt="edit mode" src="https://github.com/user-attachments/assets/3f1084b7-5bdf-4013-afef-d4f43c6949be">

zoomed-out mode:
<img width="600" alt="zoomed-out mode" src="https://github.com/user-attachments/assets/d5cd31db-b9d1-4c46-84e0-8de6e6a9600d">

I don't understand the relevant CSS models well enough to understand the details, but `flex` changes how widths and heights are calculated, which is going to break different blocks in weird ways.

**Comment by mdawaffe** [comment]
> This also affects Jetpack map blocks

I may have spoken too soon about this, sorry :) The issue with the Jetpack block may be unrelated. I'm still looking into what's happening and will update this ticket when I know more.

**Comment by mdawaffe** [comment]
My confusion stemmed from a difference between the post and site editors. I'm still not completely sure what's going on, but I think it's the following.

In the zoomed out mode of the post editor, there is no `<main>` element, so blocks are children of `.is-root-container`, which has `display: flex`. Blocks don't expect to be flex elements so can break in odd ways.

In zoomed out mode of the site editor, there is a `<main>` (`display: block`) element, so blocks are in their "expected" environment. However, in addition to the `transform: scale()`, the zoomed out editor's layout changes: the width of blocks change as a result of the `border: calc(#{$frame-size} / #{$scale}) solid $gray-300;` [border rule](https://github.com/WordPress/gutenberg/blob/f50e045c1ce75acd026ab760891cd5bf57234fd3/packages/block-editor/src/components/iframe/content.scss#L43C2-L43C59). The contents of the Jetpack map block are dynamically generated based on the block's width and the block listens for resize events to update itself. When the editor's layout changes because of the border rule, the Jetpack map block doesn't know to recalculate its width and regenerate its displayed content.

Perhaps we can ditch the left/right border rule to prevent the layout change?

**Comment by stokesman** [comment]
> Perhaps we can ditch the left/right border rule to prevent the layout change?

That’s definitely something that should be prevented. The border doesn’t have to be removed though, it’s just not currently factored into the zoom out transform so it throws off the layout.

---- 

I noticed that with Twenty Twenty-Four and posts (not pages) in the Post editor, the whole of the post content narrows. It’s the auto margins from `.alignfull` that become filled out with the `body` being a flex container.
<img width="850" alt="image" src="https://github.com/user-attachments/assets/0416e69a-8745-4c00-8094-0414812c41d1">

To me it seems any styling changes to the document’s contents in Zoom Out should be avoided as much as possible and we should look for another way to expand the content area that’s more isolated.

**Comment by richtabor** [comment]
> To me it seems any styling changes to the document’s contents in Zoom Out should be avoided as much as possible and we should look for another way to expand the content area that’s more isolated.

Just for clarity, you're suggesting that the border effect is what's causing the problem?

**Comment by richtabor** [comment]
Also, how do I reproduce this exactly? I'm not seeing the wide cover block on the Gutenberg demo page have this issue: 

https://github.com/user-attachments/assets/85d35768-a182-4ed3-abee-8b986591f252

**Comment by ellatrix** [comment]
I'm no longer seeing it. However, the scaling is now broken. Notice how much the wide block overflows with and without zoom-out. Back in May we fixed the scaling so that the width does not shrink.

|Wider canvas|Shrunken canvas (should be purely scaled, _not_ shrunken|
|-|-|
|![Screenshot 2024-08-05 at 17 18 57](https://github.com/user-attachments/assets/59cb424f-4493-4f71-80a5-44eb03d7ddb4)|![Screenshot 2024-08-05 at 17 19 08](https://github.com/user-attachments/assets/7cb19550-3cb6-4c04-adf0-e6c05fb3334a)|

**Comment by stokesman** [comment]
> Just for clarity, you're suggesting that the border effect is what's causing the problem?

No. The "expand main content area" effect seems to be the cause https://github.com/WordPress/gutenberg/issues/63519#issuecomment-2229547217.

----
I can still reproduce this with Twenty Twenty-Four in the Post editor on a post—**not a page**—with the following markup:
```html
<!-- wp:cover {"dimRatio":50,"isUserOverlayColor":true,"isDark":false,"align":"wide","className":"is-light"} -->
<div class="wp-block-cover alignwide is-light"><span aria-hidden="true" class="wp-block-cover__background has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","textColor":"white","fontSize":"large"} -->
<p class="has-text-align-center has-white-color has-text-color has-large-font-size">Of Mountains &amp; Printing Presses</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:group {"align":"wide","style":{"color":{"background":"#d9edcb"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide has-background" style="background-color:#d9edcb"><!-- wp:paragraph -->
<p>p in widealign group</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

```

Why this happens on posts and not pages seems to be that the Post content block (`.wp-block-post-content`) is `.alignfull` on posts and not pages. Possibly interesting as well is that even if `.alignfull` is added to a page’s Post content block there is no effect. The particular align styles don’t exist on pages—the styles are these:
https://github.com/WordPress/gutenberg/blob/650eb7f21f77dfb884eba606b7a995d5a25c5fff/packages/editor/src/components/visual-editor/index.js#L325-L329

**Comment by richtabor** [comment]
> However, the scaling is now broken. Notice how much the wide block overflows with and without zoom-out. 

Yea, you're right.

**Comment by mdawaffe** [comment]
> Just for clarity, you're suggesting that the border effect is what's causing the problem?

There seem to be multiple issues :) I claim that the border rule is one of them.

The computed width (ignoring `scale()`) of the iframe's body element when using Twenty Twenty-Four:
Edit Mode: 1387px
Zoomed-Out Mode: 1374px <-- Layout change
Zoomed-Out Mode after disabling the `html { border: }` rule: 1387px

(Note that these widths depend on your browser window's width.)

| Edit | Zoomed Out | Zoomed Out with Disabled Border Rule |
|---|---|---|
| <img width="1659" alt="Edit Mode" src="https://github.com/user-attachments/assets/38c3414d-ecf8-40d4-9ae7-f70a779a314c"> | <img width="1659" alt="Zoomed Out Mode" src="https://github.com/user-attachments/assets/662a04e5-4ad2-4885-9b55-b1e833f63f36"> | <img width="1659" alt="Zoomed Out Mode with Disabled Border Rule" src="https://github.com/user-attachments/assets/ec7b063b-3ad6-4131-9d56-408748b677e2"> |

(You can't see much difference in the thumbnails above, but the computed width for each is visible if you zoom in.)

**Comment by stokesman** [comment]
> There seem to be multiple issues :) I claim that the border rule is one of them.

Yes, the border is part of the scaling issue but not part of what this issue is originally about—that some blocks are changing their width relative to others when zoom out is engaged.

**Comment by mdawaffe** [comment]
> some blocks are changing their width relative to others when zoom out is engaged

That's exactly what I'm seeing :) Though if it's better to consider the border issue as a separate, that's cool by me.

**Comment by richtabor** [comment]
@stokesman @mdawaffe is this issue still occurring?

**Comment by mdawaffe** [comment]
@richtabor yes.

**Comment by AhmarZaidi** [comment]
Hey 👋,
I'd like to work on this issue.

Here are some of my observations:

- The issue occurs with `align wide` and `align full` blocks in zoom out mode (align-full cover block example):

  <img width="350" alt="1" src="https://github.com/user-attachments/assets/354cf369-f512-4e4d-969b-caa3c3f82dc2">
  <img width="350" alt="2" src="https://github.com/user-attachments/assets/7a8f2271-50d9-4959-91e3-24792e92ebd1">

    
- The issue doesn’t occur with all the cover blocks (patterns). 
Example: Shrinks when using ‘Centered image with two-tone background color’ block (green & skin color one) but doesn’t shrink when using ‘Heading, Paragraph, Button with Two Images’ (pink one)

- If a pattern that doesn’t have this issue (eg: ‘Heading, Paragraph, Button with Two Images’) is present then other patterns (with the issue) are also fixed (they take expected width). However, I couldn’t find any styling differences b/w those blocks which could cause the issue.
    
  <img width="350" alt="3" src="https://github.com/user-attachments/assets/c0809fd1-cbc5-4c27-9205-9ddc4556a9f4">
  
  <img width="350" alt="4" src="https://github.com/user-attachments/assets/4144d04f-2155-49e5-81d0-171fb99ca8ec">

---

One solution that seems to fix the issue is to simply remove `margin-left: auto; margin-right: auto;`  from `.is-root-container.alignfull` from visual-editor style.
https://github.com/WordPress/gutenberg/blob/650eb7f21f77dfb884eba606b7a995d5a25c5fff/packages/editor/src/components/visual-editor/index.js#L328

Here’s the zoom out view after removing:
- `align wide`
    
  <img width="350" alt="6" src="https://github.com/user-attachments/assets/f0d3f959-9b07-488c-b8eb-7f93ea12d204">

- `align full`
    
  <img width="350" alt="5" src="https://github.com/user-attachments/assets/17087de0-4c65-415d-9a8a-e88dd669e209">
    
    
- Also tested https://github.com/WordPress/gutenberg/issues/63519#issuecomment-2269607090 and it is also fixed.
    - Before removing auto margins (1st normal, 2nd zoom out)
        
    <img width="350" alt="7" src="https://github.com/user-attachments/assets/6ee27061-909f-46c7-9358-0f99b8b69849">
    
    <img width="350" alt="8" src="https://github.com/user-attachments/assets/4ad1cd18-6ae5-4821-a7b8-f2c023947a3e">

        
    - After removing auto margins (in zoom out mode)
        
    <img width="350" alt="9" src="https://github.com/user-attachments/assets/e8536b27-b5c5-46b6-9e51-8861c2af9fb2">

Note: I did remove and test the border rule (https://github.com/WordPress/gutenberg/issues/63519#issuecomment-2257267425) but that doesn't seem to fix this issue.
https://github.com/WordPress/gutenberg/blob/650eb7f21f77dfb884eba606b7a995d5a25c5fff/packages/block-editor/src/components/iframe/content.scss#L43

**Comment by draganescu** [comment]
Howdy @AhmarZaidi can you open a PR so we can test it out and see what other consequences the edits to the styling of the root container have?

**Comment by draganescu** [comment]
@ellatrix @stokesman @mdawaffe  is this still something you can repro on `trunk`? I can't 🤷🏻 including with the markup provided.

**Comment by stokesman** [comment]
Yes, but only in the Post editor on a post (not a page). It seems the theme can make a difference. TT4 is what I was testing with. Adding other blocks/content can make the issue less pronounced or entirely unseen (depending on window width). You can see the issue with the following markup:
```html
<!-- wp:cover {"dimRatio":50,"isUserOverlayColor":true,"isDark":false,"align":"full","className":"is-light"} -->
<div class="wp-block-cover alignfull is-light"><span aria-hidden="true" class="wp-block-cover__background has-background-dim"></span><div class="wp-block-cover__inner-container"><!-- wp:paragraph {"align":"center","placeholder":"Write title…","textColor":"white","fontSize":"large"} -->
<p class="has-text-align-center has-white-color has-text-color has-large-font-size">Of Mountains &amp; Printing Presses</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:cover -->

<!-- wp:group {"align":"wide","style":{"color":{"background":"#d9edcb"}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide has-background" style="background-color:#d9edcb"><!-- wp:paragraph -->
<p>p in widealign group</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

And add this markup to avoid the issue from being present (unless your window is very wide):
```html
<!-- wp:group {"align":"wide","className":"wporg-gutenberg-block-layout","layout":{"contentSize":"1150px","type":"constrained"}} -->
<div class="wp-block-group alignwide wporg-gutenberg-block-layout"><!-- wp:paragraph {"fontSize":"medium"} -->
<p class="has-medium-font-size">Blocks allow you to build your own custom posts and pages without any coding knowledge. Here’s a selection of the default blocks included with Gutenberg:</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

**Comment by mdawaffe** [comment]
> is this still something you can repro on `trunk`?

Yes, the issue I have still happens in current trunk. Note that it has a similar symptom as the issue described above by @stokesman but comes from a distinct source. (See https://github.com/WordPress/gutenberg/issues/63519#issuecomment-2270218179 and earlier.)

1. Activate Twenty Twenty-Four.
2. Create a new post.
3. Add a group block.
4. Set the group block's Alignment to Full Width.
5. Uncheck the group block's "Inner blocks use content width" setting.
6. Add a few paragraphs of lorem ipsum text to the group block.
7. Zoom out and in. Notice that the line breaks in the paragraphs change.
8. Use the browser inspector to find the editor iframe's HTML element.
9. Set that HTML element's `border` CSS property to `0`.
10. Zoom out and in. Notice that the line breaks in the paragraphs no longer change.

If all we were doing was `scale()`ing, there wouldn't be any layout changes. In addition to adjusting `scale()`, though, we're changing the border of the HTML element. That change impacts the widths of everything else.

I haven't been following any of the more recent discussion about this (and similar issues). Apologies if there's another thread out there with a better understanding than mine in this one :)

**Comment by stokesman** [comment]
@mdawaffe, as far as I can tell this issue has nothing to do with the scaling and border. Those are indeed problems and #65814 is aimed specifically at those. I do appreciate your attention to detail and good explanation of what’s going on with the border and scaling 👍.

As best I can see, this issue is due to `display: flex` being put on the `body` while zoomed out. #65967 currently resolves this issue though it wasn’t the aim of that PR.

**Comment by talldan** [comment]
Not sure if it's the same issue, but it seems pretty easy to reproduce this using Twenty Twenty Five, just by adding a single paragraph to a post:

https://github.com/user-attachments/assets/d31e55f2-a31f-472b-b9be-65011cdb6118

I concur with what @stokesman says, the flex rule is the issue. https://github.com/WordPress/gutenberg/pull/66041 is also resolving the issue for me.

**Comment by ajlende** [comment]
https://github.com/WordPress/gutenberg/pull/66041 was merged, and I can't reproduce this issue on trunk anymore, so closing this one.
