### ISSUE TITLE
Navigate to entity record crash editor

### ISSUE THREAD

**Issue by Tropicalista** [WordPress/gutenberg#64814]
### Description

I have a custom post type which I wanna use as a pattern.

If I try something like this, the editor crashes.

```
	const handleEditForm = () => {
		onNavigateToEntityRecord( {
			postId: ref,
			postType: 'formello',
		} );
	};
```

The error is:

```
Uncaught TypeError: Cannot read properties of null (reading 'ownerDocument')
    at apply (rich-text.js?ver=9988fecf32c29c7254e1:2492:18)
    at applyRecord (rich-text.js?ver=9988fecf32c29c7254e1:3709:5)
    at applyFromProps (rich-text.js?ver=9988fecf32c29c7254e1:3806:5)
    at rich-text.js?ver=9988fecf32c29c7254e1:3813:7
    at commitHookEffectListMount (react-dom.development.js:23184:26)
    at commitLayoutEffectOnFiber (react-dom.development.js:23302:17)
    at commitLayoutMountEffects_complete (react-dom.development.js:24722:9)
    at commitLayoutEffects_begin (react-dom.development.js:24708:7)
    at commitLayoutEffects (react-dom.development.js:24646:3)
    at commitRootImpl (react-dom.development.js:26857:5)
```

### Step-by-step reproduction instructions

1. Create a custom post type (ex. Doc)
2. Create a new post of custom post type (New doc)
3. Create a simple block that mimic what patterns do and add function mentioned above
4. Editor crashes

### Environment info

- WP 6.6

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by Mamaduka** [comment]
@Tropicalista, can you provide code for a simple block that mimics the Patterns (Reusable) block? The issue might be with it.

**Comment by Tropicalista** [comment]
This is solved with Gutenberg 19.4.0

**Comment by Tropicalista** [comment]
This come out again with wp 6.7 RC 1.


```
The above error occurred in the <ForwardRef(PostTitle)> component:

    at PostTitle (http://localhost:10005/wp-includes/js/dist/editor.js?ver=f84c1fcefdc6332efbd1:20825:53)
    at div
    at div
    at WritingFlow (http://localhost:10005/wp-includes/js/dist/block-editor.js?ver=ba158b1bfcaf2bda05b0:43957:3)
    at div
    at BlockTools (http://localhost:10005/wp-includes/js/dist/block-editor.js?ver=ba158b1bfcaf2bda05b0:58576:3)
    at ExperimentalBlockCanvas (http://localhost:10005/wp-includes/js/dist/block-editor.js?ver=ba158b1bfcaf2bda05b0:59136:3)
    at div
    at Resizable (http://localhost:10005/wp-includes/js/dist/components.js?ver=75e0765bccdbc4da087e:62986:28)
    at UnforwardedResizableBox (http://localhost:10005/wp-includes/js/dist/components.js?ver=75e0765bccdbc4da087e:64031:3)
    at ResizableEditor (http://localhost:10005/wp-includes/js/dist/editor.js?ver=f84c1fcefdc6332efbd1:27050:3)
    at div
    at VisualEditor (http://localhost:10005/wp-includes/js/dist/editor.js?ver=f84c1fcefdc6332efbd1:27266:3)
    at SlotComponent (http://localhost:10005/wp-includes/js/dist/components.js?ver=75e0765bccdbc4da087e:33416:5)
    at Slot
    at UnforwardedSlot (http://localhost:10005/wp-includes/js/dist/components.js?ver=75e0765bccdbc4da087e:33976:5)
    at EditCanvasContainerSlotSlot
    at div
    at http://localhost:10005/wp-includes/js/dist/editor.js?ver=f84c1fcefdc6332efbd1:9868:3
    at div
    at div
    at div
    at InterfaceSkeleton (http://localhost:10005/wp-includes/js/dist/editor.js?ver=f84c1fcefdc6332efbd1:9958:3)
    at EditorInterface (http://localhost:10005/wp-includes/js/dist/editor.js?ver=f84c1fcefdc6332efbd1:27596:3)
    at BlockRefsProvider (http://localhost:10005/wp-includes/js/dist/block-editor.js?ver=ba158b1bfcaf2bda05b0:27719:3)
    at Provider (http://localhost:10005/wp-includes/js/dist/components.js?ver=75e0765bccdbc4da087e:33991:3)
    at http://localhost:10005/wp-includes/js/dist/block-editor.js?ver=ba158b1bfcaf2bda05b0:36995:5
    at http://localhost:10005/wp-includes/js/dist/block-editor.js?ver=ba158b1bfcaf2bda05b0:36539:3
    at BlockContextProvider (http://localhost:10005/wp-includes/js/dist/block-editor.js?ver=ba158b1bfcaf2bda05b0:37058:3)
    at EntityProvider (http://localhost:10005/wp-includes/js/dist/core-data.js?ver=c8526dfd5ea638e51031:6994:3)
    at EntityProvider (http://localhost:10005/wp-includes/js/dist/core-data.js?ver=c8526dfd5ea638e51031:6994:3)
    at http://localhost:10005/wp-includes/js/dist/editor.js?ver=f84c1fcefdc6332efbd1:24561:3
    at http://localhost:10005/wp-includes/js/dist/editor.js?ver=f84c1fcefdc6332efbd1:21964:3
    at Editor (http://localhost:10005/wp-includes/js/dist/editor.js?ver=f84c1fcefdc6332efbd1:29324:3)
    at div
    at ErrorBoundary (http://localhost:10005/wp-includes/js/dist/editor.js?ver=f84c1fcefdc6332efbd1:11688:5)
    at SlotFillProvider (http://localhost:10005/wp-includes/js/dist/components.js?ver=75e0765bccdbc4da087e:33829:3)
    at provider_SlotFillProvider (http://localhost:10005/wp-includes/js/dist/components.js?ver=75e0765bccdbc4da087e:33927:3)
    at Provider (http://localhost:10005/wp-includes/js/dist/components.js?ver=75e0765bccdbc4da087e:33991:3)
    at Layout (http://localhost:10005/wp-includes/js/dist/edit-post.js?ver=9567d2bb2ad838a6bbda:3116:11)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by Mamaduka** [comment]
@Tropicalista, the issue is fixed in Gutenberg 19.4 but not in WP 6.7 RC1. Is that correct?

**Comment by Tropicalista** [comment]
Yes it's correct. Can [this](https://github.com/WordPress/gutenberg/pull/66213) be related?

**Comment by Tropicalista** [comment]
To clarify things, onNavigateToEntityRecord **works on 19.3 and up**. It does not work on WP 6.7-RC1 without Gutenberg.

I'm testing with [formello](https://wordpress.org/plugins/formello/) plugin. The code I'm using to test this up is [here](https://github.com/formello-forms/formello/blob/master/src/blocks/library/edit.js).

From what I see the wp 6.7 should use Gutenberg 19.3. Am I correct?

**Comment by t-hamano** [comment]
I tested it with the following steps and I think I was able to reproduce it.

1. Start WordPress 6.7 RC1 environment
2. Activate [the Formllo](https://ja.wordpress.org/plugins/formello/) plugin
3. Switch Gutenberg branch to `release/19.5`
4. Deactivate Gutenberg plugin
5. Create a new form from the Forms menu
6. Add the form to the post editor
7. Click "Edit original" from the block toolbar
8. ❌ The editor crashes.
9. Activate Gutenberg plugin
10. Perform steps 6-7
11. ✅ The editor does not crash

Interestingly, this issue does not occur in the `release/19.5` branch of Gutenberg, but the editor crashes in the trunk (86a3bc9bb3). So, the result is as follows:

- ❌ WordPress 6.7 RC1
- ✅ Gutenberg `release/19.5` branch
- ❌ Gutenberg trunk (86a3bc9bb3)

It is still unclear whether this is a plugin issue or a Gutenberg issue.

https://github.com/user-attachments/assets/9c430da1-4809-4763-904d-b8a6ee01fa69

**Comment by t-hamano** [comment]
@Tropicalista I tested this issue again with minimal code and am unable to reproduce the issue in 6.7 RC1.

The following code creates a custom post called "Book" and tests navigating to the post via a block.

<details><summary>Details</summary>

PHP:

```php
add_action(
	'init',
	function () {
		register_post_type(
			'book',
			array(
				'public'       => true,
				'label'        => 'Books',
				'show_in_rest' => true,
			)
		);
	}
);
```

JavaScript:

```javascript
wp.blocks.registerBlockType( 'test/navigate-entity-test', {
	apiVersion: 3,
	title: 'Navigate Entity Test',
	edit: () => {
		const { onNavigateToEntityRecord } = wp.data
			.select( 'core/block-editor' )
			.getSettings();
		return wp.element.createElement(
			'div',
			wp.blockEditor.useBlockProps(),
			wp.element.createElement(
				'button',
				{
					onClick: () => {
						onNavigateToEntityRecord( {
							postId: 8, // Replace with the actual post ID
							postType: 'book',
						} );
					},
				},
				'Navigate to Custom Post Type (Books) entity'
			)
		);
	},
} );
```

</details> 

https://github.com/user-attachments/assets/07827568-23f1-4e90-bb86-5e9f72b83aa8

Is your code attempting to access a variable or element that may be undefined?

**Comment by ndiego** [comment]
Moving this back to "In Discussion" on the 6.7 project board for the time being.

**Comment by Tropicalista** [comment]
I think I found the problem.

This code works. But of course it will not display the children

```
export default function ReusableBlockEdit( {
	attributes: { ref },
	clientId,
	name,
	setAttributes,
} ) {
	const [ isModalOpen, setModalOpen ] = useState( false );
	const [ isDisabled, setIsDisabled ] = useState( true );
	const [ titleTemp, createTitle ] = useState( '' );

	const { onNavigateToEntityRecord } = useSelect(
		( select ) => {
			const {
				getSettings,
			} = select( blockEditorStore );

			// For editing link to the site editor if the theme and user permissions support it.
			return {
				onNavigateToEntityRecord:
					getSettings().onNavigateToEntityRecord,
			};
		},
		[ clientId, ref ]
	);

	const handleEditOriginal = () => {
		onNavigateToEntityRecord( {
			postId: ref,
			postType: 'formello_form',
		} );
	};

	const blockProps = useBlockProps();

	const { children, ...innerBlocksProps } = useInnerBlocksProps( blockProps );

	return (
		<div { ...innerBlocksProps }>
			<BlockControls>
				<ToolbarGroup>
					<ToolbarButton onClick={ handleEditOriginal }>
						{ __( 'Edit form', 'formello' ) }
					</ToolbarButton>
				</ToolbarGroup>
			</BlockControls>
			{ children }
		</div>
	);
}
```

IT will crash if I change the code to something like this:

```
	const [ blocks, onInput, onChange ] = useEntityBlockEditor(
		'postType',
		'formello_form',
		{ id: ref }
	);

	const innerBlocksProps = useInnerBlocksProps( blockProps, {
		value: blocks,
		onInput,
		onChange,
		allowedBlocks: [ 'formello/form' ],
		renderAppender: blocks?.length
			? undefined
			: InnerBlocks.ButtonBlockAppender,
	} );
```

Do you have any idea of what should I do to prevent this error? Is it a bug or is my code worng?

**Comment by t-hamano** [comment]
I'm still not sure if this is a problem with Gutenberg itself.

@Tropicalista 

- Just to be sure, does this issue occur in 6.7 RC2?
- Could you enable `SCRIPT_DEBUG` and tell us the error you get?
- Could you provide the minimal but complete Edit component code that causes the crash?

**Comment by Tropicalista** [comment]
@t-hamano I have uploaded a demo repo that you can test here: [![Navifate to entity](https://img.shields.io/wordpress/plugin/v/block-visibility?logo=wordpress&logoColor=%23fff&label=Playground%20Demo&labelColor=%233858e9&color=%233858e9)](https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fraw.githubusercontent.com%2FTropicalista%2Fnavigate-to-entity%2Frefs%2Fheads%2Fmaster%2Fplayground%2Fblueprint.json&php=8.0&wp=beta&networking=yes&language=&multisite=no&random=95nmouu9r7i)

Link to repo: https://github.com/Tropicalista/navigate-to-entity/tree/master

- I have created a super simple post type book.
- I have created a simple pattern
- I have created a simple block that use navigate to entity
- I have created a blog post to embed both
- The pattern works, the custom post type does not.

To be clear, if I use the code you shared before, without a children block, it works. 

The code of the block is very simple and you can see it here: https://github.com/Tropicalista/navigate-to-entity/blob/master/src/edit.js

**Comment by t-hamano** [comment]
@Tropicalista Thanks for the detailed info. I was able to track down the PR related to this issue.

To get straight to the point, I believe this is a Gutenberg issue and should be fixed in WP 6.7.

### Step-by-step reproduction instructions

First, I would like to explain again how to test this issue:

- Upload and activate [this plugin](https://github.com/Tropicalista/navigate-to-entity/tree/master). It will create a post type called "Book".
- Create a new Book post. Make a note of its post ID.
- Enter the following code into the post editor, replacing the ref value with the post ID you noted earlier: 
  ```html
  <!-- wp:test/sample {"ref":1,"postType":"book"} -->
  <p class="wp-block-test-sample">Hello from the saved content!</p>
  <!-- /wp:test/sample -->
  ```
- Click the "Edit book" button in the block toolbar.
- This will crash the editor. However, if you reload your browser the post will display correctly.

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/a87af665-4d35-4b79-800a-e3fb4aefb1b9

### When was this issue resolved and when did it reoccur?

- ❌ WordPress 6.7 RC2: Problems will occur.
- ✅ #65062 has been merged and the issue no longer occurs. This is part of Gutenberg 19.3, so it shipped into WP 6.7.
- ❌ The issue reappeared with the merge of #66101. This PR is part of Gutenberg 19.6 but has been backported to WP 6.7.

---

So it looks like a regression that occurred during the WP 6.7 cycle.

@SantosGuillamot @gziolo Do you know anything about this issue?

**Comment by Tropicalista** [comment]
Can be this [line](https://github.com/WordPress/gutenberg/blob/8af840ec02fb4122f8ccf683d235a4324090d2b4/packages/editor/src/components/provider/index.js#L183)?

**Comment by gziolo** [comment]
I performed some debugging at these are my findings.

> Can be this [line](https://github.com/WordPress/gutenberg/blob/8af840ec02fb4122f8ccf683d235a4324090d2b4/packages/editor/src/components/provider/index.js#L183)?

Removing the logic as follows doesn't fix the issue:

```diff
diff --git a/packages/editor/src/components/provider/index.js b/packages/editor/src/components/provider/index.js
index 50d0261006..623cb847be 100644
--- a/packages/editor/src/components/provider/index.js
+++ b/packages/editor/src/components/provider/index.js
@@ -173,17 +173,13 @@ export const ExperimentalEditorProvider = withRegistryProvider(
 						getRenderingMode,
 						__unstableIsEditorReady,
 					} = select( editorStore );
-					const { getEntitiesConfig } = select( coreStore );
 
 					return {
 						editorSettings: getEditorSettings(),
 						isReady: __unstableIsEditorReady(),
 						mode: getRenderingMode(),
 						selection: getEditorSelection(),
-						postTypeEntities:
-							post.type === 'wp_template'
-								? getEntitiesConfig( 'postType' )
-								: null,
+						postTypeEntities: null,
 					};
 				},
 				[ post.type ]
```

Adding an additional call for `getPostTypes` resolves the issue:

```diff
diff --git a/packages/editor/src/components/provider/index.js b/packages/editor/src/components/provider/index.js
index 50d0261006..dba4e86178 100644
--- a/packages/editor/src/components/provider/index.js
+++ b/packages/editor/src/components/provider/index.js
@@ -173,8 +173,9 @@ export const ExperimentalEditorProvider = withRegistryProvider(
 						getRenderingMode,
 						__unstableIsEditorReady,
 					} = select( editorStore );
-					const { getEntitiesConfig } = select( coreStore );
-
+					const { getEntitiesConfig, getPostTypes } =
+						select( coreStore );
+					getPostTypes( { per_page: -1 } );
 					return {
 						editorSettings: getEditorSettings(),
 						isReady: __unstableIsEditorReady(),
```

It means that the plugins shared above depend on some internal implementation of the post editor, which was never guaranteed in WordPress core. To me, it feels like the missing part is populating the list of all available post types for this functionality to be fully functional.

**Comment by SantosGuillamot** [comment]
I have similar observations after testing it. I don't think it is a bug caused by the mentioned pull request, but it was potentially covering the original issue.

From my triaging, it definitely seems it is a problem caused because the postType is not available yet when doing the navigation. To simplify the testing I was running this code directly in the console:

```js
wp.data.select('core/block-editor').getSettings().onNavigateToEntityRecord( { postId: 16, postType: 'book' } )
```

Running just that code triggers the error. However, if just before that I run the following:

```js
wp.data.select('core').getPostType('book');
```

It navigates as expected.

I'm wondering if this should be handled automatically by the core function and make it wait until the postType is available. I've seen we are already calling that function [here](https://github.com/WordPress/gutenberg/blob/03225e0e2b5aa369f402273d3612f1e2e45c9f15/packages/edit-post/src/components/layout/index.js#L409). Maybe we can reuse that logic somehow. The rendering logic seems to happen in that file.

**Comment by gziolo** [comment]
I also ran a test with WordPress 6.6 and installed the Formello plugin ([highlighted here](https://github.com/WordPress/gutenberg/issues/64814#issuecomment-2440362287)). The same issue has existed for quite some time. I agree with @SantosGuillamot that the potential fix should be applied on the `onNavigateToEntityRecord` level.

**Comment by Tropicalista** [comment]
With Gutenberg version 16.3 and up, this it's working. Why not backport?

**Comment by getdave** [comment]
The [backport to 6.7 which "regressed" this](https://github.com/WordPress/gutenberg/pull/66101) fixed a performance issue so I'm not sure a simple backport is possible. We need a more tailored fix (as suggested above).

**Comment by SantosGuillamot** [comment]
> With Gutenberg version 16.3 and up, this it's working. Why not backport?

I'm still seeing the problem with Gutenberg `trunk`.

Some potential solutions I see to the original issue:

* Don't load the `edit-post` component until the post type is loaded.

We could include a call to `getPostType` in [this useSelect](https://github.com/WordPress/gutenberg/blob/03225e0e2b5aa369f402273d3612f1e2e45c9f15/packages/edit-post/src/components/layout/index.js#L419-L439) and only load the component when it is defined. Something like this:

```js
With Gutenberg version 16.3 and up, this it's working. Why not backport?
isPostTypeLoaded: !! getPostType( currentPostType ),
```

I have tested it, and it seems to "work" as a quick solution.  However, I believe we should try to go one step back.

* Go one step back and load the post type before navigating.
Ideally, we should call `getPostType` just before [this dispatch](https://github.com/WordPress/gutenberg/blob/03225e0e2b5aa369f402273d3612f1e2e45c9f15/packages/edit-post/src/hooks/use-navigate-to-entity-record.js#L56-L62). But I am not sure how to do that.

**Comment by getdave** [comment]
Update: I have a PoC PR in https://github.com/WordPress/gutenberg/pull/66709.

-----

Would this `await resolveSelect` pattern work?

https://github.com/WordPress/gutenberg/blob/7c7c2062934000bdb77d668a29e99767102f9f93/packages/block-library/src/navigation/edit/use-convert-classic-menu-to-block-menu.js#L33-L45

Something like:

```js
const onNavigateToEntityRecord = useCallback(
	async ( params ) => {
		await registry
			.resolveSelect( coreStore )
			.getPostType( params.postType );
		dispatch( {
			type: 'push',
			post: { postId: params.postId, postType: params.postType },
			// Save the current rendering mode so we can restore it when navigating back.
			previousRenderingMode: getRenderingMode(),
		} );
		setRenderingMode( defaultRenderingMode );
	},
	[ registry, getRenderingMode, setRenderingMode, defaultRenderingMode ]
);
```

In my testing this fixes the Issue reported when using that Plugin.

**Comment by SantosGuillamot** [comment]
I believe something like that could work and it seems to solved the issue in my testing 🙂

**Comment by getdave** [comment]
Let's work on refining https://github.com/WordPress/gutenberg/pull/66709. It's currently targetting `wp/6.7` but should it be targetting `trunk`?

**Comment by Tropicalista** [comment]
The fix is still not working on site editor.

Simply copy the two demo from a post and try to insert in template in site editor. 

Try in playground: [![Navifate to entity](https://img.shields.io/wordpress/plugin/v/block-visibility?logo=wordpress&logoColor=%23fff&label=Playground%20Demo&labelColor=%233858e9&color=%233858e9)](https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fraw.githubusercontent.com%2FTropicalista%2Fnavigate-to-entity%2Frefs%2Fheads%2Fmaster%2Fplayground%2Fblueprint.json&php=8.0&wp=beta&networking=yes&language=&multisite=no&random=95nmouu9r7i)

**Comment by ghost** [comment]
In Gutenberg 19.4, this issue was resolved, but it has reappeared in version 19.6.1. Please investigate.

**Comment by getdave** [comment]
> The fix is still not working on site editor.

@Tropicalista I don't _think_ your Playground is using [the Gutenberg PR which fixes](https://github.com/WordPress/gutenberg/pull/66709) the Issue?

Try [this Playground which activates the Gutenberg PR](https://playground.wordpress.net/?blueprint-url=https%3A%2F%2Fraw.githubusercontent.com%2FTropicalista%2Fnavigate-to-entity%2Frefs%2Fheads%2Fmaster%2Fplayground%2Fblueprint.json&php=8.0&wp=beta&networking=yes&language=&multisite=no&random=95nmouu9r7i&gutenberg-pr=66709).

Here's a screencapture of me showing it working:

https://github.com/user-attachments/assets/b5cb9424-e22e-451b-bd66-4c8e4c8d5adf

**Comment by Tropicalista** [comment]
@getdave You are right.

I thought that this was merged because issue title says 6.7.

**Comment by Mamaduka** [comment]
Has anyone figured out why the bug affects a third-party plugin but not the core Patterns block?

While #66709 is a good hotfix, it's still a compromise. There should be no need to pre-select data before navigation; the editor should do it for consumers as needed (after navigation).

@youknowriad, @jsnajdr, what do you think?

**Comment by youknowriad** [comment]
The reason is probably because patterns are loaded on every editor, so the post type is already there. But I agree that we need to solve the root issue. (Wait for the post type at the moment that we need it) instead of adding a fetch call in the onNavigate callback because that's probably just one way to trigger the issue.

**Comment by getdave** [comment]
I would be happy to close https://github.com/WordPress/gutenberg/pull/66709. I don't like changing from sync to async in that PR and as you say the editor should be able to request the entities on demand when it navigates rather than having to have them ready in advance.

**Comment by jsnajdr** [comment]
This is a bug caused by `useRichText` returning a ref that is used on an element that is rendered conditionally. The Post Title component does this:
```js
const { ref } = useRichText();
return (
  <PostTypeSupportCheck supportKeys="title">
    <h1 ref={ ref } />
  <PostTypeSupportCheck />
);
```
When navigating from a post of type `post` to a post of type `book`, the `PostTypeSupportCheck` briefly unmounts the `h1` element because it internally fetches the post type for `book`. Only after the post type is loaded does it support `title` again.

The `useRichText` logic, namely the `applyFromProps` calls, get very confused when the ref is reset to `null`. Then a `useLayoutEffect` that calls `applyFromProps` has no element to work with.

I tried to fix this by setting `didMountRef.current = false` when the element unmounts. This fixes the crash, but it introduces another bug: the post title is not updated. When navigation from the "post" post to "book" post, the UI still shows the "post" title. Maybe @ellatrix can help here.

This all also explains why @getdave's fix in #66709 involves calling `getPostType`. By preloading the post type, it avoids unmounting the `h1` in `PostTypeSupportCheck`.

The bug can also be fixed by wrapping all post title logic inside `PostTypeSupportCheck`, including the `useRichText` call. But that works around a bug in `useRichText` that would still remain there.

**Comment by cbravobernal** [comment]
Cherry-picked to 6.7 branch for a 6.7.2 release.
