### ISSUE TITLE
CSS nesting is broken in the fallback div.editor-styles-wrapper version of the editor.

### ISSUE THREAD

**Issue by tcmulder** [WordPress/gutenberg#65172]
### Description

When the editor falls back to the editor div rather than the new iframe, the .editor-styles-wrapper class scoping breaks CSS nesting, which is now supported in all major, modern browsers.

In the new iframe, for instance, I could write the following, which gets output exactly as it is written here, which works in modern browsers:

```
.some-parent {
	.some-child {
		color: purple;
	}
}
```

However, when this gets loaded into the .editor-styles-wrapper div and add_editor_style adds the scoping class, the result is this:

```
.editor-styles-wrapper .some-parent {
	.editor-styles-wrapper .some-child {
		color: purple;
	}
}
```

The child should not receive a scope, since .some-parent does not contain an element called .editor-styles-wrapper.

### Step-by-step reproduction instructions

1. Create a CSS file, e.g. `css-nesting.css` at the root of your theme.
2. Add the following in that file:

```
.some-parent {
	.some-child {
		color: purple;
	}
}
```

3. Add the following to `functions.php`.

```
add_action( 'after_setup_theme', function() {
	add_theme_support( 'editor-styles' );
	add_editor_style( '/css-nesting.css' );
} );
```

4. Load a page that uses the old div.editor-styles-wrapper and view the source: you'll see the broken nesting in the <style> tag that gets created for scoping.

Note I'm not 100% sure how to force the old div.editor-styles-wrapper version to be used, but I've heard having a block registered with apiVersion equal to 2 in the blocks.json will trigger this behavior.

### Environment info

- WordPress 6.6.1.
- Basic Underscores theme.
- No plugins active.

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by kubiqsk** [comment]
Hi,
did you find some tricky way how to fix this?
I see it's almost 1 year and there is no reaction in here, despite it's a pretty serious bug...

**Comment by tcmulder** [comment]
I _think_ this has been fixed. I now get:

```css
:where(.editor-styles-wrapper) .some-parent .some-child {
  color: purple;
}
```

in WordPress 6.8.1. That works.

Also, it's much more common for the new iframe to load rather than the legacy div system these days, since far fewer block.json files for blocks are below version 3.

**Comment by kubiqsk** [comment]
Not really, for me it's still not working, that's why I commented this thread in here...
I had to do `@import()` in main CSS file to trick it, so it will not add any `:where(.editor-styles-wrapper)` anywhere...

Eg.

```css
a.case-study-item{
	overflow: hidden;
	display: flex;
	flex-direction: column;

	.image{
		position: relative;
	}
}
```

will be 

```css
:where(.editor-styles-wrapper) a.case-study-item{
	overflow: hidden;
	display: flex;
	flex-direction: column;

	:where(.editor-styles-wrapper) .image{
		position: relative;
	}
}
```

and that will not work for the `.image` class of course

**Comment by kubiqsk** [comment]
Can you reopen this issue please? Or should I create a new one? Because it's really not solved...

**Comment by tcmulder** [comment]
That's odd, I get:

```css
:where(.editor-styles-wrapper) a.case-study-item {
  overflow: hidden;
  display: flex;
  flex-direction: column;
}
:where(.editor-styles-wrapper) a.case-study-item .image {
  position: relative;
 }
```

**Comment by tcmulder** [comment]
Ah, you're right: my build tool was compiling the problem away. With my previous example, I'm now getting:

```css
:where(.editor-styles-wrapper) .some-parent {
	:where(.editor-styles-wrapper) .some-child {
		color: purple;
	}
}
```

which is slightly different than before, but still problematic. I've not found a workaround beyond implementing a build tool (I'm using @wordpress/scripts) if my theme needs to support version 2 of block.json.

**Comment by USERSATOSHI** [comment]
## Reproduction Report
### Description
This report validates whether the issue can be reproduced.

### Environment
- WordPress: 6.9-alpha-60272
- PHP: 8.2.28
- Server: Apache/2.4.62 (Debian)
- Database: mysqli (Server: 11.8.2-MariaDB-ubu2404 / Client: mysqlnd 8.2.28)
- Browser: Chrome 138.0.0.0
- OS: macOS
- Theme: Twenty Eleven 4.9
- MU Plugins:
  * Gutenberg Test Plugin, Disable Login Autofocus 
  * Gutenberg Test Plugin, Disable Remote Patterns 
  * Gutenberg Test Plugin, Enable Templates UI 
  * Gutenberg Test Plugin, No-cache Headers 
  * Gutenberg Test Plugin, Normalize Theme 
  * server-timing.php 
- Plugins:
  * Gutenberg 21.3.0-rc.2
  * Test Reports 1.2.0

### Actual Results
1.  ✅ Error condition occurs (reproduced).

### Supplemental Artifacts
<img width="1470" height="804" alt="Image" src="https://github.com/user-attachments/assets/9a7d50c9-5537-4e8d-a685-f9af4984cf3a" />

<img width="1448" height="224" alt="Image" src="https://github.com/user-attachments/assets/14306946-2325-42e0-8cf8-608fe770fb3a" />
