### ISSUE TITLE
Edit content mode (select mode): Ellipsis menu button in list view is empty

### ISSUE THREAD

**Issue by andrewserong** [WordPress/gutenberg#65504]
### Description

Following #65204, blocks in the list view still show an ellipsis menu, and it's clickable, however the menu is empty.

In this case, where the menu will be empty, shall we skip the ellipsis menu button from rendering?

### Step-by-step reproduction instructions

1. Open the site editor
2. At the top left, click the pointer icon and switch from Design mode to Edit mode (formerly known as Select mode)
3. Open the list view, and see that there is still an ellipsis menu button for each item in the list view

### Screenshots, screen recording, code snippet

<img width="552" alt="image" src="https://github.com/user-attachments/assets/1034ea85-8791-418c-a32e-20125467e09e">

### Environment info

- Gutenberg trunk

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by youknowriad** [comment]
I think this is most likely fixed by #65485

**Comment by andrewserong** [comment]
Just re-tested on `trunk`, and it's close now, but we still expose the block settings menu in some circumstances. Mostly it's hidden (e.g. with headings and paragraphs), however Button blocks still appear to show the settings menu:

https://github.com/user-attachments/assets/6860147f-577b-43d6-8737-7e1394a63d40

**Comment by richtabor** [comment]
Confirmed, this is still happening for the button block at least. I'm not following the conditions why this block is treated differently, even from List Item block.

**Comment by youknowriad** [comment]
Can't reproduce this at the moment. I see a "duplicate" menu item for buttons.

**Comment by andrewserong** [comment]
> Can't reproduce this at the moment. I see a "duplicate" menu item for buttons.

I just re-tested and I think it's largely gone now. Since we now allow duplication, I think that's largely hidden the issue as we only rarely see a situation where the settings menu is empty. This is pretty edge-casey, but I can now reproduce the issue if I lock a button block (i.e. as might be the case within a pattern), and then switch to content only mode, as in that case Duplicate will not be available:

https://github.com/user-attachments/assets/c63870c9-80c0-4373-9268-191c87596a97

IMO this makes it much lower priority to fix, as in most cases users likely won't encounter this? Still, it could be good to polish it at some point.

**Comment by youknowriad** [comment]
My guess is that it's not really fixable with how our extensibility APIs work. We have slots that inject menu elements to these dropdown, and I believe there's no way to know whether there will be something rendered on these slots or not without actually opening the block settings menu. 

That said, we could be "more conservative" and say: just hide the whole dropdown if "content only" or something regardless of whether there are fills or not.

**Comment by draganescu** [comment]
> just hide the whole dropdown if "content only" 

I think we just expanded the list of available optopns in this dropdown, right? Maybe the dropdown should say it's empty if it's empty with some disabled state ... although that never fares well 😄

**Comment by ramonjd** [comment]
> I can now reproduce the issue if I lock a button block (i.e. as might be the case within a pattern), and then switch to content only mode, as in that case Duplicate will not be available:

I tried this again:

https://github.com/user-attachments/assets/bb80c127-fd0c-491a-be4d-0afcc68fe1b4

I think it's possible that a side effect of @jeryj's recent PR has ensured that there's always something there, `Add before/after`

- https://github.com/WordPress/gutenberg/pull/70827

I couldn't find any other instances. If I'm not missing something, could we close this issue for now?

**Comment by andrewserong** [comment]
> I couldn't find any other instances. If I'm not missing something, could we close this issue for now?

Thanks for re-testing! This is quite an old issue now, so let's close it out and re-open (or create a new issue) if we run into it again.

**Comment by jeryj** [comment]
Fixing bugs by accident is the best 😅
