### ISSUE TITLE
Media & Text: Layout breaks when inside a Stack and set to "Crop image to fill"

### ISSUE THREAD

**Issue by andersnoren** [WordPress/gutenberg#65605]
### Description

If you place a Media & Text block inside a Stack block, assign an image and set the image to "Crop image to fill", the image will overflow the bounds of the wrapping blocks.

### Step-by-step reproduction instructions

1. Create a new page.
2. Insert a Stack.
3. Insert a Media & Text block inside the stack, and assign an image.
4. In the block settings, set the image to "Crop image to fill".
5. The image should overflow the stack in the block editor.
6. Publish and visit the page, and the image should overflow the stack (and the Post Content block) on the front-end as well.

### Screenshots, screen recording, code snippet

<img width="1328" alt="image" src="https://github.com/user-attachments/assets/2d106861-f840-453d-8183-fadd0450a398">

Edit: Disregard the page title – there's no Cover block used in the layout.

### Environment info

WP 6.6.2
Twenty Twenty-Four
With or without Gutenberg 19.2.0 active

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [X] Yes

**Comment by ndiego** [comment]
It looks like this issue might have been fixed in Gutenberg 19.3. I am able to replicate in 19.2 but not in 19.3. Can you confirm?

**Comment by andersnoren** [comment]
Hey @ndiego! I'm still getting it in 19.3, both in the layout created in 19.2 (viewed with 19.3 installed) and one created from scratch after the update to 19.3.

Here's the block markup for the latter, in case it's helpful:

```
<!-- wp:group {"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:media-text {"mediaId":24991,"mediaLink":"http://localhost:8888/utsikt/gallery-test-two/poe-image-8/","mediaType":"image","imageFill":true} -->
<div class="wp-block-media-text is-stacked-on-mobile is-image-fill-element"><figure class="wp-block-media-text__media"><img src="http://localhost:8888/utsikt/wp-content/uploads/2022/07/poe-image-8-1024x768.png" alt="" class="wp-image-24991 size-full" style="object-position:50% 50%"/></figure><div class="wp-block-media-text__content"><!-- wp:paragraph {"placeholder":"Content…"} -->
<p></p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:media-text --></div>
<!-- /wp:group -->
```

**Comment by ndiego** [comment]
Thanks for the code. I'm still having trouble replicating this in the TT4 theme. 🤔

| Editor | Front end |
|-|-|
|<img width="1267" alt="image" src="https://github.com/user-attachments/assets/c9ce5be8-27a0-4a15-9a92-d7fc0141a90f">|<img width="680" alt="image" src="https://github.com/user-attachments/assets/ab6eb20a-0473-4755-b030-81684a23ca2f">|

**Comment by andersnoren** [comment]
Oh, it seems this is a Safari only issue (currently running version 17.6). It looks correct in Chrome, Firefox and Opera.

**Comment by Mayank-Tripathi32** [comment]
I tried replicating the issue but did not encounter any overflow in Safari or Chrome. However, I noticed that the image disappears from the frontend if no text is set. It seems this issue might have been resolved, but a different behavior may have been introduced. I'll investigate this further.

https://github.com/user-attachments/assets/a2af3ebe-4a5c-4a88-9583-8d2c3cc70d8b

**Comment by andersnoren** [comment]
@Mayank-Tripathi32 I can't replicate the behavior in the OP anymore either. It seems to work in both Gutenberg 20.0.0 and in 6.7.1 with Gutenberg deactivated (tested on Safari). 

Feel free to close if you want to open a new issue for the image not being visible if included in a stack without any text. I'm getting that as well, but it doesn't seem Safari specific.
