### ISSUE TITLE
Chrome Color Picker styling issues

### ISSUE THREAD

**Issue by yuanworks** [WordPress/gutenberg#6750]
## The popup color picker (aka. Chrome Picker) has CSS styling issues.

**Steps To Reproduce**
1. Go to a new Paragraph Block
2. Select the background / font color
3. Choose a custom color

**Issues**
1. Width of the Chrome Picker is not the same as the  parent popup component.
2. ChromePicker is using "Menlo" font by default, which is defaulting to a sans-serif font on Windows (ideally should just use the `font-family: inherited` which doesn't break the layout)

**Screenshot**
![image](https://user-images.githubusercontent.com/3508123/40032148-67eed864-5825-11e8-8490-25c5bda3ec0e.png)

**Desktop (please complete the following information):**
 - OS: Mac, Windows
- Browser Chrome, Firefox

**Smartphone (please complete the following information):**
 - Device: Android

If there's a green light on this, I will work on a PR for it.

**Comment by ajitbohra** [comment]
styling issues have been fixed in master branch

**Comment by danielbachhuber** [comment]
@yuanworks Can you create a pull request for issue 2?

> ChromePicker is using "Menlo" font by default, which is defaulting to a sans-serif font on Windows (ideally should just use the `font-family: inherited` which doesn't break the layout)

**Comment by yuanworks** [comment]
@ajitbohra for some reason I still see the wrong picker width after pulling from origin/master, as well as on the just-released 2.9.1. Am I missing some other step after ` git pull origin`? (other than `npm install / npm run dev`)

**Comment by pento** [comment]
@yuanworks: I can reproduce the same bug locally, #5962 was closed without being merged, so it hasn't actually been fixed.

**Comment by yuanworks** [comment]
Thanks @pento. Recarding the second issue I noted, on Windows (a big portion of users) seeing the color HEX on the default serif Times New Roman font is an eyesore but doesn't have as quick of a fix as the width.

![image](https://user-images.githubusercontent.com/3508123/40340773-91c98150-5db3-11e8-9daf-9624422c6e45.png)

Should I try to contact the author of the component (not sure if Gutenberg is always keeping up with the version) so that he can hardcode something like `font-famiy: Menlo, Arial, Helvetica, sans-serif` to the component or it's better just to wait and see if a custom component will be rebuilt?

**Comment by pento** [comment]
Hrrm, that's a problem. It's worth contacting the author, but as @mtias suggested in #6863, we may need to rebuilt the colour picker, anyway.
