### ISSUE TITLE
Button Block does not prefix a URL with `http://`

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#6841]
**Describe the bug**
I had a feeling that this issue issue may have been raised before but I can't find it.

When you enter a url for a button, you can't hit the `Return` key to apply your changes.

On top of that, if you type a url without the `https://` it displays a random result from your site and when you hit `Return`, it actually selects that result instead of using the url you typed

**To Reproduce**
1. Add Button Block
2. Type `google.com` into the URL field
3. Hit `return` key to apply changes

**Expected behavior**
I should be able to simply enter a URL and hit Enter/Return to apply the changes

**Screenshots**
![gutenberg_buttonblock](https://user-images.githubusercontent.com/2078245/40266422-2aeeb954-5b8e-11e8-9a8f-409f968c4792.gif)

_macOS Sierra 10.12.1 (16B2659)
Firefox Quantum 60.0 (64-bit)
WordPress 4.9.6
Gutenberg 2.9.0_

**Comment by danielbachhuber** [comment]
> On top of that, if you type a url without the https:// it displays a random result from your site and when you hit Return, it actually selects that result instead of using the url you typed

This is a bug. We should make sure the first search result isn't automatically selected.

**Comment by brandonpayton** [comment]
Tested and confirmed this is still a bug.

**Comment by afercia** [comment]
Maybe I'm missing something. I've just tested it:
- typed `wordpress.org`
- got some search results but I've ignored them and just pressed Enter
- I got the entered value in the markup: `<a class="wp-block-button__link" href="wordpress.org"></a>`

However, there's no validation or feedback at all: search suggestions stay open, nothing informs me a link has been added, the resulting `href` attribute is invalid. See also https://github.com/WordPress/gutenberg/issues/1838

**Comment by brandonpayton** [comment]
@afercia, thanks for catching that. I'm seeing the same. The link is saved but with no validation or indication it occurred.

It would be good to get design feedback on how we should:
* Communicate validation errors.
* Convey that the URL has been saved.

I'm leaving this open since this speaks to URL editing for the Button block. Hopefully answers here or in #1838 can be useful for both.

**Comment by mtias** [comment]
Let's consolidate on #1838 for the validation so it can be bumped in priority.

**Comment by designsimply** [comment]
Re-opening because #1838 was fixed by #11286 but did not address the case where hitting enter after typing something into the button block URL field does not work to apply the link.

There is a request to add an "Open in new window" option to the link inserter in the button block at #8000 and #10128 seeks to update it to use `URLPopover` where hitting enter to apply a link should already be working and would solve this issue once it is put into place.

**Comment by afercia** [comment]
This is still a problem and it's a bit surprising it's still in this state. As mentioned above, reusing `URLPopover` would introduce consistency with the experience and interaction users get when inserting links in other components.

Additionally, for accessibility:
- when inserting the button, initial focus goes to the URL field: this is a problem because to enter the button text keyboard users have to tab backwards; screen reader users have to figure out there's something _before_ that's been just skipped
- when tabbing backwards and focus goes to the button text, indication of focus is definitely insufficient (depending also on the theme colors); see below: with Twenty Nineteen the only indication is the barely noticeable caret within the editable text:

<img width="520" alt="screenshot 2019-02-28 at 14 33 28" src="https://user-images.githubusercontent.com/1682452/53570374-9c825180-3b66-11e9-9f6e-a8181632893d.png">

There's the need of an additional focus indicator.

**Comment by karmatosed** [comment]
Removing the label as agree this needs doing and doesn't need design specifically.

**Comment by Soean** [comment]
The initial issue is fixed in the new URL interface:
<img width="438" alt="Bildschirmfoto 2020-02-24 um 13 46 07" src="https://user-images.githubusercontent.com/695201/75133415-40b4bf00-570d-11ea-91af-d810793eb8cd.png">


But is still adds an invalid href attribute if I input `de.wordpress.org`. The paragraph adds `http://` automatically, but the button doesn't.

**Comment by talldan** [comment]
I noticed a separate issue in Firefox when testing this again:
https://github.com/WordPress/gutenberg/issues/21777

**Comment by michelmany** [comment]
How do I change this UrlPicker to add a default value for the link? I mean, I need to pre-populate this link. Thanks!

**Comment by skorasaurus** [comment]
I'm still able to reproduce this in Gutenberg 9.4.1 on a vanilla, test site (both in chrome and firefox) using the same steps that @maddisondesigns wrote; but after pressing enter, the path of your website is also included. 

For example: if your site is installed at https://nameofyourwebsite.com and you're trying to link to wordpress.stackexchange.com the link becomes : `https://nameofyourwebsite.com/wordpress.stackexchange.com`

**Comment by annezazu** [comment]
Can confirm this happens with WordPress 5.6 and Gutenberg 9.5.2/Gutenberg 9.6 RC as well.

**Comment by paaljoachim** [comment]
I can also confirm that this happens with WP 5.6. and Gutenberg  9.8. 
Tested with Twenty Twenty One.

@noisysocks Robert. This seems like a good candidate for the Must Have project board for WP 5.7.

**Comment by mrwweb** [comment]
This same issue also impacts the Image block.

1. Insert and select image
2. Set link for image
2. Type google.com in the URL field
3. Hit return key to apply changes

Link href is `google.com` and note `http://google.com`.

**Comment by paaljoachim** [comment]
@felixarntz Felix is this an issue you might be able to work on?
Reason to ask is that it seems like you worked on this feature: https://wptavern.com/wordpress-5-7-will-make-it-easier-to-migrate-from-http-to-https

**Comment by paaljoachim** [comment]
The link control component automatically adds http://
Can we transfer the code from there to the Buttons block?

**Comment by carolinan** [comment]
The button block already uses the LinkControl component.

The pattern seems to be:
If you wait for the spinner to finish, and select the link from the search results, it will add the http://.
But if you press the enter key after writing the link, with the input field still focus, it does not add it.

**Comment by paaljoachim** [comment]
WordPress 5.7 RC 1
Gutenberg plugin 10.0.2
Twenty Twenty One.

Retesting

https://user-images.githubusercontent.com/5323259/109720562-8c186d80-7baa-11eb-8004-3a6be6188529.mp4

Conclusion is that one needs to click the URL link to add the http. 
@shaunandrews Shaun is experimenting with Link Control designs in this PR: https://github.com/WordPress/gutenberg/pull/28755

**Comment by Thelmachido** [comment]
I was able to reproduce this on Gutenberg Version 13.7.3 on the Twenty Twenty-Two theme. 

As shown in the short video below, I had two button blocks. 

On the first button, I typed in _wordpress.org_ and I picked the link that was suggested. When I previewed the page this button linked to the _wordpress.org_ site. 


3. On the second button I typed in _wordpress.org_ and then clicked on **return**. This button then added `https://testthelma.mystagingwebsite.com/sample-page/wordpress.org` as the URL which isn't the expected result.


https://user-images.githubusercontent.com/41231764/181713398-2442a0ab-00c0-4d3c-84d4-49fe81695584.mov

**Comment by skorasaurus** [comment]
Hi, 
https://github.com/WordPress/gutenberg/pull/47311 which will be included in gutenberg 15.2, fixes the following issues mentioned in this issue and can be closed: 

_When you enter a url for a button, you can't hit the Return key to apply your changes._


_On top of that, if you type a url without the https:// it displays a random result from your site and when you hit Return, it actually selects that result instead of using the url you typed_

_The button block does not append http to a url_

Please reopen if you are still experiencing one of these issues in Gutenberg 15.2 (which is not yet released to the public).
