### ISSUE TITLE
Block Inserter Panel Does Not Close After Interaction on Mobile/Tablet web editor

### ISSUE THREAD

**Issue by Kallyan01** [WordPress/gutenberg#68790]
### Description

When using the Gutenberg editor on mobile or tablet browsers, the block inserter panel remains open after performing actions such as dragging and dropping or clicking on a block. This behavior is not ideal as it obstructs the editing canvas and disrupts the user experience.

https://github.com/user-attachments/assets/f396ec9e-92be-44fd-be33-83b4e3c35cb5

**Expected Behavior**

The block inserter panel should close automatically once the user interacts with the block list (e.g., after dragging and dropping or clicking on a block). This would improve usability by reducing distractions and providing a smoother editing experience.

### Step-by-step reproduction instructions

1) Open the Gutenberg editor on a mobile or tablet browser.
2) Open the block inserter panel.

![Image](https://github.com/user-attachments/assets/bc0f3354-c285-4f38-9c81-6fcccc9b388e)

3) Attempt to:
- Drag and drop a block to the canvas.
- Click on a block to add it to the editor.
- Observe that the block inserter panel remains open after completing the action.

### Screenshots, screen recording, code snippet

![Image](https://github.com/user-attachments/assets/05015a41-9251-4f0f-adbc-146a6f86f27b)

### Environment info

- Wordpress 6.8
- Gutenberg 20.0.0
- Env Type : Mobile and Tablet Devices 

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [ ] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Kallyan01** [comment]
@ellatrix @bjtitus @Mamaduka can you look into this issue and confirm ?

**Comment by Mamaduka** [comment]
I thought this was resolved. @jeryj, we were discussing something similar very recently.

**Comment by Kallyan01** [comment]
@Mamaduka Checked the latest trunk, the bug still exist ! can you mention the PR / Issue which resolved the issue ?

**Comment by jeryj** [comment]
@Mamaduka - I don't recall working on closing the inserter after mobile/tablet interactions. The closest thing to this I remember is working on the `useZoomOut` hook to not engage on tablet/mobile.

**Comment by Mamaduka** [comment]
I think the issue in question and PR are similar, but not the same - https://github.com/WordPress/gutenberg/pull/67339#issuecomment-2583232271.

Sorry for the confusion, @jeryj!

**Comment by Mamaduka** [comment]
I found an alternative solution that requires fewer changes: #74487.
