### ISSUE TITLE
BorderRadius Presets: Generating wrong variable names in pattern code

### ISSUE THREAD

**Issue by EldarAgalarov** [WordPress/gutenberg#71628]
### Description

Define RadiusSizes preset(s) in theme.json file, like this:
```
"radiusSizes": [
	{
		"name": "Medium",
		"slug": "medium",
		"size": "clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem)"
	}
]
```

Create new block pattern, insert empty group block and set Top Left and Top Right Radius properties to Medium. Set Bottom ones to None. There are generated pattern code:
```
<!-- wp:group {"style":{"border":{"radius":{"topLeft":"clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem)","topRight":"clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem)","bottomLeft":"var:preset|border-radius|0","bottomRight":"var:preset|border-radius|0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-left-radius:clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem);border-top-right-radius:clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem);border-bottom-left-radius:var(--wp--preset--border-radius--0);border-bottom-right-radius:var(--wp--preset--border-radius--0)"></div>
<!-- /wp:group -->
```

- `topLeft` and `topRight` properties have just defined `clamp` values instead of variable name `var:preset|border-radius|medium`;
- `bottomLeft` and `bottomRight` props have wrong and undefined variable name `var:preset|border-radius|0` instead of just `0` (zero).

**ALSO:** The border radius dropdown list is displaying out of the screen borders (to make it visible and clickable need to enable the Shadow property):

<img width="292" height="187" alt="Image" src="https://github.com/user-attachments/assets/b61218d0-c7f8-4535-927d-74f547391e26" />

### Environment info

WP 6.8.2; Gutenberg 21.6.

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by t-hamano** [comment]
Thanks for the report. I was able to reproduce the problem.

**Comment by t-hamano** [comment]
> ALSO: The border radius dropdown list is displaying out of the screen borders (to make it visible and clickable need to enable the Shadow property):

P.S. This is a recognized bug and it would be great if this could also be fixed in WP 6.9: https://github.com/WordPress/gutenberg/pull/67544#issuecomment-3174274306

**Comment by USERSATOSHI** [comment]
Hi, while debugging , I found the main cause of this issue.

First for the clamp value, this was due the decodeValue which was being used in border-panel.js in global-styles to convert the preset into raw values.

https://github.com/wordpress/gutenberg/blob/trunk/packages/block-editor/src/components/global-styles/border-panel.js#L153-158

doing the following fixes the raw clamp value and will use the preset format.

```diff
return {
-			topLeft: decodeValue( border?.radius?.topLeft ),
-			topRight: decodeValue( border?.radius?.topRight ),
-			bottomLeft: decodeValue( border?.radius?.bottomLeft ),
-			bottomRight: decodeValue( border?.radius?.bottomRight ),
+			topLeft: border?.radius?.topLeft,
+			topRight: border?.radius?.topRight,
+			bottomLeft: border?.radius?.bottomLeft,
+			bottomRight: border?.radius?.bottomRight,
		};
```

for invalid preset for None ( 0 )

this was cause we were not checking if the slug is '0' in which case

```js
if ( spacingMatch.slug === '0' ) {
	return '0';
}
``` 
should fix that.
( unless this was intentional )


the result after this returns the correct pattern code
```
<!-- wp:group {"style":{"border":{"radius":{"topLeft":"var:preset|border-radius|medium","topRight":"var:preset|border-radius|medium","bottomLeft":"0","bottomRight":"0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-left-radius:var(--wp--preset--border-radius--medium);border-top-right-radius:var(--wp--preset--border-radius--medium);border-bottom-left-radius:0;border-bottom-right-radius:0"></div>
<!-- /wp:group -->
```

<img width="1470" height="713" alt="Image" src="https://github.com/user-attachments/assets/6d94eb54-69de-49a2-ad8a-60bf54794f81" />

If this looks fine, I am happy to create PR with the fix and tests 

cc: @t-hamano @EldarAgalarov

**Comment by EldarAgalarov** [comment]
@t-hamano @USERSATOSHI  Following bug still presents: On selecting `None` outputs invalid variable name `var:preset|border-radius|0`:

```
<!-- wp:group {"style":{"border":{"radius":{"topLeft":"var:preset|border-radius|0","topRight":"var:preset|border-radius|0","bottomLeft":"var:preset|border-radius|0","bottomRight":"var:preset|border-radius|0"}}},"layout":{"type":"constrained"}} -->
<div class="wp-block-group" style="border-top-left-radius:var(--wp--preset--border-radius--0);border-top-right-radius:var(--wp--preset--border-radius--0);border-bottom-left-radius:var(--wp--preset--border-radius--0);border-bottom-right-radius:var(--wp--preset--border-radius--0)"></div>
<!-- /wp:group -->
```

<img width="458" height="119" alt="Image" src="https://github.com/user-attachments/assets/b2b79de7-7a6a-4ede-902f-9fc92b63533d" />

Tested on Gutenberg 21.7.

**Comment by t-hamano** [comment]
@USERSATOSHI Do you have the bandwidth to investigate the problem? 🙏

**Comment by USERSATOSHI** [comment]
> [@USERSATOSHI](https://github.com/USERSATOSHI) Do you have the bandwidth to investigate the problem? 🙏

Sure, let me investigate this now.

**Comment by USERSATOSHI** [comment]
Hi, @EldarAgalarov can you send a minimal theme.json so I can reproduce this, cause it seems like the size is not set to 0 but the slug is '0'.

**Comment by EldarAgalarov** [comment]
@USERSATOSHI  I'm using followig BorderRadius presets:

```
"radiusSizes": [
	{
		"name": "Small 3X",
		"slug": "small-xxx",
		"size": "clamp(0.125rem, 0.1106rem + 0.0641vw, 0.1875rem)"
	},
	{
		"name": "Small 2X",
		"slug": "small-xx",
		"size": "clamp(0.25rem, 0.2356rem + 0.0641vw, 0.3125rem)"
	},
	{
		"name": "Small X",
		"slug": "small-x",
		"size": "clamp(0.3125rem, 0.2692rem + 0.1923vw, 0.5rem)"
	},
	{
		"name": "Small",
		"slug": "small",
		"size": "clamp(0.4375rem, 0.3942rem + 0.1923vw, 0.625rem)"
	},
	{
		"name": "Medium",
		"slug": "medium",
		"size": "clamp(0.6875rem, 0.6298rem + 0.2564vw, 0.9375rem)"
	},
	{
		"name": "Large",
		"slug": "large",
		"size": "clamp(0.875rem, 0.7885rem + 0.3846vw, 1.25rem)"
	},
	{
		"name": "Large X",
		"slug": "large-x",
		"size": "clamp(1.3125rem, 1.1827rem + 0.5769vw, 1.875rem)"
	},
	{
		"name": "Large 2X",
		"slug": "large-xx",
		"size": "clamp(1.75rem, 1.5769rem + 0.7692vw, 2.5rem)"
	},
	{
		"name": "Large 3X",
		"slug": "large-xxx",
		"size": "clamp(2.625rem, 2.3654rem + 1.1538vw, 3.75rem)"
	}
]
```

**Comment by USERSATOSHI** [comment]
Thank you

**Comment by USERSATOSHI** [comment]
@t-hamano, @EldarAgalarov I think I found the issue,

<img width="301" height="51" alt="Image" src="https://github.com/user-attachments/assets/20cd9102-d8a4-4cd6-ae2b-b9b03aba9485" />

None has a size 1 and slug '0' due to which it adds that preset string but If I use the slug to check if it is '0' then It would conflict with custom ones that have non zero size but slug as '0'.

Ref: https://github.com/WordPress/gutenberg/pull/71631#discussion_r2348764168
