### ISSUE TITLE
Template activation experiment follow-ups

### ISSUE THREAD

**Issue by ellatrix** [WordPress/gutenberg#71735]
- [ ] Re-attempt since it was reverted for 6.9 (#73025). This is blocked until we agree on the design and UX.
---
Starting a tracking issue for all the template activation (#67125) follow-ups. Let's prefer sub-issues for new items since we still have the experiment.
- [ ] Change template type to just type, show it in the document panel. https://github.com/WordPress/gutenberg/pull/72775
- [ ] Specific templates no longer get a title, the title seems to be prefilled with a slug.
- [ ] When an active template is deleted, it should be removed from the option.
- [ ] Make descriptions editable. https://github.com/WordPress/gutenberg/pull/72791
- [ ] When creating templates through the modal, allow giving it a name. 
- [ ] Check why getHomePage is not invalidating. https://github.com/WordPress/gutenberg/pull/67125#discussion_r2354894647
- [ ] When checking active templates, take into account the edited site option.
- [ ] Some plugins like Woo are adding a filter to `get_block_templates` with user templates. That should not be happening.

<details><summary>Old</summary>
- [x] Remove the Reset action. https://github.com/WordPress/gutenberg/pull/72679
- [x] Review design and UX of showing "Status: N/A" when a template is a custom one, per https://github.com/WordPress/gutenberg/pull/72499#discussion_r2447579211.
- [x] Core changes should be synced back to Gutenberg. Some more back-compat issues were addressed there. https://github.com/WordPress/gutenberg/pull/72680
- [x] https://github.com/WordPress/gutenberg/issues/71724
- [x] https://github.com/WordPress/gutenberg/issues/71765
- [x] https://github.com/WordPress/gutenberg/issues/71770
- [x] Add meta for newly created templates. Fixed in #72156.
- [x] Remove `core-data` hacks. E.g. https://github.com/WordPress/gutenberg/pull/67125#discussion_r2354891236. Fixed in #72285.
- [x] Add some back-compat for the `wp_template` REST API endpoint. Querying by old slug should still work. List things we're breaking. https://github.com/WordPress/gutenberg/pull/67125#discussion_r2354877717. Fixed in #72223. 
- [ ] Wherever both endpoints are used, like the active list and `useTemplates`, try to refactor to not merge both results. https://github.com/WordPress/gutenberg/pull/67125#discussion_r2354907842
- [x] Check if the auto-draft logic can be adjusted. See https://github.com/WordPress/gutenberg/pull/67125#discussion_r2354896706. Fixed in #72285.
- [x] Add more comments for get_block_template overrides. https://github.com/WordPress/gutenberg/pull/67125#discussion_r2354881530
- [x] Add a modal when "editing" a theme/plugin template. Maybe this also allows us to get rid of some hacks like auto-drafting. Fixed in #72285.
- [x] During template resolution, check if the theme terms match the current theme.
- [ ] Consider exposing "isCustom" on templates via REST API to avoid [hacks like this](https://github.com/WordPress/gutenberg/blob/ea8144bcc9b16bb8c483060abedbaf8363ad30e3/packages/edit-site/src/components/page-templates/index.js#L157-L162).
- [ ] Add modal when deactivating templates and give to option to either reset to the theme or disable the template entirely.
- [ ] Add a modal when activating a template, maybe show a modal explaining that the currently active template will be deactivated, see https://github.com/WordPress/gutenberg/issues/72035#issuecomment-3414679521.
- [x] Surface revisions in the editor.

<details>

**Comment by kmanijak** [comment]
Hey @ellatrix , adding another one https://github.com/WordPress/gutenberg/issues/71770.

Also, adding to the list https://github.com/WordPress/gutenberg/issues/71765 raised by @Aljullu today.

---

I know I've initially given a green light on the PR but I'm having more doubts about it. There's seems to be quite a lot of issues and finding more. Are we sure they can all be fixed before GB 21.7 is out?

**Comment by ellatrix** [comment]
As we discussed 21.9 is the last one to go in 6.9, so let's see if we can fix the critical issues before the GB stable.

**Comment by kmanijak** [comment]
Added one related to `@wordpress/e2e-test-utils-playwright`: https://github.com/WordPress/gutenberg/issues/71815

**Comment by kmanijak** [comment]
Adding some findings based on current `trunk` (so with https://github.com/WordPress/gutenberg/pull/71811 and https://github.com/WordPress/gutenberg/pull/71798). 

**Major:**
1. Custom templates don't display titles but slugs in Editor. Is that expected. Example:

WP 6.8 | With GB enabled
-- | -- 
<img width="1003" height="441" alt="Image" src="https://github.com/user-attachments/assets/4ba2a683-0d71-408d-ba9c-c3f1683cca37" /> <img width="336" height="421" alt="Image" src="https://github.com/user-attachments/assets/0366c255-cbfa-45ca-80e9-7270fa609ad2" /> | <img width="811" height="407" alt="Image" src="https://github.com/user-attachments/assets/7328f983-f400-4f5f-bb0b-8219b1058c17" />

2. "Edit Site" in the admin bar redirects to "You attempted to edit an item that doesn't exist. Perhaps it was deleted?" page.

**Minor:**

1. Moving Active template to trash doesn't deactivate them. I think I'd expect the default template to be activated automatically
2. Once you update the template and activate it, I'd appreciate redirecting or updating the URL to the new, custom template. Otherwise I make updates to default template, save it, activate it and upon page refresh the edits seems to be gone. They're not, you're just back at default template but I guess it may be confusing.
    - But that also leads to engineering side - some of our test relies on refreshing the Editor. As an 3rd party dev, is there a way to know what is the post ID of newly created template in such case?

@ellatrix, I'm still testing it so there may be more issues but posting the first batch already.

**Comment by ellatrix** [comment]
> Moving Active template to trash doesn't deactivate them. I think I'd expect the default template to be activated automatically


Yeah this one is already in the list

**Comment by ellatrix** [comment]
> Custom templates don't display titles but slugs in Editor.

I can't reproduce this, I tried with Woo 10.2.2

**Comment by jennydupuy** [comment]
I am conducting tests related to [templates management](https://make.wordpress.org/test/2025/10/03/help-test-changes-to-template-management/)
and I am encountering this problem: Sorting templates by status causes an error in the template editor ([72278](https://github.com/WordPress/gutenberg/issues/72278)).

**Comment by jhmonroe** [comment]
Same! Tried testing Gutenberg to sort by status (after successfully seeing the little green "Active" flag on the templates in my blank test site.

Yields the error below:

<img width="924" height="148" alt="Image" src="https://github.com/user-attachments/assets/8e99b16c-511d-4dd6-ba3e-930b26c2db2b" />

```
TypeError: e.localeCompare is not a function
    at Object.sort (http://blanksite.local/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=1761143751529:115:189829)
    at Object.i [as sort] (http://blanksite.local/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=1761143751529:115:232573)
    at http://blanksite.local/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=1761143751529:115:257774
    at Array.sort (<anonymous>)
    at Ou (http://blanksite.local/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=1761143751529:115:257702)
    at http://blanksite.local/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=1761143751529:115:296083
    at Object.Yh [as useMemo] (http://blanksite.local/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:114:243)
    at c.useMemo (http://blanksite.local/wp-content/plugins/gutenberg/build/vendors/react.min.js?ver=18:29:377)
    at Wk (http://blanksite.local/wp-content/plugins/gutenberg/build/edit-site/index.min.js?ver=1761143751529:115:296078)
    at mf (http://blanksite.local/wp-content/plugins/gutenberg/build/vendors/react-dom.min.js?ver=18:105:412)
```

There is no way to make the error message go away. Refreshing the page. Turning off checkboxes in Gutenberg. Only way is to completely deactivate Gutenberg. There is no checkbox under Gutenberg > Experiments to turn off the template management/active feature

Presumably I would have to clear something in the database to be able to continue using Gutenberg in my local test site. Does anyone know what value to change? Guessing it's in the table for OPTIONS or USERMETA?

PS: Found @t-hamano  comment in [#72278](https://github.com/WordPress/gutenberg/issues/72278#issuecomment-3436338843) but maybe someone knows a fix to remove the database entry manually so the templates page is usable again with gutenberg installed?

PPS: If anyone runs into this issue and needs to get your test site working again with Gutenberg, I deleted all meta values for wp_persisted_preferences under user meta in the database! You'll lose your other prefs but this was easiest way

> I am conducting tests related to [templates management](https://make.wordpress.org/test/2025/10/03/help-test-changes-to-template-management/) and I am encountering this problem: Sorting templates by status causes an error in the template editor ([72278](https://github.com/WordPress/gutenberg/issues/72278)).

**Comment by t-hamano** [comment]
> Sorting templates by status causes an error in the template editor (https://github.com/WordPress/gutenberg/issues/72278).

This issue was resolved by #72648, so this problem should no longer occur in Beta2.

**Comment by burnuser** [comment]
New issue: https://github.com/WordPress/gutenberg/issues/72865
WP 6.9 Beta 2: Edit Template on Theme Templates still exists but does not work any longer!

**Comment by t-hamano** [comment]
Since the template activation feature has been punted to 7.0, I'd like to punt this issue to 7.0 accordingly.

**Comment by ellatrix** [comment]
This is blocked by new designs, no punting to the future until we align on a design and user experience.
