### ISSUE TITLE
Notes: improve alignment between Notes and the selected block

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/gutenberg#72331]
### Description

This Issue addresses improving the floating Notes to better match the desired behavior.

In https://github.com/WordPress/gutenberg/pull/72216 we landed the floating notes feature where notes float alongside their related blocks. That PR included handling to avoid overlapping notes: for example when a post contains many short blocks each with comments. The approach used in the PR is to push down any thread that would otherwise overlap the thread above it.

In the spec shared in this comment from @jasmussen https://github.com/WordPress/gutenberg/pull/71856#issuecomment-3379946322 the behavior is slightly different- when a thread is selected, it is placed next to its related block - all threads below are pushed down to avoid overlap, all threads above are pushed up to avoid overlap:

![Image](https://github.com/user-attachments/assets/1a73918b-d707-4514-baac-9ff56dd83bde)

PR to resolve this: https://github.com/WordPress/gutenberg/pull/72309

### Step-by-step reproduction instructions

1. Create a post with many short (one line) blocks
2. add a note to each block
3. select notes by clicking a block or a floating note

Expected behavior:
* The thread floats directly beside its block
* threads below shift down to avoid overlapping each other
* threads above shift up to avoid overlapping

### Screenshots, screen recording, code snippet

https://github.com/user-attachments/assets/c22bc3b6-2266-4034-b2ad-1a3b8d4532b2

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by annezazu** [comment]
Just was testing it this morning and came here to report the same thing:

https://github.com/user-attachments/assets/1f7d716f-9e03-441f-9f78-1e1b434b27ae

Beyond not aligning with design spec, it also leads to Notes getting cut off and it's hard to associate them with the selected block.

**Comment by adamsilverstein** [comment]
@annezazu https://github.com/WordPress/gutenberg/pull/72309 should fix this and is ready for merge, can you give it a test?

**Comment by annezazu** [comment]
It's better but it didn't fully fix it. Left a comment there. Happy to test again.

**Comment by adamsilverstein** [comment]
I created a follow up issue to address the case where a comment overflows the bottom edge of the editor and gets cut off - https://github.com/WordPress/gutenberg/issues/72440
