### ISSUE TITLE
Notes appearing on site frontend and as Recent Comments on Dashboard

### ISSUE THREAD

**Issue by jeffpaul** [WordPress/gutenberg#72607]
### Description

As originally reported by https://profiles.wordpress.org/burnuser/ and confirmed by https://profiles.wordpress.org/shsajalchowdhury/ in https://wordpress.org/support/topic/showing-new-notes-under-recent-comments-in-dashboard-is-tricky/#post-18691377, Notes appear on the site frontend as though they were Comments and also in the WP Admin dashboard Recent Comments.

### Step-by-step reproduction instructions

Create a post
add sample paragraph block text
add a Note
view WP Admin dashboard & post frontend to see Notes appearing alongside frontend Comments

### Screenshots, screen recording, code snippet

Frontend view of Notes: https://prnt.sc/v03LGZcRX1BD
View of Notes increasing Comments on post: https://prnt.sc/DMtU9t8IC2ks

View of Notes appearing in Recent Comments in Dashboard:

<img width="1146" height="1372" alt="Image" src="https://github.com/user-attachments/assets/294d2aca-e5ca-4419-9ceb-4ed5b3012d9d" />

### Environment info

WP 6.9-beta1
Tested with Gutenberg 21.9.0 **DEACTIVATED**

### Please confirm that you have searched existing issues in the repo.

- [x] Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

- [x] Yes

### Please confirm which theme type you used for testing.

- [x] Block
- [ ] Classic
- [ ] Hybrid (e.g. classic with theme.json)
- [ ] Not sure

**Comment by Mamaduka** [comment]
This happens only in WP 6.9 Beta when the Gutenberg plugin is not active. To reproduce the same issue with Gutenberg, you'll need to remove the `exclude_block_comments_from_admin` filter. During the core sync, it was decided not to use a similar filter and modify the admin comment list queries directly. 

## Problem

The Comment Query's default value for `type` is an empty string, which means [`all` types are returned](https://github.com/WordPress/wordpress-develop/blob/97382397b2bd7c85aef6d4cd1c10bafd397957fc/src/wp-includes/class-wp-comment-query.php#L780-L784). We'll have to modify this logic in a backward-compatible manner, maybe giving it a different meaning - all types except `note`.

Unfortunately, I'm not sure what the best way to do it is. Hardcode it, use a filter like we do in Gutenberg, or something else.


cc @peterwilsoncc, @swissspidy

**Comment by swissspidy** [comment]
Should this be discussed in a Trac ticket instead?

Also cc @adamsilverstein

**Comment by t-hamano** [comment]
This issue is probably also related: https://github.com/WordPress/gutenberg/issues/72548

**Comment by adamsilverstein** [comment]
> Should this be discussed in a Trac ticket instead?

I agree, I will create a Trac ticket for this issue since its a core-specific implementation.

**Comment by adamsilverstein** [comment]
I opened a trac ticket to discuss the best way forward in core: https://core.trac.wordpress.org/ticket/64145

**Comment by adamsilverstein** [comment]
Fixed in https://github.com/WordPress/wordpress-develop/pull/10405

**Comment by gubser** [comment]
I accidentally stumbled on this. In my WordPress 7.0.1 instance, the RSS feeds at `<site-url>/comments/feed` and `<site-url>/comments/feed/atom` still show these internal notes. :-/

Should i create a new issue?  And if yes, where?

**Comment by t-hamano** [comment]
Hi @gubser, I also investigated, and I believe your report is correct. It appears that the check for "comment_type" is missing within the WP_Query class. As this issue needs to be fixed in the WordPress core, could you submit [a core new ticket](https://core.trac.wordpress.org/newticket)?

**Comment by gubser** [comment]
I opened ticket https://core.trac.wordpress.org/ticket/65613

**Comment by adamsilverstein** [comment]
I have posted a fix for this in https://github.com/WordPress/wordpress-develop/pull/12486, testing appreciated!
