### ISSUE TITLE
Columns Block (beta): long content in doesn't wrap and pushes editor off page

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#7921]
**Describe the bug**
Adding in long amounts of text pushes the whole editor off the edge of the page.

![gutenberg_columnblockforcesblockoffedgeofpage](https://user-images.githubusercontent.com/2078245/42615425-9092b312-85ed-11e8-9e62-0eac66d2cedf.gif)

**To Reproduce**
1. Add column Block
2. Add some text to one column
3. Add text without spaces to another column

**Expected behavior**
Content should wrap

_macOS Sierra 10.12.1
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.2.0_

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.7 and Gutenberg 3.2.0 on Firefox 61.0.1 on macOS 10.13.5.

![screen shot 2018-07-16 at mon jul 16 4 50 59 pm](https://user-images.githubusercontent.com/1119271/42787629-966227d6-8918-11e8-9c7a-259fcca5c97c.png)

**Comment by maddisondesigns** [comment]
This also breaks the front-end as well and causes horizontal scrolling.

![gutenberg_columnscontentdoesntbreakword](https://user-images.githubusercontent.com/2078245/42938244-fb9dbace-8b94-11e8-9f32-47c8c902156c.gif)

You need to add `word-break: break-all;` on `.wp-block-column`

**Comment by eddhurst** [comment]
Testing this on 3.9 - I think the back-end issue here has been resolved somewhere along the line.

![screen shot 2018-09-26 at 13 54 59](https://user-images.githubusercontent.com/9933592/46081310-20897500-c194-11e8-9be9-9d0cda8a8e97.png)

The front end issue however has not been resolved.

![screen shot 2018-09-26 at 13 58 50](https://user-images.githubusercontent.com/9933592/46081412-575f8b00-c194-11e8-8272-b07765aae868.png)

**Comment by ZebulanStanphill** [comment]
I can still reproduce this issue in `master`. (Tested in Firefox Beta.)
![image](https://user-images.githubusercontent.com/19592990/46186747-c24cb700-c2a5-11e8-948d-56afec314d29.png)

**Comment by maddisondesigns** [comment]
Can confirm, yep, this is still an issue on the front-end and back-end.

Back-end vid: https://cl.ly/c7e79cefe9c6

Front-end vid: https://cl.ly/bbc80ba11159

**Comment by maddisondesigns** [comment]
@eddhurst Not sure why you would do `word-break: break-word;`. The allowable values for `word-break` are `normal | keep-all | break-all`.

https://www.w3.org/TR/css-text-3/#word-break-property

**Comment by eddhurst** [comment]
@maddisondesigns That is true, but `word-break: break-all;` is definitely not the expected behaviour of text within a column - and aggressively breaks words, even if they would otherwise wrap.

`break-word` is unofficial, but supported by Chrome, Safari and Chrome, Safari and other WebKit/Blink browsers: https://caniuse.com/#search=word-break

**Comment by eddhurst** [comment]
I have updated the initial PR, which correctly fixes this issue. I realised that `word-break: break-word` is effectively just treated as `word-wrap: break-word` 

word-wrap has much better browser support and is understood by FF, IE and Edge.

**Comment by eddhurst** [comment]
This appears to have been fixed in the last few updates to columns

**Comment by ajtruckle** [comment]
I have issues. See: https://wordpress.org/support/topic/word-wrapping-in-column-2-of-internet-explorer-microsoft-edge/

**Comment by designsimply** [comment]
I replied to your forum post with the results of a test I ran.
