### ISSUE TITLE
Tooltips interfering with block up and down UI

### ISSUE THREAD

**Issue by tomjn** [WordPress/gutenberg#8543]
**Describe the bug**

If you go to move a block down, but change your mind, you can move the mouse up and click on the up button instead.

However, if you lingered a little too long, a tooltip appears covering the up button, and mousing upwards puts the cursor over this tooltip, preventing the up arrow button from being clicked:

<img width="194" alt="screen shot 2018-08-05 at 02 02 28" src="https://user-images.githubusercontent.com/58855/43681712-a4199266-9853-11e8-936f-afd06016a70d.png">

Additionally, once the mouse is over the tooltip, the button UI dissapears, but the tooltip persists:

<img width="275" alt="screen shot 2018-08-05 at 02 02 04" src="https://user-images.githubusercontent.com/58855/43681707-9526aa5a-9853-11e8-8f5b-899c180537bf.png">

**To Reproduce**

0. Select a block
1. However over the down button
2. Wait for the tooltip to show
3. Try to click the up button

**Expected behavior**

I expected to be able to mouse over the button

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser Chrome
 - Version 68

**Additional context**
- v3.4

Thoughts:

 - The tooltips might be better appearing to the side
 - Larger target areas would be helpful, it wasn't comfortable targeting the buttons, and it wasn't clear what their bounds were
 - the buttons have a hover and a focus styling, but no active/down styling, I expected the buttons to 'depress' when pushed, as implied by the shadows on hover

**Comment by SuperGeniusZeb** [comment]
This would be solved by an implementation of #6224.

![image](https://user-images.githubusercontent.com/19592990/43688894-285a3810-98b7-11e8-8cf7-2f2526a278c1.png)

**Comment by swissspidy** [comment]
While #6224 would solve this particulsr issue, I‘m sure similar ones will be exposed at some point.

Perhaps we could make the tooltips more clever. For example, GotHub‘s own open source UI library allows positioning tooltips every way possible using a few CSS classes.

**Comment by designsimply** [comment]
Tested with WordPress 4.9.8 and Gutenberg 3.4.0 on Firefox 61.0.1 on macOS 10.13.6 and confirmed that the block movers disappear and leave the "Move Down" tooltip in place if you select a block and quickly move the mouse over the top of the tooltip that appears. ([1m20s](https://cloudup.com/cj-EuuFd5CU))

Note: added a clarifying step since this only happens for a currently selected block.

**Comment by chrisvanpatten** [comment]
I was unable to reproduce in 3.8 in Safari, Firefox, and Chrome which I think means this is solved! I'm going to close it up but @tomjn can you check on your end as well, and if I'm wrong feel free to reopen! 🚀

**Comment by ZebulanStanphill** [comment]
@chrisvanpatten I can still reproduce in `master`, though I am not really sure this issue is really an issue. Tooltips are supposed to stay visible when you hover over them.

**Comment by chrisvanpatten** [comment]
@ZebulanStanphill What browser are you using?

**Comment by chrisvanpatten** [comment]
@ZebulanStanphill I just tried again, this time on `master`, and now I _am_ able to reproduce. So… who knows what's going on 😂

Agreed that it's technically the correct behavior, but maybe there's a way the tooltips could be positioned to the side, or have the "move down" tooltip below the button?

In any event, I'm reopening now. Sorry about that; mea culpa!

**Comment by youknowriad** [comment]
This was fixed recently.
