### ISSUE TITLE
White screen that shows me nothing

### ISSUE THREAD

**Issue by danieltj27** [WordPress/gutenberg#8960]
**Describe the bug**
When activating the Gutenberg plugin from the 4.9.8 callout, it takes you to a page that I assume should be the demo page judging by the URL (`/wp-admin/post-new.php?gutenberg-demo`) but it's just a blank white screen.

**To Reproduce**
1. Install WordPress 4.9.8 and login
2. Click to install Gutenberg from the callout added in 4.9.8
3. Click to activate the plugin
4. Redirected to a white screen

**Expected behavior**
I expect to see the post edit screen with the Gutenberg editor, not a blank screen.

**Screenshots**
Just a white screen.

**Desktop (please complete the following information):**
- macOS High Sierra, Chrome 68
- Gutenberg 3.5.0

**Additional context**
N/A

**Comment by danieltj27** [comment]
Oops, this issue here is that as it was a new setup, the rewrite links were not flushed so the API route wasn't defined (there was a 404 in the console trying to find `wp-json/wp/v2`). Fixed... kind of.

**Comment by pento** [comment]
Hey, @danieltj27.

By "kind of", do you mean it's working now, or there's something else not loading correctly?

**Comment by danieltj27** [comment]
Fixed kind of in a sense of whilst it's now working fully, as Gutenberg relies on the rest API, I'd expect some kind of message alerting me that the API is unreachable (or just have Gutenberg flush permalinks on activation to try and avoid this issue altogether).

**Comment by gilesfraser123** [comment]
I have the same problem, I installed Gutenberg and now get a white editing area when I try to edit a page. I have no idea how to sort it out.

**Comment by FilRav** [comment]
White page after upgrading from version 3.4.0 to 3.5.0. 
(Wordpress version 4.9.8-it with default theme Twenty Seventeen. I had also the plugin "Insert Pages" ver 3.4.2, but after reinstalling old version of Gutenberg everything work again)

**Comment by danieltj27** [comment]
Go to Settings > Permalinks and click the save changes button which flushes the rewrite rules. That should solve the problem (unless it's a deeper issue).

Gutenberg (whilst it's a plugin at least) should do this for you on activation considering it completely relies on the REST API.

**Comment by FilRav** [comment]
Thank you for your quick answer. I've tried but unfortunately it doesn't solve the issue. I revert to 3.4.0 version :P

**Comment by gilesfraser123** [comment]
Doesnt solve the issue for me either. still get a white editing area.

**Comment by FilRav** [comment]
[SOLVED]
I've changed the browser from Google Chrome 49.0.2623.112 to Firefox 52.9.0 and I can edit the page as usual. There's no need to go to Settings > Permalinks to flushe changes. Thank you

**Comment by gilesfraser123** [comment]
Still doesnt do it for me. I shall leave it alone until there is an update.

**Comment by FilRav** [comment]
I noted that if a page has gallery with "Link to none" it can result to a white page (it has also a shortcode for "insert page" in my case). As soon I switched to "Link to media" in gallery options, the page becomes editable again (I have to switch browser from Firefox to Google Chrome and viceversa)

**Comment by designsimply** [comment]
> As Gutenberg relies on the rest API, I'd expect some kind of message alerting me that the API is unreachable.

Noting that this is being tracked in #8549.
