### ISSUE TITLE
Gutenberg + Markdown + Page === Bad experience

### ISSUE THREAD

**Issue by westi** [WordPress/gutenberg#9331]
**Describe the bug**
If you have markdown enabled in a plugin like Jetpack's `WPCom_Markdown` we attempt to disable it so it doesn't mangle the block content - `gutenberg_remove_wpcom_markdown_support`

This seems to work fine on posts but not for pages.

**To Reproduce**
1. Install Gutenberg and Jetpack
2. Enable Markdown in Jetpack
3. Create a new page using Gutenberg with multiple paragraphs
4. View page on the front end and be disappointed that all the paragraphs have merged

**Expected behavior**
Paragraphs don't merge

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Firefox
 - Version 61.0.2

**Comment by westi** [comment]
Note: When checking the database you can see that the `<p>` tags inside `<!-- wp:paragraph -->` got stripped on save.

**Comment by youknowriad** [comment]
Thanks for opening the issue, I remember similar issues in the past that have been fixed on JetPack directly? Did you raise an issue there to see if they are working on compatibility and if they are aware of this bug?

**Comment by mkaz** [comment]
I just tested this with Gutenberg 3.9.0 and WordPress 4.9.8 on a local install and could not duplicate with pages (or posts).  Also checking the db and the `<p>` are still present.

The filter is attached to `wp_insert_post_data` which should be called for both Posts and Pages, so I'm not sure why the two would be different. Defined here: https://github.com/WordPress/gutenberg/blob/master/lib/plugin-compat.php

We had a bug on WPCOM that I fixed on our internal API, so possible you saw this same bug there.

**Comment by youknowriad** [comment]
Closing, let us know if you're still seeing this.

**Comment by westi** [comment]
> We had a bug on WPCOM that I fixed on our internal API, so possible you saw this same bug there.

This was observed on WPCOM.

**Comment by AdrienM76** [comment]
I'm still seeing this using Firefox-dev 65.0b9 on MacOS 10.14.2 in Posts as well, not just Pages. When I deactivate Jetpack, the <p> tags are preserved.
