### ISSUE TITLE
Small spacing issue

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9749]
The negative margin for second last panel of the settings 

Here is screenshot - https://goo.gl/WXJg4i

Advance CSS class should have this -ve padding instead of second last setting panel.

**Comment by youknowriad** [comment]
Which version are you testing because this should be fixed now.

**Comment by prajaktagadhave** [comment]
3.8.0

**Comment by prajaktagadhave** [comment]
I still facing this issue in 3.9.0 too. Any update regarding this?

**Comment by youknowriad** [comment]
Are you still seeing this issue? I can't reproduce in my testing. I'm closing for now, let's reopen if we find reproducible steps. (Maybe a browser issue)?
